"use client";

// ЭШ Study by Topic — the public map of the exam's mathematics.
//
// FIVE MAIN TOPICS (the ministry's strands, lib/esh-questions ESH_DOMAINS),
// each opening into its subtopic courses. Until 2026-08-12 this page was a
// hand-written list from before the course system existed: eight flat topics
// with invented weights ("Algebra ~25%") and subtopic chips that linked
// nowhere. Everything here is now derived — the grouping from ESH_DOMAINS,
// the courses from lib/esh-course, and the weights MEASURED from the 980
// tagged past-paper questions (data/esh/exam-weights.json, regenerated by
// scripts/esh/build_exam_weights.py and freshness-checked by
// scripts/verify-esh-question-topics.test.ts).
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { useLang } from "@/lib/lang-context";
import { eshCoursesByDomain, liveUnitCount, totalUnitCount } from "@/lib/esh-course";
import examWeights from "@/data/esh/exam-weights.json";

// Short bilingual framing per main topic — page copy, not taxonomy.
const DOMAIN_COPY: Record<string, { en: string; mn: string }> = {
  algebra: {
    en: "The largest share of the exam: numbers and expressions, equations, sets, functions, logarithms, sequences, and complex numbers.",
    mn: "Шалгалтын хамгийн их хувь: тоо ба илэрхийлэл, тэгшитгэл, олонлог, функц, логарифм, дараалал, комплекс тоо.",
  },
  geometry_trig: {
    en: "Plane and solid geometry, trigonometry, and vectors and matrices — nearly a third of every paper.",
    mn: "Хавтгай ба огторгуйн геометр, тригонометр, вектор ба матриц — тест бүрийн бараг гуравны нэг.",
  },
  analysis: {
    en: "Limits, derivatives, and integrals. Concentrated in the hardest questions of both sections.",
    mn: "Хязгаар, уламжлал, интеграл. Хоёр хэсгийн хамгийн хэцүү бодлогуудад төвлөрдөг.",
  },
  probability_stats: {
    en: "Probability theory and data analysis, from counting outcomes to reading distributions.",
    mn: "Магадлалын онол ба өгөгдлийн шинжилгээ — үр дүн тоолохоос тархалт унших хүртэл.",
  },
  combinatorics: {
    en: "A small but reliable slice of the exam — and the entry point to half of probability.",
    mn: "Шалгалтын багавтар ч тогтмол хэсэг — магадлалын талын үүд.",
  },
};

type WeightEntry = {
  key: string;
  count: number;
  sharePct: number;
  topics: { topic: string; count: number; sharePct: number }[];
};

export default function TopicsPage() {
  const { lang } = useLang();
  const t = (en: string, mn: string) => (lang === "mn" ? mn : en);
  const weightOf = new Map(
    (examWeights.domains as WeightEntry[]).map((d) => [d.key, d]),
  );

  return (
    <div className="min-h-screen pt-20" style={{ background: "var(--bg)" }}>
      {/* Hero */}
      <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pt-12 pb-10">
        <div className="eyebrow mb-3">{t("ЭШ Topics · Math", "ЭШ Сэдвүүд · Математик")}</div>
        <h1
          className="serif"
          style={{
            fontWeight: 400,
            fontSize: "clamp(48px, 7vw, 88px)",
            letterSpacing: "-0.04em",
            lineHeight: 0.96,
            color: "var(--fg)",
          }}
        >
          {t("Study by ", "Сэдвээр ")}
          <em className="serif-italic" style={{ color: "var(--accent)" }}>
            {t("topic", "суралцах")}
          </em>
          .
        </h1>
        <p className="serif mt-5 max-w-2xl" style={{ fontSize: 18, lineHeight: 1.5, color: "var(--fg-1)" }}>
          {t(
            "Five main topics, following the ministry curriculum's own strands, each opening into its subtopic courses. The weights are measured from every question of the real past papers on this site.",
            "Яамны сургалтын хөтөлбөрийн дагуу таван үндсэн сэдэв, тус бүр нь дэд сэдвийн курсүүдтэй. Жин тус бүрийг энд буй жинхэнэ өмнөх жилийн тестүүдийн бүх бодлогоос хэмжсэн.",
          )}
        </p>
        <p className="mono text-[11px] uppercase mt-4" style={{ color: "var(--fg-3)", letterSpacing: "0.06em" }}>
          {examWeights.basedOn.papers} {t("past papers", "тест")} · {examWeights.basedOn.questions} {t("questions measured", "бодлого хэмжив")}
        </p>
      </section>

      {/* Five main topics */}
      <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-10" style={{ borderTop: "1px solid var(--line)" }}>
        <div className="space-y-12">
          {eshCoursesByDomain().map(({ domain, courses }, di) => {
            const w = weightOf.get(domain.key);
            const copy = DOMAIN_COPY[domain.key];
            const topicPct = new Map((w?.topics ?? []).map((x) => [x.topic, x.sharePct]));
            return (
              <div key={domain.key} id={domain.key}>
                {/* Domain header */}
                <div className="flex items-start justify-between gap-4 flex-wrap mb-1.5">
                  <div className="min-w-0">
                    <div className="eyebrow mb-1.5" style={{ color: "var(--accent)" }}>
                      {String(di + 1).padStart(2, "0")} · {t("Main topic", "Үндсэн сэдэв")}
                    </div>
                    <h2
                      className="serif"
                      style={{ fontWeight: 400, fontSize: "clamp(28px, 4vw, 40px)", letterSpacing: "-0.02em", color: "var(--fg)", lineHeight: 1.05 }}
                    >
                      {t(domain.title, domain.titleMn)}
                    </h2>
                    <p className="mono text-[10px] uppercase mt-1.5" style={{ color: "var(--fg-3)", letterSpacing: "0.06em" }}>
                      {t(domain.titleMn, domain.title)}
                    </p>
                  </div>
                  {w && (
                    <div className="serif tabular flex items-baseline gap-1 shrink-0" style={{ color: "var(--fg-3)" }}>
                      <span style={{ fontSize: 40, color: "var(--accent)", letterSpacing: "-0.03em" }}>
                        {Math.round(w.sharePct)}
                      </span>
                      <span className="mono text-[10px]" style={{ letterSpacing: "0.06em" }}>
                        % {t("of exam", "шалгалтын")}
                      </span>
                    </div>
                  )}
                </div>
                {copy && (
                  <p className="text-[14px] leading-relaxed max-w-2xl mb-5" style={{ color: "var(--fg-2)" }}>
                    {t(copy.en, copy.mn)}
                  </p>
                )}

                {/* Subtopic courses */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {courses.map((course, i) => {
                    const live = liveUnitCount(course.topic);
                    const total = totalUnitCount(course.topic);
                    const pct = topicPct.get(course.topic);
                    return (
                      <Link
                        key={course.topic}
                        id={course.topic}
                        href={`/practice/esh/learn/${course.topic}`}
                        className="card-edit p-5 flex flex-col group"
                      >
                        <div className="flex items-start justify-between mb-2">
                          <div className="mono text-[10px]" style={{ color: "var(--fg-3)", letterSpacing: "0.08em" }}>
                            {di + 1}.{i + 1} · {t("Subtopic", "Дэд сэдэв")}
                          </div>
                          <ArrowRight className="w-4 h-4" style={{ color: "var(--fg-3)" }} />
                        </div>
                        <h3 className="serif" style={{ fontWeight: 400, fontSize: 21, letterSpacing: "-0.02em", color: "var(--fg)" }}>
                          {course.title}
                        </h3>
                        <p className="mono text-[10px] uppercase mt-1" style={{ color: "var(--fg-3)", letterSpacing: "0.06em" }}>
                          {course.titleMn}
                        </p>
                        <p className="text-[13px] mt-2 line-clamp-2" style={{ color: "var(--fg-2)" }}>
                          {course.intro}
                        </p>
                        <div className="flex items-center gap-4 mt-auto pt-4">
                          <div className="flex items-baseline gap-1">
                            <span
                              className="serif tabular"
                              style={{ fontSize: 17, color: live > 0 ? "var(--accent)" : "var(--fg-3)", letterSpacing: "-0.02em" }}
                            >
                              {live}/{total}
                            </span>
                            <span className="mono text-[10px] uppercase" style={{ color: "var(--fg-3)", letterSpacing: "0.06em" }}>
                              {t("units ready", "нэгж бэлэн")}
                            </span>
                          </div>
                          {pct !== undefined && pct > 0 && (
                            <div className="flex items-baseline gap-1">
                              <span className="serif tabular" style={{ fontSize: 17, color: "var(--fg-1)", letterSpacing: "-0.02em" }}>
                                {pct}%
                              </span>
                              <span className="mono text-[10px] uppercase" style={{ color: "var(--fg-3)", letterSpacing: "0.06em" }}>
                                {t("of exam", "шалгалтын")}
                              </span>
                            </div>
                          )}
                        </div>
                      </Link>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </div>
      </section>

      {/* CTA */}
      <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pb-16">
        <div className="card-edit p-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div>
            <h3 className="serif" style={{ fontWeight: 400, fontSize: 22, letterSpacing: "-0.02em", color: "var(--fg)" }}>
              {t("Not sure where to start?", "Хаанаас эхлэхээ мэдэхгүй байна уу?")}
            </h3>
            <p className="text-[13px] mt-1" style={{ color: "var(--fg-2)" }}>
              {t(
                "Sit a past paper first — your results name the exact subtopics to fix.",
                "Эхлээд өмнөх жилийн тест бодоорой — үр дүн чинь засах ёстой дэд сэдвүүдийг нэрлэж өгнө.",
              )}
            </p>
          </div>
          <Link href="/practice/esh/test" className="btn btn-primary shrink-0">
            {t("Take a past paper", "Тест бодох")}
          </Link>
        </div>
      </section>
    </div>
  );
}
