// GENERATED by scripts/gen-logo-assets.py — do not edit by hand.
// Traced from assets/brand/lockup-master.png; re-run the script after a new
// export from the designer.
//
// Inline, not <img src>: `fill="currentColor"` only resolves against the
// `color` of an ancestor in the SAME document, and an <img>-loaded SVG is
// its own document. Inlined, one asset serves light and dark and tracks
// --accent-h if the palette hue ever moves.

export default function LogoMark({
  className,
  color = "var(--accent)",
  title = "Mongol Potential",
}: {
  className?: string;
  color?: string;
  title?: string;
}) {
  return (
    <svg
      viewBox="0 0 631.000000 631.000000"
      role="img"
      aria-label={title}
      className={className}
      style={{ color }}
      preserveAspectRatio="xMidYMid meet"
    >
      <g transform="translate(0.000000,631.000000) scale(0.100000,-0.100000)" fill="currentColor" stroke="none">
        <path d="M3110 5813 c-263 -28 -556 -118 -798 -244 -161 -84 -244 -139 -410
-272 -330 -266 -536 -538 -672 -887 -250 -642 -124 -1381 315 -1847 l86 -92
-30 -98 c-63 -204 -87 -406 -102 -868 -15 -458 -9 -776 14 -829 78 -178 293
-244 446 -138 73 50 116 114 130 195 7 39 11 209 11 438 0 716 31 963 152
1207 39 81 51 117 55 165 9 112 -48 216 -156 290 -87 58 -165 132 -224 212
-147 198 -218 417 -218 675 0 488 240 891 730 1224 169 115 415 214 631 252
130 24 393 24 517 1 462 -85 796 -356 927 -751 51 -154 71 -292 70 -491 -1
-162 -4 -190 -27 -279 -104 -390 -405 -659 -815 -731 -126 -22 -175 -41 -231
-91 -61 -55 -93 -126 -95 -209 -1 -34 13 -126 31 -210 73 -345 93 -576 102
-1210 7 -404 11 -498 24 -538 59 -182 300 -259 455 -147 54 39 99 101 117 163
27 91 14 912 -20 1272 -15 163 -42 377 -51 406 -3 12 21 25 106 59 664 259
1066 916 1010 1652 -18 240 -77 503 -150 678 -124 292 -343 553 -621 738 -230
154 -543 264 -859 302 -79 9 -372 11 -450 3z M3570 4843 c-50 -19 -104 -69
-126 -117 -68 -147 20 -309 177 -323 77 -7 135 15 187 71 105 114 68 293 -73
357 -39 18 -132 24 -165 12z M2549 4613 c-165 -84 -169 -316 -7 -397 158 -79
327 23 328 197 0 67 -16 109 -59 155 -69 74 -169 91 -262 45z" />
      </g>
    </svg>
  );
}
