"""AA HL Practice Paper 1 (ib-hl-practice-1) — 120 min, 110 marks, NO calculator.

Blueprint (topic x marks):
    Section A (51): Q1 number_algebra 5 | Q2 stats_probability 6
                    Q3 functions 9      | Q4 number_algebra 6
                    Q5 geometry_trig 8  | Q6 calculus 8
                    Q7 stats_probability 9
    Section B (59): Q8 geometry_trig 21 | Q9 calculus 20
                    Q10 number_algebra 18
    Paper totals: number_algebra 29 | functions 9 | geometry_trig 29 |
                  stats_probability 15 | calculus 28 = 110.
    (HL shares NA 19/F 15/GT 24/SP 16/C 26 — each within the ±8-pt
    per-paper band; paper 2 rebalances F and SP toward the pair target.)

HL-only content on this paper: complex numbers with De Moivre (Q4),
proof by induction AND by contradiction (Q10), vector product / planes /
foot of perpendicular in 3D (Q8), integration by parts + Maclaurin
series (Q9). Everything exact — fractions, surds, multiples of pi, e.
Figure: Q9 (curve x e^{-x} with shaded region), generated by
scripts/test-figures/ib-aa-hl-practice-1.py from the SAME parameters.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ibbuild import ROOT, A1, AG, M1, R1, part, question, write_paper  # noqa: E402

from sympy import (Rational, sqrt, pi, Eq, I, Matrix, simplify, solve,  # noqa: F401,E402
                   expand, factor, diff, integrate, exp, sin, cos, tan,
                   binomial, factorial, symbols, im, re, arg, Abs, series)

x, y, k = symbols("x y k")


def png(name, alt_en):
    from PIL import Image
    p = os.path.join(ROOT, "public", "ib-figures", name)
    assert os.path.isfile(p), f"figure missing on disk: {p} — run the figure script first"
    with Image.open(p) as im_:
        w, h = im_.size
    return {"src": f"/ib-figures/{name}", "width": w, "height": h, "alt_en": alt_en}


QS = []

# ── Q1 [5] number_algebra: binomial theorem, constant term ───────────────
# (x^2 - 2/x)^6: term_k = C(6,k) (x^2)^(6-k) (-2/x)^k = C(6,k)(-2)^k x^(12-3k)
assert expand((x**2 - 2/x)**6).coeff(x, 0) == 240
assert binomial(6, 4) * (-2)**4 == 240
QS.append(question(
    "IB-AAHL-P1-T1-Q1", 1, "A", "number_algebra", "binomial_theorem",
    contextIntro=("Consider the expansion of $\\left(x^2 - "
                  "\\dfrac{2}{x}\\right)^{6}$."),
    parts=[
        part("a", "Write down an expression for the general term in the "
             "expansion.", 2,
             [M1("apply the binomial theorem to the two bracket terms"),
              A1("$\\binom{6}{k}(x^2)^{6-k}\\left(-\\dfrac{2}{x}\\right)^{k} "
                 "= \\binom{6}{k}(-2)^k x^{12-3k}$")],
             answer="$\\binom{6}{k}(-2)^k x^{12-3k}$",
             solution=("$$T_k = \\binom{6}{k}(x^2)^{6-k}"
                       "\\left(-\\frac{2}{x}\\right)^{k} "
                       "= \\binom{6}{k}(-2)^k x^{12-3k}$$"),
             verify=["Eq(binomial(6, 1)*(-2)**1, -12)",
                     "Eq(12 - 3*1, 9)"]),
        part("b", "Hence find the term independent of $x$.", 3,
             [M1("set the index to zero: $12 - 3k = 0$"),
              A1("$k = 4$"),
              A1("$\\binom{6}{4}(-2)^4 = 15 \\times 16 = 240$")],
             answer="$240$",
             solution=("The term independent of $x$ needs $12 - 3k = 0$, so "
                       "$k = 4$:"
                       "$$\\binom{6}{4}(-2)^4 = 15 \\cdot 16 = 240.$$"),
             verify=["Eq(solve(Eq(12 - 3*x, 0), x)[0], 4)",
                     "Eq(binomial(6, 4)*(-2)**4, 240)",
                     "Eq(expand((x**2 - 2/x)**6).coeff(x, 0), 240)"]),
    ]))

# ── Q2 [6] stats_probability: total probability + Bayes, exact ───────────
# Box A: 3 red 2 green; Box B: 1 red 4 green; fair coin picks the box.
pRed = Rational(1, 2) * Rational(3, 5) + Rational(1, 2) * Rational(1, 5)
assert pRed == Rational(2, 5)
pA_given_red = (Rational(1, 2) * Rational(3, 5)) / pRed
assert pA_given_red == Rational(3, 4)
QS.append(question(
    "IB-AAHL-P1-T1-Q2", 2, "A", "stats_probability", "conditional_probability",
    contextIntro=("Box A contains 3 red and 2 green counters; box B contains "
                  "1 red and 4 green counters. A fair coin is tossed: heads "
                  "means a counter is taken at random from box A, tails from "
                  "box B."),
    parts=[
        part("a", "Find the probability that the counter taken is red.", 3,
             [M1("use the total probability over the two boxes"),
              A1("$\\tfrac{1}{2}\\cdot\\tfrac{3}{5} + "
                 "\\tfrac{1}{2}\\cdot\\tfrac{1}{5}$"),
              A1("$P(R) = \\dfrac{2}{5}$")],
             answer="$\\dfrac{2}{5}$",
             solution=("$$P(R) = \\frac{1}{2}\\cdot\\frac{3}{5} + "
                       "\\frac{1}{2}\\cdot\\frac{1}{5} = \\frac{3}{10} + "
                       "\\frac{1}{10} = \\frac{2}{5}$$"),
             verify=["Eq(Rational(1,2)*Rational(3,5) + "
                     "Rational(1,2)*Rational(1,5), Rational(2,5))"]),
        part("b", "Given that the counter is red, find the probability that "
             "it came from box A.", 3,
             [M1("use $P(A \\mid R) = \\dfrac{P(A \\cap R)}{P(R)}$"),
              A1("$\\dfrac{3/10}{2/5}$"),
              A1("$P(A \\mid R) = \\dfrac{3}{4}$")],
             answer="$\\dfrac{3}{4}$",
             solution=("$$P(A \\mid R) = \\frac{\\tfrac{1}{2}\\cdot"
                       "\\tfrac{3}{5}}{\\tfrac{2}{5}} = "
                       "\\frac{3/10}{2/5} = \\frac{3}{4}$$"),
             verify=["Eq((Rational(1,2)*Rational(3,5))/Rational(2,5), "
                     "Rational(3,4))"]),
    ]))

# ── Q3 [9] functions: factor + remainder theorems, then root count ───────
a3, b3 = -3, 1
p3 = 2*x**3 + a3*x**2 + b3*x - 6
assert p3.subs(x, 2) == 0                       # (x - 2) is a factor
assert p3.subs(x, -1) == -12                    # remainder -12 at x = -1
assert expand((x - 2)*(2*x**2 + x + 3)) == expand(p3)
assert 1**2 - 4*2*3 == -23                      # discriminant of 2x^2+x+3
QS.append(question(
    "IB-AAHL-P1-T1-Q3", 3, "A", "functions", "polynomial_theorems",
    contextIntro=("The polynomial $p(x) = 2x^3 + ax^2 + bx - 6$ has "
                  "$(x - 2)$ as a factor. When $p(x)$ is divided by "
                  "$(x + 1)$ the remainder is $-12$."),
    parts=[
        part("a", "Find the value of $a$ and the value of $b$.", 5,
             [M1("factor theorem: $p(2) = 0$"),
              A1("$4a + 2b = -10$"),
              M1("remainder theorem: $p(-1) = -12$"),
              A1("$a - b = -4$"),
              A1("$a = -3, \\; b = 1$")],
             answer="$a = -3$, $b = 1$",
             solution=("$p(2) = 0$: $16 + 4a + 2b - 6 = 0 \\Rightarrow "
                       "2a + b = -5$."
                       "$$p(-1) = -2 + a - b - 6 = -12 \\Rightarrow "
                       "a - b = -4$$"
                       "Adding the equations: $3a = -9$, so $a = -3$ and "
                       "$b = 1$."),
             verify=["Eq((2*x**3 - 3*x**2 + x - 6).subs(x, 2), 0)",
                     "Eq((2*x**3 - 3*x**2 + x - 6).subs(x, -1), -12)",
                     "Eq(2*(-3) + 1, -5)", "Eq(-3 - 1, -4)"]),
        part("b", "Express $p(x)$ as a product of $(x - 2)$ and a quadratic "
             "factor.", 2,
             [M1("divide (or compare coefficients)"),
              A1("$p(x) = (x - 2)(2x^2 + x + 3)$")],
             answer="$p(x) = (x - 2)(2x^2 + x + 3)$",
             solution=("Dividing $2x^3 - 3x^2 + x - 6$ by $(x - 2)$:"
                       "$$p(x) = (x - 2)(2x^2 + x + 3).$$"),
             verify=["Eq(expand((x - 2)*(2*x**2 + x + 3)), "
                     "2*x**3 - 3*x**2 + x - 6)"]),
        part("c", "Hence show that the equation $p(x) = 0$ has exactly one "
             "real root.", 2,
             [M1("discriminant of the quadratic factor: $1 - 24 = -23 < 0$"),
              AG("only $x = 2$ is real")],
             answer="only real root: $x = 2$",
             solution=("The quadratic factor has discriminant "
                       "$$\\Delta = 1^2 - 4(2)(3) = -23 < 0,$$ so it has no "
                       "real zeros, and the only real root of $p(x) = 0$ is "
                       "$x = 2$."),
             verify=["Eq(1 - 4*2*3, -23)", "-23 < 0"]),
    ]))

# ── Q4 [6] number_algebra: complex numbers, De Moivre ────────────────────
z4 = 1 + sqrt(3)*I
assert Abs(z4) == 2
assert arg(z4) == pi/3
assert simplify(z4**6) == 64
QS.append(question(
    "IB-AAHL-P1-T1-Q4", 4, "A", "number_algebra", "complex_numbers",
    contextIntro=("Let $z = 1 + \\sqrt{3}\\,i$."),
    parts=[
        part("a", "Find $|z|$ and $\\arg z$.", 3,
             [A1("$|z| = \\sqrt{1 + 3} = 2$"),
              M1("$\\tan(\\arg z) = \\sqrt{3}$ with $z$ in the first "
                 "quadrant"),
              A1("$\\arg z = \\dfrac{\\pi}{3}$")],
             answer="$|z| = 2$, $\\arg z = \\dfrac{\\pi}{3}$",
             solution=("$$|z| = \\sqrt{1^2 + (\\sqrt{3})^2} = 2, \\qquad "
                       "\\arg z = \\arctan\\sqrt{3} = \\frac{\\pi}{3}.$$"),
             verify=["Eq(Abs(1 + sqrt(3)*I), 2)",
                     "Eq(arg(1 + sqrt(3)*I), pi/3)"]),
        part("b", "Use de Moivre's theorem to find the value of $z^6$.", 3,
             [M1("$z^6 = 2^6\\big(\\cos 2\\pi + i\\sin 2\\pi\\big)$"),
              A1("$\\cos 2\\pi = 1$, $\\sin 2\\pi = 0$"),
              A1("$z^6 = 64$")],
             answer="$z^6 = 64$",
             solution=("$z = 2\\operatorname{cis}\\dfrac{\\pi}{3}$, so by "
                       "de Moivre"
                       "$$z^6 = 2^6\\operatorname{cis}(2\\pi) = 64(1 + 0i) "
                       "= 64.$$"),
             verify=["Eq(simplify((1 + sqrt(3)*I)**6), 64)",
                     "Eq(2**6, 64)", "Eq(6*pi/3, 2*pi)"]),
    ]))

# ── Q5 [8] geometry_trig: compound angles, exact values ──────────────────
t75 = (1 + 1/sqrt(3)) / (1 - 1/sqrt(3))
assert simplify(t75 - (2 + sqrt(3))) == 0
assert simplify(tan(pi/12) - (2 - sqrt(3))) == 0
assert simplify((2 + sqrt(3))*(2 - sqrt(3))) == 1
QS.append(question(
    "IB-AAHL-P1-T1-Q5", 5, "A", "geometry_trig", "compound_angles",
    parts=[
        part("a", "Using the identity for $\\tan(A + B)$, show that "
             "$\\tan 75^{\\circ} = 2 + \\sqrt{3}$.", 4,
             [M1("write $75^{\\circ} = 45^{\\circ} + 30^{\\circ}$ and apply "
                 "$\\tan(A+B) = \\dfrac{\\tan A + \\tan B}{1 - \\tan A"
                 "\\tan B}$"),
              A1("$\\dfrac{1 + \\tfrac{1}{\\sqrt{3}}}{1 - "
                 "\\tfrac{1}{\\sqrt{3}}} = \\dfrac{\\sqrt{3} + 1}"
                 "{\\sqrt{3} - 1}$"),
              M1("rationalise the denominator"),
              AG("$\\dfrac{(\\sqrt{3}+1)^2}{2} = \\dfrac{4 + 2\\sqrt{3}}{2} "
                 "= 2 + \\sqrt{3}$")],
             answer="$\\tan 75^{\\circ} = 2 + \\sqrt{3}$",
             solution=("$$\\tan 75^{\\circ} = \\frac{\\tan 45^{\\circ} + "
                       "\\tan 30^{\\circ}}{1 - \\tan 45^{\\circ}\\tan "
                       "30^{\\circ}} = \\frac{1 + \\tfrac{1}{\\sqrt3}}"
                       "{1 - \\tfrac{1}{\\sqrt3}} = \\frac{\\sqrt3 + 1}"
                       "{\\sqrt3 - 1}$$"
                       "Multiplying top and bottom by $(\\sqrt3 + 1)$:"
                       "$$\\frac{(\\sqrt3 + 1)^2}{3 - 1} = "
                       "\\frac{4 + 2\\sqrt3}{2} = 2 + \\sqrt{3}.$$"),
             verify=["Eq(simplify((1 + 1/sqrt(3))/(1 - 1/sqrt(3)) "
                     "- (2 + sqrt(3))), 0)",
                     "Eq(simplify(tan(5*pi/12) - (2 + sqrt(3))), 0)"]),
        part("b", "Hence find the exact value of $\\tan 15^{\\circ}$.", 2,
             [M1("$\\tan 15^{\\circ} = \\dfrac{1}{\\tan 75^{\\circ}}$ "
                 "(complementary angles)"),
              A1("$\\dfrac{1}{2 + \\sqrt{3}} = 2 - \\sqrt{3}$")],
             answer="$\\tan 15^{\\circ} = 2 - \\sqrt{3}$",
             solution=("Since $15^{\\circ}$ and $75^{\\circ}$ are "
                       "complementary, $\\tan 15^{\\circ} = "
                       "\\cot 75^{\\circ}$:"
                       "$$\\tan 15^{\\circ} = \\frac{1}{2 + \\sqrt3} = "
                       "\\frac{2 - \\sqrt3}{(2+\\sqrt3)(2-\\sqrt3)} "
                       "= 2 - \\sqrt{3}.$$"),
             verify=["Eq(simplify(tan(pi/12) - (2 - sqrt(3))), 0)",
                     "Eq(simplify(1/(2 + sqrt(3)) - (2 - sqrt(3))), 0)"]),
        part("c", "Write down the exact value of "
             "$\\tan 75^{\\circ} \\times \\tan 15^{\\circ}$.", 2,
             [M1("$(2 + \\sqrt{3})(2 - \\sqrt{3}) = 4 - 3$"),
              A1("$1$")],
             answer="$1$",
             solution=("$$(2 + \\sqrt3)(2 - \\sqrt3) = 4 - 3 = 1,$$ as "
                       "expected for the tangents of complementary angles."),
             verify=["Eq(expand((2 + sqrt(3))*(2 - sqrt(3))), 1)"]),
    ]))

# ── Q6 [8] calculus: implicit differentiation + tangent ──────────────────
# x^2 + xy + y^2 = 7 at P(1, 2); y' = -(2x + y)/(x + 2y) = -4/5 there.
assert 1 + 1*2 + 4 == 7
dydx6 = -(2*x + y)/(x + 2*y)
assert dydx6.subs({x: 1, y: 2}) == Rational(-4, 5)
assert Rational(-4, 5)*1 + Rational(14, 5) == 2          # tangent through P
assert solve(Eq(Rational(-4, 5)*x + Rational(14, 5), 0), x)[0] == Rational(7, 2)
QS.append(question(
    "IB-AAHL-P1-T1-Q6", 6, "A", "calculus", "implicit_differentiation",
    contextIntro=("A curve is defined implicitly by $x^2 + xy + y^2 = 7$. "
                  "The point $P(1, 2)$ lies on the curve."),
    parts=[
        part("a", "Show that $\\dfrac{dy}{dx} = -\\dfrac{2x + y}{x + 2y}$.", 4,
             [M1("differentiate both sides with respect to $x$"),
              A1("product rule on $xy$: $y + x\\dfrac{dy}{dx}$"),
              M1("collect the $\\dfrac{dy}{dx}$ terms"),
              AG("$\\dfrac{dy}{dx}(x + 2y) = -(2x + y)$")],
             answer="$\\dfrac{dy}{dx} = -\\dfrac{2x + y}{x + 2y}$",
             solution=("Differentiating term by term:"
                       "$$2x + \\Big(y + x\\frac{dy}{dx}\\Big) + "
                       "2y\\frac{dy}{dx} = 0$$"
                       "$$\\frac{dy}{dx}(x + 2y) = -(2x + y) \\Rightarrow "
                       "\\frac{dy}{dx} = -\\frac{2x + y}{x + 2y}.$$"),
             verify=["Eq(simplify(diff(7 - x**2 - x*y - y**2, x) "
                     "- (-2*x - y)), 0)",
                     "Eq((-(2*x + y)/(x + 2*y)).subs({x: 1, y: 2}), "
                     "Rational(-4, 5))"]),
        part("b", "Find the equation of the tangent to the curve at $P$, "
             "giving your answer in the form $y = mx + c$.", 2,
             [A1("gradient at $P$ is $-\\dfrac{4}{5}$"),
              A1("$y = -\\dfrac{4}{5}x + \\dfrac{14}{5}$")],
             answer="$y = -\\dfrac{4}{5}x + \\dfrac{14}{5}$",
             solution=("At $P(1,2)$ the gradient is $-\\dfrac{2 + 2}"
                       "{1 + 4} = -\\dfrac{4}{5}$, so"
                       "$$y - 2 = -\\frac{4}{5}(x - 1) \\Rightarrow "
                       "y = -\\frac{4}{5}x + \\frac{14}{5}.$$"),
             verify=["Eq(Rational(-4, 5)*1 + Rational(14, 5), 2)"]),
        part("c", "Find the coordinates of the point where this tangent "
             "crosses the $x$-axis.", 2,
             [M1("set $y = 0$"),
              A1("$x = \\dfrac{7}{2}$, i.e. $\\left(\\dfrac{7}{2}, "
                 "0\\right)$")],
             answer="$\\left(\\dfrac{7}{2}, 0\\right)$",
             solution=("$$0 = -\\frac{4}{5}x + \\frac{14}{5} \\Rightarrow "
                       "4x = 14 \\Rightarrow x = \\frac{7}{2}.$$"),
             verify=["Eq(solve(Eq(Rational(-4,5)*x + Rational(14,5), 0), "
                     "x)[0], Rational(7, 2))"]),
    ]))

# ── Q7 [9] stats_probability: discrete random variable ───────────────────
# P(X = x) = kx on {1,2,3,4}: k = 1/10, E = 3, Var = 1, P(X>=3 | X>=2) = 7/9
k7 = Rational(1, 10)
assert sum(k7*i for i in (1, 2, 3, 4)) == 1
E7 = sum(i*k7*i for i in (1, 2, 3, 4))
assert E7 == 3
EX2 = sum(i**2*k7*i for i in (1, 2, 3, 4))
assert EX2 == 10 and EX2 - E7**2 == 1
assert (k7*3 + k7*4) / (k7*2 + k7*3 + k7*4) == Rational(7, 9)
QS.append(question(
    "IB-AAHL-P1-T1-Q7", 7, "A", "stats_probability", "discrete_random_variables",
    contextIntro=("A discrete random variable $X$ has probability function "
                  "$P(X = x) = kx$ for $x = 1, 2, 3, 4$, where $k$ is a "
                  "constant."),
    parts=[
        part("a", "Show that $k = \\dfrac{1}{10}$.", 2,
             [M1("probabilities sum to 1: $k(1 + 2 + 3 + 4) = 1$"),
              AG("$10k = 1 \\Rightarrow k = \\tfrac{1}{10}$")],
             answer="$k = \\dfrac{1}{10}$",
             solution=("$$\\sum P(X = x) = k(1 + 2 + 3 + 4) = 10k = 1 "
                       "\\Rightarrow k = \\frac{1}{10}.$$"),
             verify=["Eq(Rational(1,10)*(1 + 2 + 3 + 4), 1)"]),
        part("b", "Find $E(X)$.", 3,
             [M1("$E(X) = \\sum x\\,P(X = x)$"),
              A1("$\\tfrac{1}{10}(1 + 4 + 9 + 16)$"),
              A1("$E(X) = 3$")],
             answer="$E(X) = 3$",
             solution=("$$E(X) = \\frac{1}{10}(1^2 + 2^2 + 3^2 + 4^2) "
                       "= \\frac{30}{10} = 3.$$"),
             verify=["Eq(Rational(1,10)*(1 + 4 + 9 + 16), 3)"]),
        part("c", "Find $\\operatorname{Var}(X)$.", 2,
             [M1("$E(X^2) = \\tfrac{1}{10}(1 + 8 + 27 + 64) = 10$"),
              A1("$\\operatorname{Var}(X) = 10 - 3^2 = 1$")],
             answer="$\\operatorname{Var}(X) = 1$",
             solution=("$$E(X^2) = \\frac{1}{10}(1 + 8 + 27 + 64) = 10, "
                       "\\qquad \\operatorname{Var}(X) = 10 - 9 = 1.$$"),
             verify=["Eq(Rational(1,10)*(1 + 8 + 27 + 64), 10)",
                     "Eq(10 - 3**2, 1)"]),
        part("d", "Find $P(X \\ge 3 \\mid X \\ge 2)$.", 2,
             [M1("$\\dfrac{P(X \\ge 3)}{P(X \\ge 2)} = "
                 "\\dfrac{7/10}{9/10}$"),
              A1("$\\dfrac{7}{9}$")],
             answer="$\\dfrac{7}{9}$",
             solution=("$$P(X \\ge 3) = \\frac{7}{10}, \\quad "
                       "P(X \\ge 2) = \\frac{9}{10} \\Rightarrow "
                       "P(X \\ge 3 \\mid X \\ge 2) = \\frac{7}{9}.$$"),
             verify=["Eq(Rational(7,10)/Rational(9,10), Rational(7,9))"]),
    ]))

# ── Q8 [21] geometry_trig (Section B): vector product, plane, foot ───────
A8 = Matrix([1, 1, 1])
B8 = Matrix([2, 1, -1])
C8 = Matrix([1, 2, 3])
AB8 = B8 - A8            # (1, 0, -2)
AC8 = C8 - A8            # (0, 1, 2)
n8 = AB8.cross(AC8)      # (2, -2, 1)
assert list(n8) == [2, -2, 1]
assert n8.norm() == 3
assert n8.dot(A8) == 1 and n8.dot(B8) == 1 and n8.dot(C8) == 1
D8 = Matrix([4, 0, 2])
assert n8.dot(D8) == 10
tF = Rational(1 - 10, 9)             # t = -1
assert tF == -1
F8 = D8 + tF*n8
assert list(F8) == [2, 2, 1]
assert n8.dot(F8) == 1
assert (F8 - D8).norm() == 3
BD8 = D8 - B8            # (2, -1, 3)
assert BD8.dot(n8) == 9
assert BD8.norm() == sqrt(14)
sin_th = Rational(9, 1) / (3*sqrt(14))
assert simplify(sin_th - 3/sqrt(14)) == 0
QS.append(question(
    "IB-AAHL-P1-T1-Q8", 8, "B", "geometry_trig", "vectors_planes",
    contextIntro=("The points $A(1, 1, 1)$, $B(2, 1, -1)$, $C(1, 2, 3)$ and "
                  "$D(4, 0, 2)$ are given. The plane $\\Pi$ contains the "
                  "points $A$, $B$ and $C$."),
    parts=[
        part("a", "Find the vectors $\\vec{AB}$ and $\\vec{AC}$.", 2,
             [A1("$\\vec{AB} = \\begin{pmatrix}1\\\\0\\\\-2\\end{pmatrix}$"),
              A1("$\\vec{AC} = \\begin{pmatrix}0\\\\1\\\\2\\end{pmatrix}$")],
             answer=("$\\vec{AB} = (1, 0, -2)$, $\\vec{AC} = (0, 1, 2)$"),
             solution=("$$\\vec{AB} = B - A = (1, 0, -2), \\qquad "
                       "\\vec{AC} = C - A = (0, 1, 2).$$"),
             verify=["Eq(2 - 1, 1)", "Eq(-1 - 1, -2)", "Eq(3 - 1, 2)"]),
        part("b", "Show that $\\vec{AB} \\times \\vec{AC} = "
             "\\begin{pmatrix}2\\\\-2\\\\1\\end{pmatrix}$.", 3,
             [M1("apply the vector-product determinant"),
              A1("components $(0\\cdot 2 - (-2)\\cdot 1,\\; "
                 "(-2)\\cdot 0 - 1\\cdot 2,\\; 1\\cdot 1 - 0\\cdot 0)$"),
              AG("$= (2, -2, 1)$")],
             answer="$(2, -2, 1)$",
             solution=("$$\\vec{AB} \\times \\vec{AC} = "
                       "\\begin{vmatrix}\\mathbf{i} & \\mathbf{j} & "
                       "\\mathbf{k}\\\\ 1 & 0 & -2\\\\ 0 & 1 & 2"
                       "\\end{vmatrix} = (0 + 2,\\; -(2 - 0),\\; 1 - 0) "
                       "= (2, -2, 1).$$"),
             verify=["Eq(0*2 - (-2)*1, 2)", "Eq(-(1*2 - (-2)*0), -2)",
                     "Eq(1*1 - 0*0, 1)"]),
        part("c", "Hence find the area of triangle $ABC$.", 2,
             [M1("area $= \\tfrac{1}{2}\\left|\\vec{AB} \\times "
                 "\\vec{AC}\\right|$ with $|(2,-2,1)| = 3$"),
              A1("area $= \\dfrac{3}{2}$")],
             answer="$\\dfrac{3}{2}$",
             solution=("$$\\left|\\vec{AB}\\times\\vec{AC}\\right| = "
                       "\\sqrt{4 + 4 + 1} = 3 \\Rightarrow \\text{area} = "
                       "\\frac{3}{2}.$$"),
             verify=["Eq(sqrt(4 + 4 + 1), 3)",
                     "Eq(Rational(1,2)*3, Rational(3,2))"]),
        part("d", "Find a Cartesian equation of the plane $\\Pi$.", 3,
             [M1("use $\\mathbf{r}\\cdot\\mathbf{n} = "
                 "\\mathbf{a}\\cdot\\mathbf{n}$ with $\\mathbf{n} = "
                 "(2, -2, 1)$"),
              A1("$\\mathbf{a}\\cdot\\mathbf{n} = 2 - 2 + 1 = 1$"),
              A1("$2x - 2y + z = 1$")],
             answer="$2x - 2y + z = 1$",
             solution=("With normal $(2, -2, 1)$ and point $A(1,1,1)$:"
                       "$$2x - 2y + z = 2(1) - 2(1) + 1 = 1.$$"),
             verify=["Eq(2*1 - 2*1 + 1, 1)", "Eq(2*2 - 2*1 + (-1), 1)",
                     "Eq(2*1 - 2*2 + 3, 1)"]),
        part("e", "Write down a vector equation of the line $L$ through $D$ "
             "perpendicular to $\\Pi$.", 2,
             [A1("direction is the normal $(2, -2, 1)$"),
              A1("$\\mathbf{r} = \\begin{pmatrix}4\\\\0\\\\2\\end{pmatrix} "
                 "+ t\\begin{pmatrix}2\\\\-2\\\\1\\end{pmatrix}$")],
             answer=("$\\mathbf{r} = (4, 0, 2) + t(2, -2, 1)$"),
             solution=("A line perpendicular to a plane is parallel to the "
                       "plane's normal:"
                       "$$\\mathbf{r} = \\begin{pmatrix}4\\\\0\\\\2"
                       "\\end{pmatrix} + t\\begin{pmatrix}2\\\\-2\\\\1"
                       "\\end{pmatrix}.$$"),
             verify=["Eq(2*4 - 2*0 + 2, 10)"]),
        part("f", "Find the coordinates of $F$, the foot of the "
             "perpendicular from $D$ to $\\Pi$.", 4,
             [M1("substitute $(4 + 2t,\\; -2t,\\; 2 + t)$ into the plane"),
              A1("$10 + 9t = 1$"),
              A1("$t = -1$"),
              A1("$F(2, 2, 1)$")],
             answer="$F(2, 2, 1)$",
             solution=("$$2(4 + 2t) - 2(-2t) + (2 + t) = 1 \\Rightarrow "
                       "10 + 9t = 1 \\Rightarrow t = -1$$"
                       "$$F = (4 - 2,\\; 0 + 2,\\; 2 - 1) = (2, 2, 1).$$"),
             verify=["Eq(solve(Eq(10 + 9*x, 1), x)[0], -1)",
                     "Eq(2*2 - 2*2 + 1, 1)"]),
        part("g", "Hence find the exact distance from $D$ to the plane "
             "$\\Pi$.", 2,
             [M1("distance $= |\\vec{DF}|$ with $\\vec{DF} = (-2, 2, -1)$"),
              A1("distance $= 3$")],
             answer="$3$",
             solution=("$$\\vec{DF} = F - D = (-2, 2, -1), \\qquad "
                       "|\\vec{DF}| = \\sqrt{4 + 4 + 1} = 3.$$"),
             verify=["Eq(sqrt((-2)**2 + 2**2 + (-1)**2), 3)"]),
        part("h", "Find the exact value of $\\sin\\theta$, where $\\theta$ "
             "is the acute angle between the line $(BD)$ and the plane "
             "$\\Pi$.", 3,
             [M1("$\\sin\\theta = \\dfrac{|\\vec{BD}\\cdot\\mathbf{n}|}"
                 "{|\\vec{BD}||\\mathbf{n}|}$ with $\\vec{BD} = (2,-1,3)$"),
              A1("$\\vec{BD}\\cdot\\mathbf{n} = 9$, $|\\vec{BD}| = "
                 "\\sqrt{14}$"),
              A1("$\\sin\\theta = \\dfrac{9}{3\\sqrt{14}} = "
                 "\\dfrac{3\\sqrt{14}}{14}$")],
             answer="$\\sin\\theta = \\dfrac{3\\sqrt{14}}{14}$",
             solution=("$$\\vec{BD} = D - B = (2, -1, 3), \\qquad "
                       "\\vec{BD}\\cdot\\mathbf{n} = 4 + 2 + 3 = 9$$"
                       "$$\\sin\\theta = \\frac{9}{\\sqrt{14}\\cdot 3} = "
                       "\\frac{3}{\\sqrt{14}} = \\frac{3\\sqrt{14}}{14}.$$"),
             verify=["Eq(2*2 + (-1)*(-2) + 3*1, 9)",
                     "Eq(sqrt(2**2 + 1 + 3**2), sqrt(14))",
                     "Eq(simplify(9/(3*sqrt(14)) - 3*sqrt(14)/14), 0)"]),
    ]))

# ── Q9 [20] calculus (Section B): x e^{-x} — parts, inflexion, Maclaurin ─
f9 = x*exp(-x)
assert simplify(diff(f9, x) - (1 - x)*exp(-x)) == 0
assert f9.subs(x, 1) == exp(-1)
assert simplify(diff(f9, x, 2) - (x - 2)*exp(-x)) == 0
assert f9.subs(x, 2) == 2*exp(-2)
anti9 = -(x + 1)*exp(-x)
assert simplify(diff(anti9, x) - f9) == 0
area9 = integrate(f9, (x, 0, 1))
assert simplify(area9 - (1 - 2*exp(-1))) == 0
mac9 = series(f9, x, 0, 4).removeO()
assert expand(mac9 - (x - x**2 + x**3/2)) == 0
QS.append(question(
    "IB-AAHL-P1-T1-Q9", 9, "B", "calculus", "integration_by_parts",
    contextIntro=("Let $f(x) = x e^{-x}$ for $x \\ge 0$. The diagram shows "
                  "the graph of $y = f(x)$; the shaded region $R$ is bounded "
                  "by the curve, the $x$-axis and the line $x = 1$."),
    figure=png("ib-aahl-p1-t1-q9.png",
               "Curve y = x e^(-x) for x from 0 to about 4, rising to a "
               "maximum then decaying; the region under the curve between "
               "x = 0 and x = 1 is shaded."),
    parts=[
        part("a", "Show that $f'(x) = (1 - x)e^{-x}$.", 2,
             [M1("product rule: $e^{-x} + x(-e^{-x})$"),
              AG("$f'(x) = (1 - x)e^{-x}$")],
             answer="$f'(x) = (1 - x)e^{-x}$",
             solution=("$$f'(x) = 1\\cdot e^{-x} + x(-e^{-x}) = "
                       "(1 - x)e^{-x}.$$"),
             verify=["Eq(simplify(diff(x*exp(-x), x) - (1 - x)*exp(-x)), 0)"]),
        part("b", "Hence find the coordinates of the maximum point of the "
             "graph of $f$.", 3,
             [M1("$f'(x) = 0$ with $e^{-x} \\ne 0$ gives $x = 1$"),
              A1("$x = 1$"),
              A1("maximum at $\\left(1, \\dfrac{1}{e}\\right)$")],
             answer="$\\left(1, \\dfrac{1}{e}\\right)$",
             solution=("$e^{-x} > 0$ for all $x$, so $f'(x) = 0$ only at "
                       "$x = 1$; $f'$ changes from positive to negative "
                       "there, and"
                       "$$f(1) = e^{-1} = \\frac{1}{e}.$$"),
             verify=["Eq((x*exp(-x)).subs(x, 1), exp(-1))",
                     "Eq(((1 - x)*exp(-x)).subs(x, 1), 0)"]),
        part("c", "Show that $f''(x) = (x - 2)e^{-x}$.", 3,
             [M1("differentiate $f'(x) = (1 - x)e^{-x}$ by the product "
                 "rule"),
              A1("$-e^{-x} - (1 - x)e^{-x}$"),
              AG("$= (x - 2)e^{-x}$")],
             answer="$f''(x) = (x - 2)e^{-x}$",
             solution=("$$f''(x) = -e^{-x} + (1 - x)(-e^{-x}) = "
                       "e^{-x}(-1 - 1 + x) = (x - 2)e^{-x}.$$"),
             verify=["Eq(simplify(diff(x*exp(-x), x, 2) "
                     "- (x - 2)*exp(-x)), 0)"]),
        part("d", "Find the coordinates of the point of inflexion of the "
             "graph of $f$.", 2,
             [M1("$f''(x) = 0$ gives $x = 2$ (sign change)"),
              A1("inflexion at $\\left(2, \\dfrac{2}{e^2}\\right)$")],
             answer="$\\left(2, \\dfrac{2}{e^2}\\right)$",
             solution=("$f''$ changes sign at $x = 2$, and $f(2) = "
                       "2e^{-2}$, so the point of inflexion is "
                       "$\\left(2, \\dfrac{2}{e^2}\\right)$."),
             verify=["Eq((x*exp(-x)).subs(x, 2), 2*exp(-2))",
                     "Eq(((x - 2)*exp(-x)).subs(x, 2), 0)"]),
        part("e", "Using integration by parts, find "
             "$\\displaystyle\\int x e^{-x}\\,dx$.", 4,
             [M1("parts with $u = x$, $dv = e^{-x}dx$"),
              A1("$-x e^{-x} + \\displaystyle\\int e^{-x}\\,dx$"),
              A1("$-x e^{-x} - e^{-x}$"),
              A1("$-(x + 1)e^{-x} + C$")],
             answer="$-(x + 1)e^{-x} + C$",
             solution=("Take $u = x$ and $dv = e^{-x}dx$, so $du = dx$ and "
                       "$v = -e^{-x}$:"
                       "$$\\int x e^{-x}dx = -x e^{-x} + \\int e^{-x}dx "
                       "= -x e^{-x} - e^{-x} + C = -(x + 1)e^{-x} + C.$$"),
             verify=["Eq(simplify(diff(-(x + 1)*exp(-x), x) - x*exp(-x)), "
                     "0)"]),
        part("f", "Hence show that the area of $R$ is $1 - \\dfrac{2}{e}$.", 3,
             [M1("area $= \\Big[-(x + 1)e^{-x}\\Big]_0^1$"),
              A1("$-2e^{-1} - (-1)$"),
              AG("$= 1 - \\dfrac{2}{e}$")],
             answer="area $= 1 - \\dfrac{2}{e}$",
             solution=("$$\\int_0^1 x e^{-x}dx = "
                       "\\Big[-(x + 1)e^{-x}\\Big]_0^1 = -2e^{-1} + 1 = "
                       "1 - \\frac{2}{e}.$$"),
             verify=["Eq(simplify(integrate(x*exp(-x), (x, 0, 1)) "
                     "- (1 - 2*exp(-1))), 0)"]),
        part("g", "Write down the first three non-zero terms of the "
             "Maclaurin series for $e^{-x}$, and hence find the first three "
             "non-zero terms of the Maclaurin series for $f(x)$.", 3,
             [A1("$e^{-x} = 1 - x + \\dfrac{x^2}{2} - \\cdots$"),
              M1("multiply the series by $x$"),
              A1("$f(x) = x - x^2 + \\dfrac{x^3}{2} - \\cdots$")],
             answer="$x - x^2 + \\dfrac{x^3}{2}$",
             solution=("$$e^{-x} = 1 - x + \\frac{x^2}{2} - \\cdots "
                       "\\Rightarrow x e^{-x} = x - x^2 + \\frac{x^3}{2} "
                       "- \\cdots$$"),
             verify=["Eq(expand(series(x*exp(-x), x, 0, 4).removeO() "
                     "- (x - x**2 + x**3/2)), 0)"]),
    ]))

# ── Q10 [18] number_algebra (Section B): induction + contradiction ───────
assert sum(r*factorial(r) for r in range(1, 10)) == factorial(10) - 1
assert factorial(10) - 1 == 3628799
assert 1*factorial(1) == factorial(2) - 1
QS.append(question(
    "IB-AAHL-P1-T1-Q10", 10, "B", "number_algebra", "proof",
    parts=[
        part("a", "Prove by mathematical induction that "
             "$\\displaystyle\\sum_{r=1}^{n} r \\cdot r! = (n + 1)! - 1$ "
             "for all $n \\in \\mathbb{Z}^{+}$.", 8,
             [R1("base case $n = 1$: LHS $= 1\\cdot 1! = 1$, RHS $= 2! - 1 "
                 "= 1$ — true"),
              M1("assume true for $n = k$: $\\sum_{r=1}^{k} r\\cdot r! = "
                 "(k + 1)! - 1$"),
              M1("consider $n = k + 1$: add the next term "
                 "$(k + 1)(k + 1)!$"),
              A1("$\\sum_{r=1}^{k+1} r\\cdot r! = (k + 1)! - 1 + "
                 "(k + 1)(k + 1)!$"),
              M1("factor out $(k + 1)!$"),
              A1("$= (k + 1)!\\,(1 + k + 1) - 1 = (k + 2)! - 1$"),
              R1("this is the statement for $n = k + 1$"),
              R1("true for $n = 1$ and $k \\Rightarrow k + 1$, so true for "
                 "all $n \\in \\mathbb{Z}^{+}$ by induction")],
             answer="proof by induction (see solution)",
             solution=("**Base case** $n = 1$: LHS $= 1 \\cdot 1! = 1$ and "
                       "RHS $= 2! - 1 = 1$, so the statement holds."
                       "**Inductive step**: assume "
                       "$\\sum_{r=1}^{k} r\\cdot r! = (k+1)! - 1$. Then"
                       "$$\\sum_{r=1}^{k+1} r\\cdot r! = (k+1)! - 1 + "
                       "(k+1)(k+1)! = (k+1)!\\big(1 + (k+1)\\big) - 1$$"
                       "$$= (k+1)!\\,(k+2) - 1 = (k+2)! - 1,$$"
                       "which is the statement for $n = k + 1$. Since the "
                       "statement is true for $n = 1$ and truth for $k$ "
                       "implies truth for $k+1$, it holds for all positive "
                       "integers $n$ by mathematical induction."),
             verify=["Eq(1*factorial(1), factorial(2) - 1)",
                     "Eq(1*factorial(1) + 2*factorial(2) + 3*factorial(3) "
                     "+ 4*factorial(4) + 5*factorial(5), factorial(6) - 1)",
                     "Eq(expand((k + 1)*(1 + (k + 1))), "
                     "expand((k + 1)*(k + 2)))"]),
        part("b", "Hence find the exact value of "
             "$\\displaystyle\\sum_{r=1}^{9} r \\cdot r!$.", 2,
             [M1("apply the formula with $n = 9$: $10! - 1$"),
              A1("$3628799$")],
             answer="$3\\,628\\,799$",
             solution=("$$\\sum_{r=1}^{9} r\\cdot r! = 10! - 1 = "
                       "3628800 - 1 = 3628799.$$"),
             verify=["Eq(factorial(10) - 1, 3628799)",
                     "Eq(1*factorial(1) + 2*factorial(2) + 3*factorial(3) "
                     "+ 4*factorial(4) + 5*factorial(5) + 6*factorial(6) "
                     "+ 7*factorial(7) + 8*factorial(8) + 9*factorial(9), "
                     "3628799)"]),
        part("c", "Prove by contradiction that $\\sqrt{2}$ is irrational.", 8,
             [R1("assume $\\sqrt{2} = \\dfrac{p}{q}$ with $p, q \\in "
                 "\\mathbb{Z}$, $q \\ne 0$, and the fraction in lowest "
                 "terms"),
              M1("square: $2q^2 = p^2$"),
              R1("$p^2$ is even, hence $p$ is even"),
              M1("write $p = 2m$"),
              A1("$2q^2 = 4m^2 \\Rightarrow q^2 = 2m^2$"),
              R1("so $q^2$ is even, hence $q$ is even"),
              R1("both $p$ and $q$ even contradicts lowest terms"),
              R1("therefore $\\sqrt{2}$ is irrational")],
             answer="proof by contradiction (see solution)",
             solution=("Assume, for contradiction, that $\\sqrt{2}$ is "
                       "rational: $\\sqrt{2} = \\dfrac{p}{q}$ in lowest "
                       "terms. Squaring, $2q^2 = p^2$, so $p^2$ is even. An "
                       "odd number squared is odd, so $p$ must be even: "
                       "$p = 2m$. Then $2q^2 = 4m^2$, so $q^2 = 2m^2$ is "
                       "even, hence $q$ is even. But then $p$ and $q$ share "
                       "the factor 2, contradicting lowest terms. The "
                       "assumption is false, so $\\sqrt{2}$ is irrational."),
             verify=["Eq((2*3)**2, 4*3**2)", "Eq(2*2**2, 8)",
                     "Eq(sqrt(2)**2, 2)"]),
    ]))

META = {"course": "aa", "level": "hl", "paper": 1, "testId": "ib-hl-practice-1",
        "label": "AA HL Practice Paper 1", "timeMinutes": 120,
        "totalMarks": 110, "calculator": False}

if __name__ == "__main__":
    write_paper(META, QS, "data/ib/aa-hl/ib-hl-practice-1/paper1.json")
