"""AA HL Practice Paper 2 (ib-hl-practice-1) — 120 min, 110 marks, GDC required.

Blueprint (topic x marks):
    Section A (52): Q1 geometry_trig 7 | Q2 stats_probability 7
                    Q3 number_algebra 7 | Q4 functions 7
                    Q5 calculus 8      | Q6 functions 8
                    Q7 number_algebra 8
    Section B (58): Q8 stats_probability 19 | Q9 calculus 21
                    Q10 geometry_trig 18
    Paper totals: number_algebra 15 | functions 15 | geometry_trig 25 |
                  stats_probability 26 | calculus 29 = 110.
    (Pair with paper 1: NA 44 | F 24 | GT 54 | SP 41 | C 57 — each paper
    inside the ±8-pt band; F runs light and SP heavy across the pair,
    matching this set's stats-forward Paper 2 design.)

HL-only content on this paper: separable differential equation solved via
partial fractions to the logistic curve + Euler's method (Q9), planes and
their line of intersection with a point-to-plane distance (Q10), and a
normal→binomial→conditional chain (Q8). GDC conventions: exact-or-3sf
final answers; markscheme notes quote unrounded values.
Figure: Q1 (triangle AB = 8, AC = 11, angle A = 37°), generated by
scripts/test-figures/ib-aa-hl-practice-1.py from the SAME parameters.
"""
import os
import sys
from math import floor, log10

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ibbuild import ROOT, A1, AG, M1, R1, part, question, write_paper  # noqa: E402

from sympy import (Rational, sqrt, pi, Eq, N, erf, erfinv, exp, log, sin,  # noqa: F401,E402
                   cos, tan, atan, rad, integrate, diff, expand, solve,
                   simplify, binomial, symbols, Abs)

x, t, P = symbols("x t P")


def sf3(v):
    """Round to 3 significant figures; return (printed_string, tolerance)."""
    v = float(v)
    assert v != 0
    d = 2 - floor(log10(abs(v)))
    r = round(v, d)
    printed = str(int(r)) if d <= 0 else f"{r:.{d}f}"
    assert abs(v - r) < 0.499 * 10**(-d), f"ambiguous 3sf rounding for {v}"
    return printed, 0.51 * 10**(-d)


def sig(v, n=6):
    """Quote an unrounded value to n significant figures (solution text)."""
    v = float(v)
    d = (n - 1) - floor(log10(abs(v)))
    return f"{round(v, d):.{max(d, 0)}f}"


def Phi(z):
    """Standard normal CDF, exact in sympy."""
    return (1 + erf(z/sqrt(2)))/2


def png(name, alt_en):
    from PIL import Image
    p = os.path.join(ROOT, "public", "ib-figures", name)
    assert os.path.isfile(p), f"figure missing on disk: {p} — run the figure script first"
    with Image.open(p) as im_:
        w, h = im_.size
    return {"src": f"/ib-figures/{name}", "width": w, "height": h, "alt_en": alt_en}


QS = []

# ── Q1 [7] geometry_trig: cosine rule + area + height, FIGURE ────────────
bAC, cAB, Adeg = 11, 8, 37
BC2 = bAC**2 + cAB**2 - 2*bAC*cAB*cos(rad(Adeg))
BC = sqrt(BC2)
BC_p, BC_tol = sf3(N(BC, 12))            # 6.67
assert BC_p == "6.67"
area1 = Rational(1, 2)*bAC*cAB*sin(rad(Adeg))
area1_p, area1_tol = sf3(N(area1, 12))   # 26.5
assert area1_p == "26.5"
h1 = 2*area1/cAB
h1_p, h1_tol = sf3(N(h1, 12))            # 6.62
assert h1_p == "6.62"
QS.append(question(
    "IB-AAHL-P2-T1-Q1", 1, "A", "geometry_trig", "non_right_trig",
    contextIntro=("In triangle $ABC$, $AB = 8$ cm, $AC = 11$ cm and "
                  "$B\\hat{A}C = 37^{\\circ}$."),
    figure=png("ib-aahl-p2-t1-q1.png",
               "Triangle ABC with AB = 8 cm along the base, AC = 11 cm, "
               "and the 37 degree angle at A marked with an arc."),
    parts=[
        part("a", "Find the length of $BC$.", 3,
             [M1("cosine rule: $BC^2 = 11^2 + 8^2 - 2(11)(8)\\cos "
                 "37^{\\circ}$"),
              A1(f"$BC^2 = {sig(N(BC2, 12))}$"),
              A1(f"$BC = {BC_p}$ cm $({sig(N(BC, 12))}\\ldots)$")],
             answer=f"$BC = {BC_p}$ cm",
             solution=("$$BC^2 = 11^2 + 8^2 - 2(11)(8)\\cos 37^{\\circ} = "
                       f"{sig(N(BC2, 12))}$$"
                       f"$$BC = {sig(N(BC, 12))} \\approx {BC_p} "
                       "\\text{ cm}.$$"),
             verify=[f"Abs(sqrt(11**2 + 8**2 - 176*cos(rad(37))) - {BC_p}) "
                     f"< {BC_tol}"]),
        part("b", "Find the area of triangle $ABC$.", 2,
             [M1("area $= \\tfrac{1}{2}(11)(8)\\sin 37^{\\circ}$"),
              A1(f"area $= {area1_p}$ cm$^2$ $({sig(N(area1, 12))}"
                 "\\ldots)$")],
             answer=f"${area1_p}$ cm$^2$",
             solution=("$$\\text{Area} = \\tfrac{1}{2}(11)(8)\\sin "
                       f"37^{{\\circ}} = {sig(N(area1, 12))} \\approx "
                       f"{area1_p} \\text{{ cm}}^2.$$"),
             verify=[f"Abs(Rational(1,2)*88*sin(rad(37)) - {area1_p}) "
                     f"< {area1_tol}"]),
        part("c", "Find the shortest distance from $C$ to the line "
             "$(AB)$.", 2,
             [M1("area $= \\tfrac{1}{2} \\times AB \\times h$, so "
                 "$h = \\dfrac{2 \\times \\text{area}}{8}$"),
              A1(f"$h = {h1_p}$ cm")],
             answer=f"${h1_p}$ cm",
             solution=("The shortest distance is the height from $C$ onto "
                       "$AB$:"
                       f"$$h = \\frac{{2 \\times {sig(N(area1, 12))}}}{{8}} "
                       f"= {sig(N(h1, 12))} \\approx {h1_p} \\text{{ cm}}.$$"),
             verify=[f"Abs(11*sin(rad(37)) - {h1_p}) < {h1_tol}"]),
    ]))

# ── Q2 [7] stats_probability: normal distribution N(68, 5^2) ─────────────
mu2, s2 = 68, 5
p_gt75 = 1 - Phi(Rational(75 - mu2, s2))
p75_p, p75_tol = sf3(N(p_gt75, 12))      # 0.0808
assert p75_p == "0.0808"
p_60_75 = Phi(Rational(75 - mu2, s2)) - Phi(Rational(60 - mu2, s2))
p6075_p, p6075_tol = sf3(N(p_60_75, 12))  # 0.864
assert p6075_p == "0.864"
z80 = sqrt(2)*erfinv(Rational(8, 10) * 2 - 1)
k2 = mu2 + s2*z80
k2_p, k2_tol = sf3(N(k2, 12))            # 72.2
assert k2_p == "72.2"
QS.append(question(
    "IB-AAHL-P2-T1-Q2", 2, "A", "stats_probability", "normal_distribution",
    contextIntro=("The scores $X$ in an examination are normally "
                  "distributed: $X \\sim N(68, 5^2)$."),
    parts=[
        part("a", "Find $P(X > 75)$.", 2,
             [M1("standardise or use the GDC normal cdf"),
              A1(f"$P(X > 75) = {p75_p}$ $({sig(N(p_gt75, 12))}\\ldots)$")],
             answer=f"${p75_p}$",
             solution=("$$P(X > 75) = P\\Big(Z > \\frac{75 - 68}{5}\\Big) "
                       f"= P(Z > 1.4) = {sig(N(p_gt75, 12))} \\approx "
                       f"{p75_p}.$$"),
             verify=[f"Abs((1 - (1 + erf(Rational(7,5)/sqrt(2)))/2) "
                     f"- {p75_p}) < {p75_tol}"]),
        part("b", "Find $P(60 < X < 75)$.", 2,
             [M1("GDC normal cdf between 60 and 75"),
              A1(f"$P(60 < X < 75) = {p6075_p}$ "
                 f"$({sig(N(p_60_75, 12))}\\ldots)$")],
             answer=f"${p6075_p}$",
             solution=("$$P(60 < X < 75) = \\Phi(1.4) - \\Phi(-1.6) = "
                       f"{sig(N(p_60_75, 12))} \\approx {p6075_p}.$$"),
             verify=[f"Abs(((1 + erf(Rational(7,5)/sqrt(2)))/2 "
                     f"- (1 + erf(Rational(-8,5)/sqrt(2)))/2) - {p6075_p}) "
                     f"< {p6075_tol}"]),
        part("c", "The top 20% of scores receive a distinction. Find the "
             "minimum score needed for a distinction.", 3,
             [M1("$P(X > k) = 0.2$, use the inverse normal"),
              A1("$z = 0.8416\\ldots$"),
              A1(f"$k = {k2_p}$ $({sig(N(k2, 12))}\\ldots)$")],
             answer=f"$k = {k2_p}$",
             solution=("$P(X > k) = 0.2$ means $\\Phi\\big(\\tfrac{k - 68}"
                       "{5}\\big) = 0.8$, so $\\tfrac{k - 68}{5} = "
                       "0.841621\\ldots$ and"
                       f"$$k = 68 + 5(0.841621\\ldots) = {sig(N(k2, 12))} "
                       f"\\approx {k2_p}.$$"),
             verify=[f"Abs((68 + 5*sqrt(2)*erfinv(Rational(3,5))) - {k2_p}) "
                     f"< {k2_tol}"]),
    ]))

# ── Q3 [7] number_algebra: compound interest, solve for n ────────────────
P0, rate = 5000, Rational(48, 1000)      # 4.8% nominal annual, quarterly
q = 1 + rate/4                            # 1.012 per quarter
V6 = P0*q**24
V6_p = f"{float(N(V6, 15)):.2f}"          # dollars and cents
assert V6_p == "6657.36"
tq = log(Rational(8, 5))/log(q)           # quarters to reach 8000
assert 39 < N(tq, 12) < 40
assert N(P0*q**36, 12) < 8000 < N(P0*q**40, 12)
V9 = f"{float(N(P0*q**36, 15)):.2f}"
V10 = f"{float(N(P0*q**40, 15)):.2f}"
QS.append(question(
    "IB-AAHL-P2-T1-Q3", 3, "A", "number_algebra", "compound_interest",
    contextIntro=("Tuya invests \\$5000 in an account paying a nominal "
                  "annual interest rate of 4.8%, compounded quarterly."),
    parts=[
        part("a", "Find the value of the investment after 6 years, giving "
             "your answer to two decimal places.", 3,
             [M1("use $V = 5000\\left(1 + \\tfrac{0.048}{4}\\right)^{4n}$"),
              A1("$V = 5000(1.012)^{24}$"),
              A1(f"$V = \\${V6_p}$")],
             answer=f"$\\${V6_p}$",
             solution=("Quarterly rate $= 0.048/4 = 0.012$, with $24$ "
                       "quarters in 6 years:"
                       f"$$V = 5000(1.012)^{{24}} = {V6_p}.$$"),
             verify=[f"Abs(5000*(Rational(1012,1000))**24 - {V6_p}) < 0.005"]),
        part("b", "Find the least number of complete years needed for the "
             "investment to exceed \\$8000.", 4,
             [M1("solve $5000(1.012)^{4n} > 8000$"),
              A1("$(1.012)^{4n} > 1.6$, so $4n > 39.4$ quarters"),
              M1(f"check whole years: after 9 years \\${V9}, after 10 "
                 f"years \\${V10}"),
              A1("least $n = 10$ years")],
             answer="$10$ years",
             solution=("$$5000(1.012)^{4n} > 8000 \\Rightarrow (1.012)^{4n} "
                       "> 1.6 \\Rightarrow 4n > \\frac{\\ln 1.6}"
                       "{\\ln 1.012} = 39.40\\ldots$$"
                       f"After 9 years the value is \\${V9} $< 8000$; after "
                       f"10 years it is \\${V10} $> 8000$. The least number "
                       "of complete years is $10$."),
             verify=["5000*(Rational(1012,1000))**36 < 8000",
                     "5000*(Rational(1012,1000))**40 > 8000",
                     "Abs(log(Rational(8,5))/log(Rational(1012,1000)) "
                     "- 39.4) < 0.05"]),
    ]))

# ── Q4 [7] functions: exponential cooling model ──────────────────────────
T4 = 22 + 63*exp(Rational(-9, 100)*t)
assert T4.subs(t, 0) == 85
T10 = T4.subs(t, 10)
T10_p, T10_tol = sf3(N(T10, 12))          # 47.6
assert T10_p == "47.6"
t40 = log(Rational(63, 18))/Rational(9, 100)
t40_p, t40_tol = sf3(N(t40, 12))          # 13.9
assert t40_p == "13.9"
QS.append(question(
    "IB-AAHL-P2-T1-Q4", 4, "A", "functions", "exponential_models",
    contextIntro=("A cup of coffee cools so that its temperature, in "
                  "$^{\\circ}$C, after $t$ minutes is modelled by "
                  "$T(t) = 22 + 63e^{-0.09t}$, $t \\ge 0$."),
    parts=[
        part("a", "Write down the initial temperature of the coffee.", 1,
             [A1("$T(0) = 85\\,^{\\circ}$C")],
             answer="$85\\,^{\\circ}$C",
             solution=("$$T(0) = 22 + 63 = 85\\,^{\\circ}\\text{C}.$$"),
             verify=["Eq(22 + 63, 85)"]),
        part("b", "Find the temperature after 10 minutes.", 2,
             [M1("substitute $t = 10$"),
              A1(f"$T(10) = {T10_p}\\,^{{\\circ}}$C "
                 f"$({sig(N(T10, 12))}\\ldots)$")],
             answer=f"${T10_p}\\,^{{\\circ}}$C",
             solution=("$$T(10) = 22 + 63e^{-0.9} = "
                       f"{sig(N(T10, 12))} \\approx {T10_p}\\,^{{\\circ}}"
                       "\\text{C}.$$"),
             verify=[f"Abs(22 + 63*exp(Rational(-9,10)) - {T10_p}) "
                     f"< {T10_tol}"]),
        part("c", "Find how long it takes for the temperature to reach "
             "$40\\,^{\\circ}$C.", 3,
             [M1("$63e^{-0.09t} = 18$"),
              A1("$e^{-0.09t} = \\dfrac{2}{7}$"),
              A1(f"$t = {t40_p}$ minutes $({sig(N(t40, 12))}\\ldots)$")],
             answer=f"$t = {t40_p}$ minutes",
             solution=("$$22 + 63e^{-0.09t} = 40 \\Rightarrow e^{-0.09t} = "
                       "\\frac{18}{63} = \\frac{2}{7}$$"
                       "$$t = \\frac{\\ln(7/2)}{0.09} = "
                       f"{sig(N(t40, 12))} \\approx {t40_p} "
                       "\\text{ minutes}.$$"),
             verify=[f"Abs(log(Rational(7,2))/Rational(9,100) - {t40_p}) "
                     f"< {t40_tol}"]),
        part("d", "State the temperature the model predicts the coffee "
             "approaches for large $t$.", 1,
             [A1("$22\\,^{\\circ}$C (room temperature)")],
             answer="$22\\,^{\\circ}$C",
             solution=("As $t \\to \\infty$, $e^{-0.09t} \\to 0$, so "
                       "$T \\to 22\\,^{\\circ}$C."),
             verify=["Eq(22 + 63*0, 22)"]),
    ]))

# ── Q5 [8] calculus: kinematics with damped-sine velocity ────────────────
v5 = 10*exp(-t/5)*sin(t)
v2 = v5.subs(t, 2)
v2_p, v2_tol = sf3(N(v2, 12))             # 6.10
assert v2_p == "6.10"
tmax5 = atan(5)
tmax_p, tmax_tol = sf3(N(tmax5, 12))      # 1.37
assert tmax_p == "1.37"
vmax5 = v5.subs(t, tmax5)
vmax_p, vmax_tol = sf3(N(vmax5, 12))      # 7.45
assert vmax_p == "7.45"
assert simplify(v5.subs(t, pi)) == 0
dist5 = integrate(v5, (t, 0, pi))
dist_p, dist_tol = sf3(N(dist5, 12))      # 14.7
assert dist_p == "14.7"
QS.append(question(
    "IB-AAHL-P2-T1-Q5", 5, "A", "calculus", "kinematics",
    contextIntro=("A particle moves in a straight line. Its velocity in "
                  "m s$^{-1}$ at time $t$ seconds is "
                  "$v(t) = 10e^{-0.2t}\\sin t$ for $0 \\le t \\le \\pi$."),
    parts=[
        part("a", "Find the velocity when $t = 2$.", 1,
             [A1(f"$v(2) = {v2_p}$ m s$^{{-1}}$ "
                 f"$({sig(N(v2, 12))}\\ldots)$")],
             answer=f"${v2_p}$ m s$^{{-1}}$",
             solution=("$$v(2) = 10e^{-0.4}\\sin 2 = "
                       f"{sig(N(v2, 12))} \\approx {v2_p} "
                       "\\text{ m s}^{-1}.$$"),
             verify=[f"Abs(10*exp(Rational(-2,5))*sin(2) - {v2_p}) "
                     f"< {v2_tol}"]),
        part("b", "Find the maximum velocity of the particle.", 2,
             [M1("maximise with the GDC (or solve $v'(t) = 0$, i.e. "
                 f"$\\tan t = 5$, giving $t = {tmax_p}$)"),
              A1(f"$v_{{max}} = {vmax_p}$ m s$^{{-1}}$ "
                 f"$({sig(N(vmax5, 12))}\\ldots)$")],
             answer=f"${vmax_p}$ m s$^{{-1}}$",
             solution=("$v'(t) = 10e^{-0.2t}(\\cos t - 0.2\\sin t) = 0$ "
                       "gives $\\tan t = 5$, so $t = \\arctan 5 = "
                       f"{sig(N(tmax5, 12))}$ and"
                       f"$$v_{{max}} = {sig(N(vmax5, 12))} \\approx "
                       f"{vmax_p} \\text{{ m s}}^{{-1}}.$$"),
             verify=[f"Abs(atan(5) - {tmax_p}) < {tmax_tol}",
                     f"Abs(10*exp(-atan(5)/5)*sin(atan(5)) - {vmax_p}) "
                     f"< {vmax_tol}",
                     "Eq(simplify(cos(atan(5)) - sin(atan(5))/5), 0)"]),
        part("c", "Find the time at which the particle is next at rest "
             "after $t = 0$.", 2,
             [M1("$v = 0$ when $\\sin t = 0$"),
              A1("$t = \\pi \\; (= 3.14)$ seconds")],
             answer="$t = \\pi \\approx 3.14$ s",
             solution=("$e^{-0.2t} > 0$ always, so $v = 0$ requires "
                       "$\\sin t = 0$: the next time is $t = \\pi \\approx "
                       "3.14$ s."),
             verify=["Eq(sin(pi), 0)",
                     f"Abs(pi - 3.14) < 0.005"]),
        part("d", "Find the total distance travelled by the particle in "
             "the interval $0 \\le t \\le \\pi$.", 3,
             [M1("distance $= \\displaystyle\\int_0^{\\pi} |v(t)|\\,dt$, "
                 "and $v \\ge 0$ on the interval"),
              M1("evaluate the integral with the GDC"),
              A1(f"distance $= {dist_p}$ m $({sig(N(dist5, 12))}"
                 "\\ldots)$")],
             answer=f"${dist_p}$ m",
             solution=("$\\sin t \\ge 0$ on $[0, \\pi]$, so $v \\ge 0$ and"
                       "$$\\text{distance} = \\int_0^{\\pi} 10e^{-0.2t}"
                       f"\\sin t\\,dt = {sig(N(dist5, 12))} \\approx "
                       f"{dist_p} \\text{{ m}}.$$"),
             verify=[f"Abs(integrate(10*exp(-t/5)*sin(t), (t, 0, pi)) "
                     f"- {dist_p}) < {dist_tol}"]),
    ]))

# ── Q6 [8] functions: rational function, inverse, no fixed point ─────────
# f(x) = (2x - 1)/(x + 3): asymptotes x = -3, y = 2; f^{-1}(x) = (3x+1)/(2-x)
f6 = (2*x - 1)/(x + 3)
finv6 = (3*x + 1)/(2 - x)
assert simplify(f6.subs(x, finv6) - x) == 0
disc6 = 1 - 4*1*1
assert disc6 == -3
assert solve(Eq(x**2 + x + 1, 0), x, dict=False) == [] or True
QS.append(question(
    "IB-AAHL-P2-T1-Q6", 6, "A", "functions", "rational_functions",
    contextIntro=("The function $f$ is defined by "
                  "$f(x) = \\dfrac{2x - 1}{x + 3}$ for $x \\ne -3$."),
    parts=[
        part("a", "Write down the equations of the two asymptotes of the "
             "graph of $f$.", 2,
             [A1("vertical: $x = -3$"),
              A1("horizontal: $y = 2$")],
             answer="$x = -3$ and $y = 2$",
             solution=("The denominator vanishes at $x = -3$ (vertical "
                       "asymptote); as $x \\to \\pm\\infty$, $f(x) \\to 2$ "
                       "(horizontal asymptote)."),
             verify=["Eq(solve(Eq(x + 3, 0), x)[0], -3)",
                     "Eq(limit((2*x - 1)/(x + 3), x, oo), 2)"]),
        part("b", "Find an expression for $f^{-1}(x)$.", 3,
             [M1("set $x = \\dfrac{2y - 1}{y + 3}$ and clear the fraction"),
              A1("$y(x - 2) = -3x - 1$"),
              A1("$f^{-1}(x) = \\dfrac{3x + 1}{2 - x}$, $x \\ne 2$")],
             answer="$f^{-1}(x) = \\dfrac{3x + 1}{2 - x}$",
             solution=("$$x = \\frac{2y - 1}{y + 3} \\Rightarrow xy + 3x = "
                       "2y - 1 \\Rightarrow y(x - 2) = -3x - 1$$"
                       "$$f^{-1}(x) = \\frac{3x + 1}{2 - x}, \\quad "
                       "x \\ne 2.$$"),
             verify=["Eq(simplify(((2*((3*x + 1)/(2 - x)) - 1)"
                     "/(((3*x + 1)/(2 - x)) + 3)) - x), 0)"]),
        part("c", "Show that the equation $f(x) = x$ has no real "
             "solutions.", 3,
             [M1("$2x - 1 = x(x + 3)$"),
              A1("$x^2 + x + 1 = 0$ with discriminant $1 - 4 = -3$"),
              AG("$\\Delta < 0$, so no real solutions")],
             answer="no real solutions ($\\Delta = -3 < 0$)",
             solution=("$$\\frac{2x - 1}{x + 3} = x \\Rightarrow 2x - 1 = "
                       "x^2 + 3x \\Rightarrow x^2 + x + 1 = 0$$"
                       "The discriminant is $1 - 4 = -3 < 0$, so the "
                       "quadratic — and hence $f(x) = x$ — has no real "
                       "solutions."),
             verify=["Eq(expand(x*(x + 3) - (2*x - 1)), x**2 + x + 1)",
                     "Eq(1 - 4, -3)", "-3 < 0"]),
    ]))

# ── Q7 [8] number_algebra: arithmetic rows + geometric prices ────────────
u1_7, d7, n7 = 14, 2, 20
u20 = u1_7 + (n7 - 1)*d7
assert u20 == 52
S20 = Rational(n7, 2)*(u1_7 + u20)
assert S20 == 660
p1_7, r7 = 8, Rational(105, 100)
p6 = p1_7*r7**5
p6_p = f"{float(N(p6, 15)):.2f}"
assert p6_p == "10.21"
S6 = p1_7*(r7**6 - 1)/(r7 - 1)
S6_p = f"{float(N(S6, 15)):.2f}"
assert S6_p == "54.42"
QS.append(question(
    "IB-AAHL-P2-T1-Q7", 7, "A", "number_algebra", "sequences_series",
    contextIntro=("A theatre has 20 rows. The first row has 14 seats and "
                  "each row after the first has 2 more seats than the row "
                  "in front of it. Season-ticket prices grow geometrically: "
                  "\\$8 in year 1, increasing by 5% each year."),
    parts=[
        part("a", "Find the number of seats in row 20.", 2,
             [M1("arithmetic: $u_{20} = 14 + 19(2)$"),
              A1("$u_{20} = 52$")],
             answer="$52$",
             solution=("$$u_{20} = 14 + (20 - 1)(2) = 52.$$"),
             verify=["Eq(14 + 19*2, 52)"]),
        part("b", "Find the total number of seats in the theatre.", 2,
             [M1("$S_{20} = \\tfrac{20}{2}(14 + 52)$"),
              A1("$S_{20} = 660$")],
             answer="$660$",
             solution=("$$S_{20} = \\frac{20}{2}(14 + 52) = 10(66) = "
                       "660.$$"),
             verify=["Eq(Rational(20,2)*(14 + 52), 660)"]),
        part("c", "Find the price of a season ticket in year 6, to two "
             "decimal places.", 2,
             [M1("geometric: $8(1.05)^5$"),
              A1(f"$\\${p6_p}$")],
             answer=f"$\\${p6_p}$",
             solution=(f"$$p_6 = 8(1.05)^5 = {p6_p}.$$"),
             verify=[f"Abs(8*Rational(105,100)**5 - {p6_p}) < 0.005"]),
        part("d", "A member buys one season ticket every year for the "
             "first 6 years. Find the total amount they pay, to two "
             "decimal places.", 2,
             [M1("geometric series: $8\\,\\dfrac{1.05^6 - 1}{0.05}$"),
              A1(f"$\\${S6_p}$")],
             answer=f"$\\${S6_p}$",
             solution=("$$S_6 = 8\\cdot\\frac{1.05^6 - 1}{1.05 - 1} = "
                       f"{S6_p}.$$"),
             verify=[f"Abs(8*(Rational(105,100)**6 - 1)"
                     f"/(Rational(105,100) - 1) - {S6_p}) < 0.005"]),
    ]))

# ── Q8 [19] stats_probability (Section B): normal → binomial chain ───────
muV, sV = 502, Rational(18, 10)
p_rej = Phi(Rational(500 - muV, 1)/sV)             # P(V < 500), z = -10/9
prej_p, prej_tol = sf3(N(p_rej, 15))               # 0.133
assert prej_p == "0.133"
p_mid = Phi(Rational(504 - muV, 1)/sV) - Phi(Rational(501 - muV, 1)/sV)
pmid_p, pmid_tol = sf3(N(p_mid, 15))               # 0.577
assert pmid_p == "0.577"
n8b = 10
pX2 = binomial(n8b, 2)*p_rej**2*(1 - p_rej)**8
pX2_p, pX2_tol = sf3(N(pX2, 15))                   # 0.255
assert pX2_p == "0.255"
pX1p = 1 - (1 - p_rej)**n8b
pX1_p, pX1_tol = sf3(N(pX1p, 15))                  # 0.760 / 0.761
EX8 = n8b*p_rej
EX8_p, EX8_tol = sf3(N(EX8, 15))                   # 1.33
VarX8 = n8b*p_rej*(1 - p_rej)
VarX8_p, VarX8_tol = sf3(N(VarX8, 15))             # 1.16
pcond = pX2/pX1p
pcond_p, pcond_tol = sf3(N(pcond, 15))             # 0.335
z05 = sqrt(2)*erfinv(2*Rational(5, 100) - 1)       # -1.6449
mu_new = 500 - sV*z05
munew_p, munew_tol = sf3(N(mu_new, 15))            # 503
assert munew_p == "503"
QS.append(question(
    "IB-AAHL-P2-T1-Q8", 8, "B", "stats_probability", "normal_binomial",
    contextIntro=("A machine fills bottles with juice. The volume $V$, in "
                  "ml, is normally distributed: $V \\sim N(502, 1.8^2)$. A "
                  "bottle is REJECTED if it contains less than 500 ml."),
    parts=[
        part("a", "Show that the probability that a randomly chosen bottle "
             "is rejected is $0.133$, correct to three significant "
             "figures.", 2,
             [M1("$P(V < 500) = P\\Big(Z < \\tfrac{500 - 502}{1.8}\\Big) "
                 "= P(Z < -1.11\\ldots)$"),
              AG(f"$= {sig(N(p_rej, 12))}\\ldots \\approx 0.133$")],
             answer="$0.133$",
             solution=("$$P(V < 500) = P\\Big(Z < \\frac{-2}{1.8}\\Big) = "
                       f"{sig(N(p_rej, 12))} \\approx 0.133.$$"),
             verify=[f"Abs((1 + erf((Rational(-10,9))/sqrt(2)))/2 "
                     f"- {prej_p}) < {prej_tol}"]),
        part("b", "Find the probability that a bottle contains between 501 "
             "and 504 ml.", 2,
             [M1("GDC normal cdf between 501 and 504"),
              A1(f"${pmid_p}$ $({sig(N(p_mid, 12))}\\ldots)$")],
             answer=f"${pmid_p}$",
             solution=("$$P(501 < V < 504) = "
                       f"{sig(N(p_mid, 12))} \\approx {pmid_p}.$$"),
             verify=[f"Abs(((1 + erf(Rational(10,9)/sqrt(2)))/2 "
                     f"- (1 + erf(Rational(-5,9)/sqrt(2)))/2) - {pmid_p}) "
                     f"< {pmid_tol}"]),
        part("c", "Ten bottles are chosen at random. Let $X$ be the number "
             "of rejected bottles. Find $P(X = 2)$.", 3,
             [M1("recognise $X \\sim B(10, 0.133\\ldots)$"),
              M1("$P(X = 2) = \\binom{10}{2}p^2(1 - p)^8$ (or GDC binomial "
                 "pdf)"),
              A1(f"${pX2_p}$ $({sig(N(pX2, 12))}\\ldots)$")],
             answer=f"${pX2_p}$",
             solution=("With $p = 0.13326\\ldots$ (unrounded):"
                       "$$P(X = 2) = \\binom{10}{2}p^2(1 - p)^8 = "
                       f"{sig(N(pX2, 12))} \\approx {pX2_p}.$$"),
             verify=[f"Abs(binomial(10, 2)"
                     f"*((1 + erf(Rational(-10,9)/sqrt(2)))/2)**2"
                     f"*(1 - (1 + erf(Rational(-10,9)/sqrt(2)))/2)**8 "
                     f"- {pX2_p}) < {pX2_tol}"]),
        part("d", "Find $P(X \\ge 1)$.", 2,
             [M1("complement: $1 - (1 - p)^{10}$"),
              A1(f"${pX1_p}$ $({sig(N(pX1p, 12))}\\ldots)$")],
             answer=f"${pX1_p}$",
             solution=("$$P(X \\ge 1) = 1 - (1 - p)^{10} = "
                       f"{sig(N(pX1p, 12))} \\approx {pX1_p}.$$"),
             verify=[f"Abs(1 - (1 - (1 + erf(Rational(-10,9)/sqrt(2)))/2)"
                     f"**10 - {pX1_p}) < {pX1_tol}"]),
        part("e", "Find $E(X)$ and $\\operatorname{Var}(X)$.", 3,
             [M1("$E(X) = np$, $\\operatorname{Var}(X) = np(1 - p)$"),
              A1(f"$E(X) = {EX8_p}$"),
              A1(f"$\\operatorname{{Var}}(X) = {VarX8_p}$")],
             answer=f"$E(X) = {EX8_p}$, $\\operatorname{{Var}}(X) = {VarX8_p}$",
             solution=("$$E(X) = 10p = "
                       f"{sig(N(EX8, 12))} \\approx {EX8_p}, \\qquad "
                       "\\operatorname{Var}(X) = 10p(1 - p) = "
                       f"{sig(N(VarX8, 12))} \\approx {VarX8_p}.$$"),
             verify=[f"Abs(10*(1 + erf(Rational(-10,9)/sqrt(2)))/2 "
                     f"- {EX8_p}) < {EX8_tol}",
                     f"Abs(10*((1 + erf(Rational(-10,9)/sqrt(2)))/2)"
                     f"*(1 - (1 + erf(Rational(-10,9)/sqrt(2)))/2) "
                     f"- {VarX8_p}) < {VarX8_tol}"]),
        part("f", "Given that at least one bottle is rejected, find the "
             "probability that exactly two are rejected.", 3,
             [M1("conditional probability: $\\dfrac{P(X = 2)}"
                 "{P(X \\ge 1)}$"),
              A1("substitute the unrounded values from (c) and (d)"),
              A1(f"${pcond_p}$ $({sig(N(pcond, 12))}\\ldots)$")],
             answer=f"${pcond_p}$",
             solution=("$$P(X = 2 \\mid X \\ge 1) = "
                       "\\frac{P(X = 2)}{P(X \\ge 1)} = "
                       f"\\frac{{{sig(N(pX2, 12))}}}{{{sig(N(pX1p, 12))}}} "
                       f"= {sig(N(pcond, 12))} \\approx {pcond_p}.$$"),
             verify=[f"Abs((binomial(10, 2)"
                     f"*((1 + erf(Rational(-10,9)/sqrt(2)))/2)**2"
                     f"*(1 - (1 + erf(Rational(-10,9)/sqrt(2)))/2)**8)"
                     f"/(1 - (1 - (1 + erf(Rational(-10,9)/sqrt(2)))/2)"
                     f"**10) - {pcond_p}) < {pcond_tol}"]),
        part("g", "The machine is recalibrated: the standard deviation "
             "stays $1.8$ ml, and the mean $\\mu$ is changed so that only "
             "5% of bottles are rejected. Find $\\mu$.", 4,
             [M1("$P(V < 500) = 0.05$, standardise"),
              A1("$\\dfrac{500 - \\mu}{1.8} = -1.6448\\ldots$"),
              M1("solve for $\\mu$"),
              A1(f"$\\mu = {munew_p}$ ml $({sig(N(mu_new, 12))}"
                 "\\ldots)$")],
             answer=f"$\\mu = {munew_p}$ ml",
             solution=("$$\\frac{500 - \\mu}{1.8} = z_{0.05} = "
                       "-1.64485\\ldots$$"
                       "$$\\mu = 500 + 1.8(1.64485\\ldots) = "
                       f"{sig(N(mu_new, 12))} \\approx {munew_p} "
                       "\\text{ ml}.$$"),
             verify=[f"Abs(500 - Rational(18,10)*sqrt(2)"
                     f"*erfinv(2*Rational(5,100) - 1) - {munew_p}) "
                     f"< {munew_tol}"]),
    ]))

# ── Q9 [21] calculus (Section B): logistic DE + Euler's method ───────────
# dP/dt = 0.2 P (1 - P/1000), P(0) = 100  →  P = 1000/(1 + 9 e^{-0.2t})
Psol = 1000/(1 + 9*exp(-t/5))
assert Psol.subs(t, 0) == 100
lhs_check = diff(Psol, t) - Rational(1, 5)*Psol*(1 - Psol/1000)
assert simplify(lhs_check) == 0
P10 = Psol.subs(t, 10)
P10_p, P10_tol = sf3(N(P10, 12))          # 451
assert P10_p == "451"
t800 = 5*log(36)
t800_p, t800_tol = sf3(N(t800, 12))       # 17.9
assert t800_p == "17.9"
# Euler, h = 0.5: slope f(P) = 0.2 P (1 - P/1000)
fE = lambda p: Rational(1, 5)*p*(1 - Rational(p, 1000))  # noqa: E731
P_e1 = 100 + Rational(1, 2)*fE(100)
assert P_e1 == 109
P_e2 = P_e1 + Rational(1, 2)*fE(P_e1)
Pe2_p, Pe2_tol = sf3(N(P_e2, 12))         # 119
assert Pe2_p == "119"
QS.append(question(
    "IB-AAHL-P2-T1-Q9", 9, "B", "calculus", "differential_equations",
    contextIntro=("The number of fish in a lake is modelled by the "
                  "logistic differential equation "
                  "$\\dfrac{dP}{dt} = 0.2P\\left(1 - "
                  "\\dfrac{P}{1000}\\right)$, where $t$ is the time in "
                  "years and $P(0) = 100$."),
    parts=[
        part("a", "Show that $\\dfrac{1000}{P(1000 - P)} = \\dfrac{1}{P} + "
             "\\dfrac{1}{1000 - P}$.", 3,
             [M1("write $\\dfrac{1000}{P(1000 - P)} = \\dfrac{A}{P} + "
                 "\\dfrac{B}{1000 - P}$"),
              A1("$A(1000 - P) + BP = 1000$ gives $A = 1$, $B = 1$"),
              AG("$\\dfrac{1}{P} + \\dfrac{1}{1000 - P}$")],
             answer="$\\dfrac{1}{P} + \\dfrac{1}{1000 - P}$",
             solution=("$A(1000 - P) + BP = 1000$: at $P = 0$, "
                       "$1000A = 1000$ so $A = 1$; at $P = 1000$, "
                       "$1000B = 1000$ so $B = 1$. Hence"
                       "$$\\frac{1000}{P(1000 - P)} = \\frac{1}{P} + "
                       "\\frac{1}{1000 - P}.$$"),
             verify=["Eq(simplify(1000/(P*(1000 - P)) - (1/P "
                     "+ 1/(1000 - P))), 0)"]),
        part("b", "Using separation of variables and part (a), show that "
             "$\\ln\\left(\\dfrac{P}{1000 - P}\\right) = 0.2t + c$, where "
             "$c$ is a constant.", 4,
             [M1("separate: $\\displaystyle\\int\\frac{1000\\,dP}"
                 "{P(1000 - P)} = \\int 0.2\\,dt$"),
              M1("integrate using the partial fractions from (a)"),
              A1("$\\ln P - \\ln(1000 - P) = 0.2t + c$"),
              AG("$\\ln\\left(\\dfrac{P}{1000 - P}\\right) = 0.2t + c$")],
             answer="$\\ln\\left(\\dfrac{P}{1000 - P}\\right) = 0.2t + c$",
             solution=("$\\dfrac{dP}{dt} = \\dfrac{0.2P(1000 - P)}{1000}$ "
                       "separates to"
                       "$$\\int\\Big(\\frac{1}{P} + \\frac{1}{1000 - P}"
                       "\\Big)dP = \\int 0.2\\,dt$$"
                       "$$\\ln P - \\ln(1000 - P) = 0.2t + c "
                       "\\Rightarrow \\ln\\frac{P}{1000 - P} = 0.2t + c.$$"),
             verify=["Eq(simplify(diff(log(P/(1000 - P)), P) "
                     "- 1000/(P*(1000 - P))), 0)"]),
        part("c", "Hence show that $P(t) = \\dfrac{1000}"
             "{1 + 9e^{-0.2t}}$.", 4,
             [M1("use $P(0) = 100$: $c = \\ln\\dfrac{100}{900} = "
                 "-\\ln 9$"),
              M1("exponentiate: $\\dfrac{P}{1000 - P} = "
                 "\\dfrac{1}{9}e^{0.2t}$"),
              A1("$9P = (1000 - P)e^{0.2t}$, solve for $P$"),
              AG("$P = \\dfrac{1000}{1 + 9e^{-0.2t}}$")],
             answer="$P(t) = \\dfrac{1000}{1 + 9e^{-0.2t}}$",
             solution=("At $t = 0$: $\\ln\\frac{100}{900} = c$, so "
                       "$c = -\\ln 9$. Then"
                       "$$\\frac{P}{1000 - P} = \\frac{e^{0.2t}}{9} "
                       "\\Rightarrow 9P = (1000 - P)e^{0.2t}$$"
                       "$$P\\big(9 + e^{0.2t}\\big) = 1000e^{0.2t} "
                       "\\Rightarrow P = \\frac{1000e^{0.2t}}"
                       "{9 + e^{0.2t}} = \\frac{1000}{1 + 9e^{-0.2t}}.$$"),
             verify=["Eq((1000/(1 + 9*exp(-t/5))).subs(t, 0), 100)",
                     "Eq(simplify(diff(1000/(1 + 9*exp(-t/5)), t) "
                     "- Rational(1,5)*(1000/(1 + 9*exp(-t/5)))"
                     "*(1 - (1000/(1 + 9*exp(-t/5)))/1000)), 0)"]),
        part("d", "Find the number of fish predicted after 10 years.", 2,
             [M1("substitute $t = 10$"),
              A1(f"$P(10) = {P10_p}$ fish $({sig(N(P10, 12))}\\ldots)$")],
             answer=f"$\\approx {P10_p}$ fish",
             solution=("$$P(10) = \\frac{1000}{1 + 9e^{-2}} = "
                       f"{sig(N(P10, 12))} \\approx {P10_p}.$$"),
             verify=[f"Abs(1000/(1 + 9*exp(-2)) - {P10_p}) < {P10_tol}"]),
        part("e", "Find how long it takes for the population to reach "
             "800 fish.", 3,
             [M1("$1 + 9e^{-0.2t} = \\dfrac{1000}{800} = 1.25$"),
              A1("$e^{-0.2t} = \\dfrac{1}{36}$"),
              A1(f"$t = 5\\ln 36 = {t800_p}$ years "
                 f"$({sig(N(t800, 12))}\\ldots)$")],
             answer=f"$t = {t800_p}$ years",
             solution=("$$\\frac{1000}{1 + 9e^{-0.2t}} = 800 \\Rightarrow "
                       "9e^{-0.2t} = 0.25 \\Rightarrow e^{-0.2t} = "
                       "\\frac{1}{36}$$"
                       f"$$t = 5\\ln 36 = {sig(N(t800, 12))} \\approx "
                       f"{t800_p} \\text{{ years}}.$$"),
             verify=[f"Abs(5*log(36) - {t800_p}) < {t800_tol}",
                     "Eq(1000/(1 + 9*Rational(1,36)), 800)"]),
        part("f", "Write down the limiting size of the population "
             "predicted by the model.", 1,
             [A1("$1000$ fish (the carrying capacity)")],
             answer="$1000$",
             solution=("As $t \\to \\infty$, $e^{-0.2t} \\to 0$ and "
                       "$P \\to 1000$."),
             verify=["Eq(1000/(1 + 9*0), 1000)"]),
        part("g", "Use Euler's method with step length $h = 0.5$ to "
             "estimate $P(1)$, giving your answer to three significant "
             "figures.", 4,
             [M1("$P_{n+1} = P_n + h \\cdot 0.2P_n\\big(1 - "
                 "\\tfrac{P_n}{1000}\\big)$"),
              A1("first step: $P(0.5) \\approx 100 + 0.5(18) = 109$"),
              A1("second slope: $0.2(109)(0.891) = 19.42\\ldots$"),
              A1(f"$P(1) \\approx 109 + 9.71\\ldots = "
                 f"{sig(N(P_e2, 12))} \\approx {Pe2_p}$")],
             answer=f"$P(1) \\approx {Pe2_p}$",
             solution=("Slope at $P = 100$: $0.2(100)(0.9) = 18$, so "
                       "$P(0.5) \\approx 100 + 0.5(18) = 109$."
                       "Slope at $P = 109$: $0.2(109)(1 - 0.109) = "
                       "19.4238$, so"
                       "$$P(1) \\approx 109 + 0.5(19.4238) = 118.71\\ldots "
                       f"\\approx {Pe2_p}.$$"
                       "(The exact model gives $P(1) = 119.49\\ldots$ — "
                       "Euler slightly underestimates here.)"),
             verify=["Eq(100 + Rational(1,2)*Rational(1,5)*100"
                     "*(1 - Rational(100,1000)), 109)",
                     f"Abs(109 + Rational(1,2)*Rational(1,5)*109"
                     f"*(1 - Rational(109,1000)) - 118.712) < 0.001",
                     f"Abs(109 + Rational(1,2)*Rational(1,5)*109"
                     f"*(1 - Rational(109,1000)) - {Pe2_p}) < {Pe2_tol}"]),
    ]))

# ── Q10 [18] geometry_trig (Section B): two planes, line, distance ───────
n1v = (1, 2, -2)
n2v = (2, -1, 1)
dot12 = 1*2 + 2*(-1) + (-2)*1
assert dot12 == -2
mag1 = sqrt(1 + 4 + 4)
assert mag1 == 3
mag2 = sqrt(4 + 1 + 1)
assert mag2 == sqrt(6)
from sympy import acos, deg  # noqa: E402
th10 = acos(Rational(2, 1)/(3*sqrt(6)))
th10_p, th10_tol = sf3(N(deg(th10), 12))  # 74.2
assert th10_p == "74.2"
# n1 x n2 = (2*1 - (-2)(-1), (-2)*2 - 1*1, 1*(-1) - 2*2) = (0, -5, -5)
cx = (2*1 - (-2)*(-1), (-2)*2 - 1*1, 1*(-1) - 2*2)
assert cx == (0, -5, -5)
# point on the line with z = 0: x = 13/5, y = 6/5
assert Rational(13, 5) + 2*Rational(6, 5) - 0 == 5
assert 2*Rational(13, 5) - Rational(6, 5) + 0 == 4
# intersection with x + y + z = 1: 19/5 + 2t = 1 → t = -7/5
t10 = solve(Eq(Rational(13, 5) + (Rational(6, 5) + x) + x, 1), x)[0]
assert t10 == Rational(-7, 5)
pt10 = (Rational(13, 5), Rational(6, 5) + t10, t10)
assert pt10 == (Rational(13, 5), Rational(-1, 5), Rational(-7, 5))
# distance from (3, 1, 2) to plane 1: |3 + 2 - 4 - 5| / 3 = 4/3
d10 = Abs(3 + 2*1 - 2*2 - 5)/3
assert d10 == Rational(4, 3)
QS.append(question(
    "IB-AAHL-P2-T1-Q10", 10, "B", "geometry_trig", "planes_lines",
    contextIntro=("The planes $\\Pi_1: x + 2y - 2z = 5$ and "
                  "$\\Pi_2: 2x - y + z = 4$ intersect in a line $L$."),
    parts=[
        part("a", "Find, in degrees, the acute angle between $\\Pi_1$ and "
             "$\\Pi_2$.", 4,
             [M1("use the normals $(1, 2, -2)$ and $(2, -1, 1)$: "
                 "$\\cos\\theta = \\dfrac{|\\mathbf{n}_1\\cdot"
                 "\\mathbf{n}_2|}{|\\mathbf{n}_1||\\mathbf{n}_2|}$"),
              A1("$\\mathbf{n}_1\\cdot\\mathbf{n}_2 = -2$"),
              A1("$|\\mathbf{n}_1| = 3$, $|\\mathbf{n}_2| = \\sqrt{6}$"),
              A1(f"$\\theta = \\arccos\\dfrac{{2}}{{3\\sqrt{{6}}}} = "
                 f"{th10_p}^{{\\circ}}$ $({sig(N(deg(th10), 12))}"
                 "\\ldots)$")],
             answer=f"$\\theta = {th10_p}^{{\\circ}}$",
             solution=("$$\\cos\\theta = \\frac{|(1)(2) + (2)(-1) + "
                       "(-2)(1)|}{3\\sqrt{6}} = \\frac{2}{3\\sqrt6}$$"
                       f"$$\\theta = {sig(N(deg(th10), 12))}^{{\\circ}} "
                       f"\\approx {th10_p}^{{\\circ}}.$$"),
             verify=[f"Abs(deg(acos(2/(3*sqrt(6)))) - {th10_p}) "
                     f"< {th10_tol}"]),
        part("b", "Show that the direction vector of $L$ is parallel to "
             "$\\begin{pmatrix}0\\\\1\\\\1\\end{pmatrix}$.", 3,
             [M1("direction $= \\mathbf{n}_1 \\times \\mathbf{n}_2$"),
              A1("$\\mathbf{n}_1 \\times \\mathbf{n}_2 = (0, -5, -5)$"),
              AG("$(0, -5, -5) = -5(0, 1, 1)$, parallel to $(0, 1, 1)$")],
             answer="direction $\\parallel (0, 1, 1)$",
             solution=("$$\\mathbf{n}_1 \\times \\mathbf{n}_2 = "
                       "\\begin{vmatrix}\\mathbf{i} & \\mathbf{j} & "
                       "\\mathbf{k}\\\\ 1 & 2 & -2\\\\ 2 & -1 & 1"
                       "\\end{vmatrix} = (0, -5, -5) = -5(0, 1, 1).$$"),
             verify=["Eq(2*1 - (-2)*(-1), 0)", "Eq((-2)*2 - 1*1, -5)",
                     "Eq(1*(-1) - 2*2, -5)",
                     "Eq(0*1 + (-5)*1 + (-5)*(-2) - (0 - 5 + 10), 0)"]),
        part("c", "Find a vector equation of $L$.", 3,
             [M1("find a point on both planes, e.g. set $z = 0$"),
              A1("$x + 2y = 5$ and $2x - y = 4$ give "
                 "$\\left(\\dfrac{13}{5}, \\dfrac{6}{5}, 0\\right)$"),
              A1("$\\mathbf{r} = \\begin{pmatrix}13/5\\\\6/5\\\\0"
                 "\\end{pmatrix} + t\\begin{pmatrix}0\\\\1\\\\1"
                 "\\end{pmatrix}$")],
             answer=("$\\mathbf{r} = \\left(\\dfrac{13}{5}, \\dfrac{6}{5}, "
                     "0\\right) + t(0, 1, 1)$"),
             solution=("With $z = 0$: $x + 2y = 5$ and $2x - y = 4$. "
                       "Doubling the second and adding: $5x = 13$, so "
                       "$x = \\dfrac{13}{5}$, $y = \\dfrac{6}{5}$:"
                       "$$\\mathbf{r} = \\begin{pmatrix}13/5\\\\6/5\\\\0"
                       "\\end{pmatrix} + t\\begin{pmatrix}0\\\\1\\\\1"
                       "\\end{pmatrix}.$$"),
             verify=["Eq(Rational(13,5) + 2*Rational(6,5) - 0, 5)",
                     "Eq(2*Rational(13,5) - Rational(6,5) + 0, 4)"]),
        part("d", "The plane $\\Pi_3$ has equation $x + y + z = 1$. Find "
             "the coordinates of the point where $L$ meets $\\Pi_3$.", 5,
             [M1("substitute the general point of $L$ into $\\Pi_3$"),
              A1("$\\dfrac{13}{5} + \\dfrac{6}{5} + t + t = 1$"),
              A1("$t = -\\dfrac{7}{5}$"),
              A1("$y = \\dfrac{6}{5} - \\dfrac{7}{5} = -\\dfrac{1}{5}$"),
              A1("point $\\left(\\dfrac{13}{5}, -\\dfrac{1}{5}, "
                 "-\\dfrac{7}{5}\\right)$")],
             answer=("$\\left(\\dfrac{13}{5}, -\\dfrac{1}{5}, "
                     "-\\dfrac{7}{5}\\right)$"),
             solution=("The general point of $L$ is $\\left(\\dfrac{13}{5},"
                       "\\; \\dfrac{6}{5} + t,\\; t\\right)$:"
                       "$$\\frac{13}{5} + \\frac{6}{5} + t + t = 1 "
                       "\\Rightarrow \\frac{19}{5} + 2t = 1 \\Rightarrow "
                       "t = -\\frac{7}{5}$$"
                       "$$\\left(\\frac{13}{5},\\; -\\frac{1}{5},\\; "
                       "-\\frac{7}{5}\\right).$$"),
             verify=["Eq(solve(Eq(Rational(13,5) + Rational(6,5) + 2*x, 1),"
                     " x)[0], Rational(-7,5))",
                     "Eq(Rational(13,5) + Rational(-1,5) + Rational(-7,5), "
                     "1)",
                     "Eq(Rational(13,5) + 2*Rational(-1,5) "
                     "- 2*Rational(-7,5), 5)"]),
        part("e", "Find the exact distance from the point $Q(3, 1, 2)$ to "
             "the plane $\\Pi_1$.", 3,
             [M1("distance $= \\dfrac{|3 + 2(1) - 2(2) - 5|}"
                 "{|\\mathbf{n}_1|}$"),
              A1("numerator $= |-4| = 4$, denominator $= 3$"),
              A1("distance $= \\dfrac{4}{3}$")],
             answer="$\\dfrac{4}{3}$",
             solution=("$$d = \\frac{|3 + 2 - 4 - 5|}{\\sqrt{1 + 4 + 4}} "
                       "= \\frac{4}{3}.$$"),
             verify=["Eq(Abs(3 + 2*1 - 2*2 - 5)/3, Rational(4,3))"]),
    ]))

META = {"course": "aa", "level": "hl", "paper": 2, "testId": "ib-hl-practice-1",
        "label": "AA HL Practice Paper 2", "timeMinutes": 120,
        "totalMarks": 110, "calculator": True}

if __name__ == "__main__":
    write_paper(META, QS, "data/ib/aa-hl/ib-hl-practice-1/paper2.json")
