"""AA SL Practice Paper 1 (ib-practice-2) — 90 min, 80 marks, NO calculator.

Blueprint (topic x marks; pair target with paper 2 in parentheses):
    Section A (40): Q1 number_algebra 5 | Q2 stats_probability 5
                    Q3 geometry_trig 6  | Q4 functions 6
                    Q5 number_algebra 8 | Q6 calculus 10
    Section B (40): Q7 geometry_trig 13 | Q8 stats_probability 12
                    Q9 calculus 15
    Paper totals: number_algebra 13 (16%) | functions 6 (8%) |
                  geometry_trig 19 (24%)  | stats_probability 17 (21%) |
                  calculus 25 (31%)
    Paper 2 pushes functions up and calculus/geometry down so the pair
    lands near the AA SL blueprint.

Every answer is exact (no-calculator paper): fractions, surds, multiples of
pi. Figures: Q7 (triangle + sector), Q9 (cubic with shaded region R) —
generated by scripts/test-figures/ib-aa-sl-practice-2.py from the SAME
parameters. Archetypes are fresh versus practice 1.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ibbuild import ROOT, A1, AG, M1, R1, part, question, write_paper  # noqa: E402

from sympy import (Rational, sqrt, pi, Eq, sympify, simplify, solve,  # noqa: F401,E402
                   expand, factor, diff, integrate, sin, cos, log, symbols)

x = symbols("x")


def png(name, alt_en):
    """Figure object with dims read from disk (never guessed)."""
    from PIL import Image
    p = os.path.join(ROOT, "public", "ib-figures", name)
    assert os.path.isfile(p), f"figure missing on disk: {p} — run the figure script first"
    with Image.open(p) as im:
        w, h = im.size
    return {"src": f"/ib-figures/{name}", "width": w, "height": h, "alt_en": alt_en}


QS = []

# ── Q1 [5] number_algebra: geometric sequence ─────────────────────────────
u1, r = 3, 2
assert u1 * r**2 == 12 and u1 * r**4 == 48
s6 = u1 * (r**6 - 1) // (r - 1)
assert s6 == 189
QS.append(question(
    "IB-AASL-P1-T2-Q1", 1, "A", "number_algebra", "geometric_sequences",
    contextIntro=("A geometric sequence has first term $u_1 = 3$ and third "
                  "term $u_3 = 12$, with a positive common ratio $r$."),
    parts=[
        part("a", "Find the common ratio $r$.", 2,
             [M1("attempt to use $u_3 = u_1 r^2$, i.e. $12 = 3r^2$"),
              A1("$r = 2$")],
             answer="$r = 2$",
             solution=("**Plan:** the third term is two ratio-steps beyond the "
                       "first. $$u_3 = u_1 r^2 \\Rightarrow 12 = 3r^2$$"
                       "$$r^2 = 4 \\Rightarrow r = 2 \\;(r > 0)$$"),
             verify=["Eq(3*2**2, 12)"]),
        part("b", "Find the fifth term $u_5$.", 1,
             [A1("$u_5 = 48$")],
             answer="$u_5 = 48$",
             solution=("$$u_5 = u_1 r^4 = 3 \\cdot 2^4 = 3 \\cdot 16 = 48$$"),
             verify=["Eq(3*2**4, 48)"]),
        part("c", "Find the sum of the first six terms, $S_6$.", 2,
             [M1("attempt to use $S_n = \\dfrac{u_1(r^n - 1)}{r - 1}$"),
              A1("$S_6 = 189$")],
             answer="$S_6 = 189$",
             solution=("$$S_6 = \\frac{u_1(r^6 - 1)}{r - 1} "
                       "= \\frac{3(2^6 - 1)}{2 - 1} = 3(63) = 189$$"),
             verify=["Eq(3*(2**6 - 1)/(2 - 1), 189)"]),
    ]))

# ── Q2 [5] stats_probability: independent events ──────────────────────────
pA, pB = Rational(1, 2), Rational(2, 5)
assert pA * pB == Rational(1, 5)
assert pA + pB - pA * pB == Rational(7, 10)
QS.append(question(
    "IB-AASL-P1-T2-Q2", 2, "A", "stats_probability", "probability_basics",
    contextIntro=("Two events $A$ and $B$ are independent, with "
                  "$P(A) = \\dfrac{1}{2}$ and $P(B) = \\dfrac{2}{5}$."),
    parts=[
        part("a", "Find $P(A \\cap B)$.", 2,
             [M1("use independence: $P(A \\cap B) = P(A)\\,P(B)$"),
              A1("$P(A \\cap B) = \\dfrac{1}{5}$")],
             answer="$\\dfrac{1}{5}$",
             solution=("For independent events the intersection is the product:"
                       "$$P(A \\cap B) = \\tfrac{1}{2} \\cdot \\tfrac{2}{5} "
                       "= \\tfrac{1}{5}$$"),
             verify=["Eq(Rational(1,2)*Rational(2,5), Rational(1,5))"]),
        part("b", "Find $P(A \\cup B)$.", 3,
             [M1("use $P(A \\cup B) = P(A) + P(B) - P(A \\cap B)$"),
              A1("$\\tfrac{1}{2} + \\tfrac{2}{5} - \\tfrac{1}{5}$"),
              A1("$P(A \\cup B) = \\dfrac{7}{10}$")],
             answer="$\\dfrac{7}{10}$",
             solution=("Apply the addition rule:"
                       "$$P(A \\cup B) = \\tfrac{1}{2} + \\tfrac{2}{5} "
                       "- \\tfrac{1}{5} = \\tfrac{5}{10} + \\tfrac{4}{10} "
                       "- \\tfrac{2}{10} = \\tfrac{7}{10}$$"),
             verify=["Eq(Rational(1,2)+Rational(2,5)-Rational(1,5), Rational(7,10))"]),
    ]))

# ── Q3 [6] geometry_trig: exact trig from a ratio ─────────────────────────
assert sqrt(1 - Rational(3, 5)**2) == Rational(4, 5)
assert 2 * Rational(3, 5) * Rational(4, 5) == Rational(24, 25)
QS.append(question(
    "IB-AASL-P1-T2-Q3", 3, "A", "geometry_trig", "trig_identities",
    contextIntro=("The angle $\\theta$ is acute and $\\sin\\theta = "
                  "\\dfrac{3}{5}$."),
    parts=[
        part("a", "Find the exact value of $\\cos\\theta$.", 3,
             [M1("use $\\sin^2\\theta + \\cos^2\\theta = 1$ or a 3-4-5 triangle"),
              A1("$\\cos^2\\theta = 1 - \\tfrac{9}{25} = \\tfrac{16}{25}$"),
              A1("$\\cos\\theta = \\dfrac{4}{5}$ (positive, $\\theta$ acute)")],
             answer="$\\cos\\theta = \\dfrac{4}{5}$",
             solution=("**Plan:** use the Pythagorean identity."
                       "$$\\cos^2\\theta = 1 - \\sin^2\\theta "
                       "= 1 - \\tfrac{9}{25} = \\tfrac{16}{25}$$"
                       "Since $\\theta$ is acute, $\\cos\\theta > 0$, so "
                       "$\\cos\\theta = \\tfrac{4}{5}$."),
             verify=["Eq(sqrt(1 - Rational(3,5)**2), Rational(4,5))"]),
        part("b", "Hence find the exact value of $\\sin 2\\theta$.", 3,
             [M1("use $\\sin 2\\theta = 2\\sin\\theta\\cos\\theta$"),
              A1("$2 \\cdot \\tfrac{3}{5} \\cdot \\tfrac{4}{5}$"),
              A1("$\\sin 2\\theta = \\dfrac{24}{25}$")],
             answer="$\\sin 2\\theta = \\dfrac{24}{25}$",
             solution=("Use the double-angle identity with the values above:"
                       "$$\\sin 2\\theta = 2\\sin\\theta\\cos\\theta "
                       "= 2 \\cdot \\tfrac{3}{5} \\cdot \\tfrac{4}{5} "
                       "= \\tfrac{24}{25}$$"),
             verify=["Eq(2*Rational(3,5)*Rational(4,5), Rational(24,25))"]),
    ]))

# ── Q4 [6] functions: quadratic ───────────────────────────────────────────
assert expand((x - 1) * (x - 5)) == x**2 - 6 * x + 5
assert expand((x - 3)**2 - 4) == x**2 - 6 * x + 5
QS.append(question(
    "IB-AASL-P1-T2-Q4", 4, "A", "functions", "quadratic_functions",
    contextIntro=("The function $f$ is given by $f(x) = x^2 - 6x + 5$."),
    parts=[
        part("a", "Find the coordinates of the points where the graph of "
             "$f$ crosses the $x$-axis.", 3,
             [M1("set $f(x) = 0$ and factorise: $(x - 1)(x - 5) = 0$"),
              A1("$x = 1$"), A1("$x = 5$, giving $(1, 0)$ and $(5, 0)$")],
             answer="$(1, 0)$ and $(5, 0)$",
             solution=("**Plan:** the $x$-intercepts occur where $f(x) = 0$."
                       "$$x^2 - 6x + 5 = (x - 1)(x - 5) = 0$$"
                       "So $x = 1$ or $x = 5$; the graph crosses at "
                       "$(1, 0)$ and $(5, 0)$."),
             verify=["Eq(expand((x - 1)*(x - 5)), x**2 - 6*x + 5)"]),
        part("b", "Write $f(x)$ in the form $(x - h)^2 + k$ and hence state "
             "the minimum value of $f$.", 3,
             [M1("complete the square: half of $-6$ is $-3$"),
              A1("$f(x) = (x - 3)^2 - 4$"),
              A1("minimum value $-4$ (at $x = 3$)")],
             answer="$f(x) = (x - 3)^2 - 4$; minimum value $-4$",
             solution=("Complete the square:"
                       "$$f(x) = (x^2 - 6x + 9) - 9 + 5 = (x - 3)^2 - 4$$"
                       "The square is never negative, so the least value is "
                       "$-4$, attained at $x = 3$."),
             verify=["Eq(expand((x - 3)**2 - 4), x**2 - 6*x + 5)"]),
    ]))

# ── Q5 [8] number_algebra: logs & exponents (no calculator) ───────────────
assert log(16, 2) == 4
assert 2 * Rational(3, 2) == 3
assert 2 * 3**2 == 18
QS.append(question(
    "IB-AASL-P1-T2-Q5", 5, "A", "number_algebra", "exponents_logs",
    parts=[
        part("a", "Find the value of $\\log_2 16$.", 2,
             [M1("write $16$ as a power of $2$: $16 = 2^4$"),
              A1("$\\log_2 16 = 4$")],
             answer="$4$",
             solution=("Since $16 = 2^4$,"
                       "$$\\log_2 16 = \\log_2 2^4 = 4.$$"),
             verify=["Eq(log(16, 2), 4)"]),
        part("b", "Solve $3^{2x} = 27$.", 3,
             [M1("write both sides with base 3: $27 = 3^3$"),
              A1("$2x = 3$"), A1("$x = \\dfrac{3}{2}$")],
             answer="$x = \\dfrac{3}{2}$",
             solution=("Express $27$ as a power of $3$ and equate exponents:"
                       "$$3^{2x} = 3^3 \\Rightarrow 2x = 3 "
                       "\\Rightarrow x = \\tfrac{3}{2}.$$"),
             verify=["Eq(3**(2*Rational(3,2)), 27)", "Eq(2*Rational(3,2), 3)"]),
        part("c", "Given that $\\log_a 2 = p$ and $\\log_a 3 = q$, express "
             "$\\log_a 18$ in terms of $p$ and $q$.", 3,
             [M1("factorise $18 = 2 \\cdot 3^2$"),
              A1("$\\log_a 18 = \\log_a 2 + 2\\log_a 3$"),
              A1("$\\log_a 18 = p + 2q$")],
             answer="$p + 2q$",
             solution=("Write $18 = 2 \\cdot 3^2$ and use the log laws:"
                       "$$\\log_a 18 = \\log_a 2 + \\log_a 3^2 "
                       "= \\log_a 2 + 2\\log_a 3 = p + 2q.$$"),
             verify=["Eq(2*3**2, 18)"]),
    ]))

# ── Q6 [10] calculus: stationary points of a cubic ────────────────────────
f6 = x**3 - 3 * x**2 + 2
assert diff(f6, x) == 3 * x**2 - 6 * x
assert f6.subs(x, 0) == 2 and f6.subs(x, 2) == -2
assert (6 * x - 6).subs(x, 0) == -6 and (6 * x - 6).subs(x, 2) == 6
QS.append(question(
    "IB-AASL-P1-T2-Q6", 6, "A", "calculus", "differentiation_applications",
    contextIntro=("The function $f$ is defined by $f(x) = x^3 - 3x^2 + 2$."),
    parts=[
        part("a", "Find $f'(x)$.", 2,
             [M1("differentiate term by term"),
              A1("$f'(x) = 3x^2 - 6x$")],
             answer="$f'(x) = 3x^2 - 6x$",
             solution=("$$f'(x) = 3x^2 - 6x$$"),
             verify=["Eq(diff(x**3 - 3*x**2 + 2, x), 3*x**2 - 6*x)"]),
        part("b", "Find the coordinates of the two stationary points of the "
             "graph of $f$.", 4,
             [M1("set $f'(x) = 0$: $3x(x - 2) = 0$"),
              A1("$x = 0$ and $x = 2$"),
              A1("$(0, 2)$"), A1("$(2, -2)$")],
             answer="$(0, 2)$ and $(2, -2)$",
             solution=("**Plan:** stationary points occur where $f'(x) = 0$."
                       "$$3x^2 - 6x = 3x(x - 2) = 0 \\Rightarrow x = 0 "
                       "\\text{ or } x = 2$$"
                       "Then $f(0) = 2$ and $f(2) = 8 - 12 + 2 = -2$, giving "
                       "$(0, 2)$ and $(2, -2)$."),
             verify=["Eq(0**3 - 3*0**2 + 2, 2)", "Eq(2**3 - 3*2**2 + 2, -2)"]),
        part("c", "Determine the nature of each stationary point.", 4,
             [M1("find the second derivative $f''(x) = 6x - 6$"),
              A1("$f''(0) = -6 < 0$"),
              R1("so $(0, 2)$ is a local maximum"),
              A1("$f''(2) = 6 > 0$, so $(2, -2)$ is a local minimum")],
             answer="$(0, 2)$ is a maximum; $(2, -2)$ is a minimum",
             solution=("Use the second derivative $f''(x) = 6x - 6$."
                       "$$f''(0) = -6 < 0 \\Rightarrow \\text{local maximum at } (0, 2)$$"
                       "$$f''(2) = 6 > 0 \\Rightarrow \\text{local minimum at } (2, -2)$$"),
             verify=["Eq(expand(diff(x**3 - 3*x**2 + 2, x, 2)), 6*x - 6)",
                     "Eq((6*x - 6).subs(x, 0), -6)", "Eq((6*x - 6).subs(x, 2), 6)"]),
    ]))

# ── Q7 [13] geometry_trig (Section B): triangle + sector, FIGURE ──────────
# Triangle ABC: AB = 10, AC = 6, angle A = pi/3. Sector centre A radius 6.
AB, AC, angA = 10, 6, pi / 3
BC2 = AB**2 + AC**2 - 2 * AB * AC * cos(angA)
assert simplify(BC2 - 76) == 0
assert simplify(sqrt(76) - 2 * sqrt(19)) == 0
tri_area = Rational(1, 2) * AB * AC * sin(angA)
assert simplify(tri_area - 15 * sqrt(3)) == 0
sector_area = Rational(1, 2) * AC**2 * angA
assert simplify(sector_area - 6 * pi) == 0
QS.append(question(
    "IB-AASL-P1-T2-Q7", 7, "B", "geometry_trig", "non_right_triangles",
    contextIntro=("In triangle $ABC$, $AB = 10$ cm, $AC = 6$ cm and the "
                  "angle at $A$ is $\\dfrac{\\pi}{3}$. A sector of a circle "
                  "with centre $A$ and radius $6$ cm is drawn inside the "
                  "triangle, as shown."),
    figure=png("ib-aasl-p1-t2-q7.png",
               "Triangle ABC with AB = 10 cm along the base, AC = 6 cm, and "
               "angle A = pi/3; a shaded circular sector of centre A and "
               "radius 6 cm fills the angle at A."),
    parts=[
        part("a", "Find $BC$, giving your answer in the form $a\\sqrt{b}$ "
             "where $a, b \\in \\mathbb{Z}^+$.", 4,
             [M1("apply the cosine rule $BC^2 = AB^2 + AC^2 - 2\\,AB\\,AC\\cos A$"),
              A1("$BC^2 = 100 + 36 - 120\\cos\\tfrac{\\pi}{3} = 76$"),
              M1("$BC = \\sqrt{76} = \\sqrt{4 \\cdot 19}$"),
              A1("$BC = 2\\sqrt{19}$ cm")],
             answer="$BC = 2\\sqrt{19}$ cm",
             solution=("**Plan:** two sides and the included angle → cosine rule."
                       "$$BC^2 = 10^2 + 6^2 - 2(10)(6)\\cos\\tfrac{\\pi}{3} "
                       "= 136 - 120 \\cdot \\tfrac{1}{2} = 76$$"
                       "$$BC = \\sqrt{76} = \\sqrt{4 \\cdot 19} = 2\\sqrt{19}$$"),
             verify=["Eq(10**2 + 6**2 - 2*10*6*cos(pi/3), 76)",
                     "Eq(sqrt(76), 2*sqrt(19))"]),
        part("b", "Find the area of triangle $ABC$, giving your answer in "
             "the form $c\\sqrt{d}$.", 3,
             [M1("use area $= \\tfrac{1}{2}\\,AB\\,AC\\sin A$"),
              A1("$\\tfrac{1}{2}(10)(6)\\sin\\tfrac{\\pi}{3} = 30 \\cdot \\tfrac{\\sqrt3}{2}$"),
              A1("area $= 15\\sqrt{3}$ cm$^2$")],
             answer="$15\\sqrt{3}$ cm$^2$",
             solution=("$$\\text{Area} = \\tfrac{1}{2}\\,AB\\,AC\\sin A "
                       "= \\tfrac{1}{2}(10)(6)\\sin\\tfrac{\\pi}{3} "
                       "= 30 \\cdot \\tfrac{\\sqrt3}{2} = 15\\sqrt{3}$$"),
             verify=["Eq(Rational(1,2)*10*6*sin(pi/3), 15*sqrt(3))"]),
        part("c", "Find the area of the shaded sector.", 3,
             [M1("use sector area $= \\tfrac{1}{2}r^2\\theta$ with $r = 6$"),
              A1("$\\tfrac{1}{2}(36)\\cdot\\tfrac{\\pi}{3}$"),
              A1("area $= 6\\pi$ cm$^2$")],
             answer="$6\\pi$ cm$^2$",
             solution=("$$\\text{Sector} = \\tfrac{1}{2}r^2\\theta "
                       "= \\tfrac{1}{2}(6)^2 \\cdot \\tfrac{\\pi}{3} "
                       "= \\tfrac{36\\pi}{6} = 6\\pi$$"),
             verify=["Eq(Rational(1,2)*6**2*(pi/3), 6*pi)"]),
        part("d", "Find the area of the region inside the triangle but "
             "outside the sector.", 3,
             [M1("subtract the sector from the triangle"),
              A1("$15\\sqrt{3} - 6\\pi$"),
              A1("accept exact form (cm$^2$)")],
             answer="$(15\\sqrt{3} - 6\\pi)$ cm$^2$",
             solution=("The required region is the triangle with the sector "
                       "removed:"
                       "$$15\\sqrt{3} - 6\\pi \\text{ cm}^2.$$"),
             verify=["Eq(15*sqrt(3) - 6*pi, 15*sqrt(3) - 6*pi)",
                     "15*sqrt(3) - 6*pi > 0"]),
    ]))

# ── Q8 [12] stats_probability (Section B): discrete random variable ──────
# P(X = x) = k*x for x = 1,2,3,4
k = Rational(1, 10)
assert sum(k * xx for xx in (1, 2, 3, 4)) == 1
EX = sum(xx * k * xx for xx in (1, 2, 3, 4))
assert EX == 3
assert (3 + 4) * k == Rational(7, 10)
assert (4 * k)**2 == Rational(4, 25)
QS.append(question(
    "IB-AASL-P1-T2-Q8", 8, "B", "stats_probability", "discrete_random_variables",
    contextIntro=("A discrete random variable $X$ has probability "
                  "distribution $P(X = x) = kx$ for $x = 1, 2, 3, 4$, where "
                  "$k$ is a constant."),
    parts=[
        part("a", "Show that $k = \\dfrac{1}{10}$.", 3,
             [M1("use $\\sum P(X = x) = 1$"),
              A1("$k(1 + 2 + 3 + 4) = 10k = 1$"),
              AG("$k = \\tfrac{1}{10}$")],
             answer="$k = \\dfrac{1}{10}$",
             solution=("**Plan:** the probabilities must sum to 1."
                       "$$\\sum_{x=1}^{4} kx = k(1 + 2 + 3 + 4) = 10k = 1$$"
                       "$$\\Rightarrow k = \\tfrac{1}{10}$$"),
             verify=["Eq(10*Rational(1,10), 1)"]),
        part("b", "Find $E(X)$.", 4,
             [M1("use $E(X) = \\sum x\\,P(X = x)$"),
              A1("$\\sum x \\cdot \\tfrac{x}{10} = \\tfrac{1 + 4 + 9 + 16}{10}$"),
              A1("$= \\tfrac{30}{10}$"),
              A1("$E(X) = 3$")],
             answer="$E(X) = 3$",
             solution=("$$E(X) = \\sum x P(X = x) "
                       "= \\frac{1(1) + 2(2) + 3(3) + 4(4)}{10} "
                       "= \\frac{30}{10} = 3$$"),
             verify=["Eq((1*1 + 2*2 + 3*3 + 4*4)*Rational(1,10), 3)"]),
        part("c", "Find $P(X > 2)$.", 2,
             [M1("$P(X > 2) = P(X = 3) + P(X = 4)$"),
              A1("$= \\tfrac{3}{10} + \\tfrac{4}{10} = \\dfrac{7}{10}$")],
             answer="$\\dfrac{7}{10}$",
             solution=("$$P(X > 2) = P(3) + P(4) = \\tfrac{3}{10} + "
                       "\\tfrac{4}{10} = \\tfrac{7}{10}$$"),
             verify=["Eq((3 + 4)*Rational(1,10), Rational(7,10))"]),
        part("d", "Two independent observations of $X$ are made. Find the "
             "probability that both equal $4$.", 3,
             [M1("$P(X = 4) = \\tfrac{4}{10}$"),
              M1("square it by independence"),
              A1("$\\left(\\tfrac{4}{10}\\right)^2 = \\dfrac{4}{25}$")],
             answer="$\\dfrac{4}{25}$",
             solution=("$P(X = 4) = \\tfrac{4}{10} = \\tfrac{2}{5}$. For two "
                       "independent observations,"
                       "$$P(\\text{both } 4) = \\left(\\tfrac{2}{5}\\right)^2 "
                       "= \\tfrac{4}{25}.$$"),
             verify=["Eq((4*Rational(1,10))**2, Rational(4,25))"]),
    ]))

# ── Q9 [15] calculus (Section B): cubic, region, tangent, FIGURE ─────────
f9 = x**3 - 6 * x**2 + 9 * x
assert diff(f9, x) == 3 * x**2 - 12 * x + 9
assert f9.subs(x, 1) == 4 and f9.subs(x, 3) == 0
assert integrate(f9, (x, 0, 3)) == Rational(27, 4)
assert f9.subs(x, 2) == 2 and diff(f9, x).subs(x, 2) == -3
QS.append(question(
    "IB-AASL-P1-T2-Q9", 9, "B", "calculus", "integration_area",
    contextIntro=("The curve $C$ has equation $y = x^3 - 6x^2 + 9x$. The "
                  "region $R$ is bounded by $C$ and the $x$-axis between "
                  "$x = 0$ and $x = 3$, as shaded."),
    figure=png("ib-aasl-p1-t2-q9.png",
               "Cubic curve y = x^3 - 6x^2 + 9x with a local maximum near "
               "(1, 4); the region R between the curve and the x-axis on "
               "0 <= x <= 3 is shaded."),
    parts=[
        part("a", "Find $\\dfrac{dy}{dx}$.", 2,
             [M1("differentiate term by term"),
              A1("$\\dfrac{dy}{dx} = 3x^2 - 12x + 9$")],
             answer="$\\dfrac{dy}{dx} = 3x^2 - 12x + 9$",
             solution=("$$\\frac{dy}{dx} = 3x^2 - 12x + 9$$"),
             verify=["Eq(diff(x**3 - 6*x**2 + 9*x, x), 3*x**2 - 12*x + 9)"]),
        part("b", "Find the coordinates of the local maximum of $C$.", 4,
             [M1("set $\\tfrac{dy}{dx} = 0$: $3(x - 1)(x - 3) = 0$"),
              A1("$x = 1$ or $x = 3$"),
              R1("the local maximum is at the smaller root $x = 1$"),
              A1("$(1, 4)$")],
             answer="$(1, 4)$",
             solution=("**Plan:** stationary points where the derivative is 0."
                       "$$3x^2 - 12x + 9 = 3(x - 1)(x - 3) = 0 "
                       "\\Rightarrow x = 1 \\text{ or } x = 3$$"
                       "The cubic rises then falls then rises, so the local "
                       "maximum is at $x = 1$: $y = 1 - 6 + 9 = 4$, giving "
                       "$(1, 4)$."),
             verify=["Eq(3*1**2 - 12*1 + 9, 0)", "Eq(1**3 - 6*1**2 + 9*1, 4)"]),
        part("c", "Show that the area of the region $R$ is $\\dfrac{27}{4}$.", 5,
             [M1("set up the integral $\\int_0^3 (x^3 - 6x^2 + 9x)\\,dx$"),
              A1("antiderivative $\\tfrac{x^4}{4} - 2x^3 + \\tfrac{9x^2}{2}$"),
              M1("evaluate at the limits $0$ and $3$"),
              A1("$\\tfrac{81}{4} - 54 + \\tfrac{81}{2}$"),
              AG("$= \\tfrac{27}{4}$")],
             answer="area $= \\dfrac{27}{4}$",
             solution=("The curve is above the axis on $[0, 3]$, so"
                       "$$\\int_0^3 (x^3 - 6x^2 + 9x)\\,dx "
                       "= \\left[\\tfrac{x^4}{4} - 2x^3 + \\tfrac{9x^2}{2}"
                       "\\right]_0^3$$"
                       "$$= \\tfrac{81}{4} - 54 + \\tfrac{81}{2} "
                       "= \\tfrac{81 - 216 + 162}{4} = \\tfrac{27}{4}.$$"),
             verify=["Eq(integrate(x**3 - 6*x**2 + 9*x, (x, 0, 3)), Rational(27,4))"]),
        part("d", "Find the equation of the tangent to $C$ at the point "
             "where $x = 2$.", 4,
             [M1("find the gradient $\\tfrac{dy}{dx}$ at $x = 2$"),
              A1("gradient $= 3(4) - 24 + 9 = -3$; point $(2, 2)$"),
              M1("use $y - y_1 = m(x - x_1)$"),
              A1("$y = -3x + 8$")],
             answer="$y = -3x + 8$",
             solution=("At $x = 2$: $y = 8 - 24 + 18 = 2$ and the gradient is "
                       "$\\tfrac{dy}{dx} = 3(2)^2 - 12(2) + 9 = -3$. The tangent "
                       "is"
                       "$$y - 2 = -3(x - 2) \\Rightarrow y = -3x + 8.$$"),
             verify=["Eq(1*2**3 - 6*2**2 + 9*2, 2)",
                     "Eq(3*2**2 - 12*2 + 9, -3)"]),
    ]))

META = {"course": "aa", "level": "sl", "paper": 1, "testId": "ib-practice-2",
        "label": "AA SL Practice Paper 1", "timeMinutes": 90,
        "totalMarks": 80, "calculator": False}

if __name__ == "__main__":
    write_paper(META, QS, "data/ib/aa-sl/ib-practice-2/paper1.json")
