"""AA SL Practice Paper 1 (ib-practice-4) — 90 min, 80 marks, NO calculator.

Blueprint (topic x marks):
    Section A (40): Q1 number_algebra 5 | Q2 stats_probability 5
                    Q3 functions 6      | Q4 geometry_trig 6
                    Q5 number_algebra 8 | Q6 calculus 10
    Section B (40): Q7 geometry_trig 13 | Q8 stats_probability 12
                    Q9 calculus 15
    Paper totals: number_algebra 13 | functions 6 | geometry_trig 19 |
                  stats_probability 17 | calculus 25 = 80.

Every answer exact (fractions, surds, multiples of pi). Archetypes fresh
versus practice 1-3: infinite geometric series, set independence via a
Venn identity, completing the square, double-angle exact values, binomial
expansion with an approximation, product-rule stationary points, a
3-4-5 cuboid (space diagonal, exact 45-degree angle, volume, surface
area), a discrete probability distribution, and total signed area under a
cubic. Figures: Q7 (cuboid), Q9 (cubic with shaded region) generated by
scripts/test-figures/ib-aa-sl-practice-4.py from the SAME parameters.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ibbuild import ROOT, A1, AG, M1, R1, part, question, write_paper  # noqa: E402

from sympy import (Rational, sqrt, pi, Eq, simplify, expand, diff,  # noqa: F401,E402
                   integrate, sin, cos, atan, binomial, symbols)

x = symbols("x")


def png(name, alt_en):
    from PIL import Image
    p = os.path.join(ROOT, "public", "ib-figures", name)
    assert os.path.isfile(p), f"figure missing on disk: {p} — run the figure script first"
    with Image.open(p) as im_:
        w, h = im_.size
    return {"src": f"/ib-figures/{name}", "width": w, "height": h, "alt_en": alt_en}


QS = []

# ── Q1 [5] number_algebra: infinite geometric series ─────────────────────
u1, r = 12, Rational(1, 3)
assert u1 * r ** 2 == Rational(4, 3)
assert u1 / (1 - r) == 18
QS.append(question(
    "IB-AASL-P1-T4-Q1", 1, "A", "number_algebra", "geometric_series",
    contextIntro=("A geometric sequence has first term $u_1 = 12$ and common"
                  " ratio $r = \\dfrac{1}{3}$."),
    parts=[
        part("a", "Find $u_3$.", 2,
             [M1("use $u_n = u_1 r^{\\,n-1}$"),
              A1("$u_3 = 12\\left(\\tfrac{1}{3}\\right)^2 = \\tfrac{4}{3}$")],
             answer="$u_3 = \\dfrac{4}{3}$",
             solution=("$$u_3 = 12\\left(\\frac{1}{3}\\right)^{2} "
                       "= \\frac{12}{9} = \\frac{4}{3}.$$"),
             verify=["Eq(12*Rational(1, 3)**2, Rational(4, 3))"]),
        part("b", "Find the sum to infinity of the sequence.", 3,
             [M1("use $S_\\infty = \\dfrac{u_1}{1 - r}$ (valid since "
                 "$|r| < 1$)"),
              A1("$\\dfrac{12}{1 - \\tfrac{1}{3}}$"),
              A1("$S_\\infty = 18$")],
             answer="$S_\\infty = 18$",
             solution=("Since $|r| = \\tfrac13 < 1$ the series converges:"
                       "$$S_\\infty = \\frac{u_1}{1 - r} = "
                       "\\frac{12}{1 - \\tfrac13} = \\frac{12}{\\tfrac23} "
                       "= 18.$$"),
             verify=["Eq(12/(1 - Rational(1, 3)), 18)"]),
    ]))

# ── Q2 [5] stats_probability: independence via a set identity ────────────
pA, pB, pAuB = Rational(1, 2), Rational(2, 5), Rational(7, 10)
pAnB = pA + pB - pAuB
assert pAnB == Rational(1, 5)
assert pA * pB == Rational(1, 5)
QS.append(question(
    "IB-AASL-P1-T4-Q2", 2, "A", "stats_probability", "set_probability",
    contextIntro=("For two events $A$ and $B$, $P(A) = \\dfrac{1}{2}$, "
                  "$P(B) = \\dfrac{2}{5}$ and "
                  "$P(A \\cup B) = \\dfrac{7}{10}$."),
    parts=[
        part("a", "Find $P(A \\cap B)$.", 2,
             [M1("use $P(A \\cup B) = P(A) + P(B) - P(A \\cap B)$"),
              A1("$P(A \\cap B) = \\dfrac{1}{5}$")],
             answer="$P(A \\cap B) = \\dfrac{1}{5}$",
             solution=("$$P(A \\cap B) = P(A) + P(B) - P(A \\cup B) "
                       "= \\frac12 + \\frac25 - \\frac{7}{10} "
                       "= \\frac{1}{5}.$$"),
             verify=["Eq(Rational(1, 2) + Rational(2, 5) - Rational(7, 10),"
                     " Rational(1, 5))"]),
        part("b", "Determine whether $A$ and $B$ are independent, justifying"
             " your answer.", 3,
             [M1("compute $P(A)\\,P(B) = \\tfrac12 \\cdot \\tfrac25$"),
              A1("$P(A)P(B) = \\dfrac{1}{5}$"),
              R1("since $P(A \\cap B) = P(A)P(B)$, the events ARE "
                 "independent")],
             answer="independent, since $P(A \\cap B) = P(A)P(B) = "
                    "\\dfrac{1}{5}$",
             solution=("$A$ and $B$ are independent exactly when "
                       "$P(A \\cap B) = P(A)P(B)$. Here"
                       "$$P(A)P(B) = \\frac12 \\cdot \\frac25 = \\frac15 "
                       "= P(A \\cap B),$$ so the events are independent."),
             verify=["Eq(Rational(1, 2)*Rational(2, 5), Rational(1, 5))"]),
    ]))

# ── Q3 [6] functions: completing the square ──────────────────────────────
assert expand((x - 3) ** 2 - 4) == x ** 2 - 6 * x + 5
assert set(__import__("sympy").solve(Eq(x ** 2 - 6 * x + 5, 0), x)) == {1, 5}
QS.append(question(
    "IB-AASL-P1-T4-Q3", 3, "A", "functions", "quadratic_functions",
    contextIntro=("The function $f$ is defined by $f(x) = x^2 - 6x + 5$."),
    parts=[
        part("a", "Write $f(x)$ in the form $(x - h)^2 + k$.", 3,
             [M1("complete the square: half of $-6$ is $-3$"),
              A1("$(x - 3)^2$ with a correction of $-9$"),
              A1("$f(x) = (x - 3)^2 - 4$")],
             answer="$f(x) = (x - 3)^2 - 4$",
             solution=("$$f(x) = x^2 - 6x + 5 = (x - 3)^2 - 9 + 5 "
                       "= (x - 3)^2 - 4.$$"),
             verify=["Eq(expand((x - 3)**2 - 4), x**2 - 6*x + 5)"]),
        part("b", "Hence write down the coordinates of the vertex of the"
             " graph of $f$, and find the $x$-intercepts.", 3,
             [A1("vertex $(3, -4)$"),
              M1("solve $(x - 3)^2 = 4$, i.e. $x - 3 = \\pm 2$"),
              A1("$x = 1$ and $x = 5$")],
             answer="vertex $(3, -4)$; $x$-intercepts $x = 1$ and $x = 5$",
             solution=("The vertex form gives the minimum point $(3, -4)$. "
                       "Setting $f(x) = 0$:"
                       "$$(x - 3)^2 = 4 \\Rightarrow x - 3 = \\pm 2 "
                       "\\Rightarrow x = 1 \\text{ or } x = 5.$$"),
             verify=["Eq(1**2 - 6*1 + 5, 0)", "Eq(5**2 - 6*5 + 5, 0)"]),
    ]))

# ── Q4 [6] geometry_trig: double-angle exact values ──────────────────────
assert sqrt(1 - Rational(9, 25)) == Rational(4, 5)
assert 2 * Rational(4, 5) * Rational(3, 5) == Rational(24, 25)
assert 2 * Rational(3, 5) ** 2 - 1 == Rational(-7, 25)
QS.append(question(
    "IB-AASL-P1-T4-Q4", 4, "A", "geometry_trig", "double_angle",
    contextIntro=("The angle $\\theta$ is acute and $\\cos\\theta "
                  "= \\dfrac{3}{5}$."),
    parts=[
        part("a", "Find $\\sin\\theta$.", 2,
             [M1("use $\\sin^2\\theta + \\cos^2\\theta = 1$"),
              A1("$\\sin\\theta = \\dfrac{4}{5}$ (positive, as $\\theta$ is "
                 "acute)")],
             answer="$\\sin\\theta = \\dfrac{4}{5}$",
             solution=("$$\\sin\\theta = \\sqrt{1 - \\left(\\tfrac35\\right)^2}"
                       " = \\sqrt{\\tfrac{16}{25}} = \\frac{4}{5}.$$"),
             verify=["Eq(sqrt(1 - Rational(9, 25)), Rational(4, 5))"]),
        part("b", "Find $\\sin 2\\theta$.", 2,
             [M1("use $\\sin 2\\theta = 2\\sin\\theta\\cos\\theta$"),
              A1("$\\sin 2\\theta = \\dfrac{24}{25}$")],
             answer="$\\sin 2\\theta = \\dfrac{24}{25}$",
             solution=("$$\\sin 2\\theta = 2\\sin\\theta\\cos\\theta "
                       "= 2 \\cdot \\frac45 \\cdot \\frac35 = "
                       "\\frac{24}{25}.$$"),
             verify=["Eq(2*Rational(4, 5)*Rational(3, 5), Rational(24, 25))"]),
        part("c", "Find $\\cos 2\\theta$.", 2,
             [M1("use $\\cos 2\\theta = 2\\cos^2\\theta - 1$"),
              A1("$\\cos 2\\theta = -\\dfrac{7}{25}$")],
             answer="$\\cos 2\\theta = -\\dfrac{7}{25}$",
             solution=("$$\\cos 2\\theta = 2\\cos^2\\theta - 1 = "
                       "2 \\cdot \\frac{9}{25} - 1 = \\frac{18}{25} - "
                       "\\frac{25}{25} = -\\frac{7}{25}.$$"),
             verify=["Eq(2*Rational(3, 5)**2 - 1, Rational(-7, 25))"]),
    ]))

# ── Q5 [8] number_algebra: binomial expansion + approximation ────────────
assert binomial(6, 1) * 2 == 12
assert binomial(6, 2) * 2 ** 2 == 60
assert binomial(6, 3) * 2 ** 3 == 160
assert 1 + Rational(12, 100) + Rational(60, 10000) == Rational(1126, 1000)
QS.append(question(
    "IB-AASL-P1-T4-Q5", 5, "A", "number_algebra", "binomial_theorem",
    contextIntro=("Consider the binomial expansion of $(1 + 2x)^6$."),
    parts=[
        part("a", "Find the first three terms of the expansion, in ascending"
             " powers of $x$.", 3,
             [M1("apply the binomial theorem with terms "
                 "$\\binom{6}{k}(2x)^k$"),
              A1("$\\binom{6}{1}(2x) = 12x$"),
              A1("$1 + 12x + 60x^2$")],
             answer="$1 + 12x + 60x^2$",
             solution=("$$(1 + 2x)^6 = 1 + \\binom{6}{1}(2x) + "
                       "\\binom{6}{2}(2x)^2 + \\cdots = 1 + 12x + 60x^2 "
                       "+ \\cdots$$"),
             verify=["Eq(binomial(6, 1)*2, 12)",
                     "Eq(binomial(6, 2)*2**2, 60)"]),
        part("b", "Find the coefficient of $x^3$ in the expansion.", 3,
             [M1("the $x^3$ term is $\\binom{6}{3}(2x)^3$"),
              A1("$\\binom{6}{3} = 20$ and $(2)^3 = 8$"),
              A1("coefficient $= 160$")],
             answer="$160$",
             solution=("$$\\binom{6}{3}(2x)^3 = 20 \\cdot 8x^3 = 160x^3,$$"
                       " so the coefficient is $160$."),
             verify=["Eq(binomial(6, 3)*2**3, 160)"]),
        part("c", "By substituting a suitable value of $x$ into the first"
             " three terms, estimate $(1.02)^6$.", 2,
             [M1("set $2x = 0.02$, i.e. $x = 0.01$"),
              A1("$1 + 12(0.01) + 60(0.01)^2 = 1.126$")],
             answer="$(1.02)^6 \\approx 1.126$",
             solution=("With $x = 0.01$ the first three terms give"
                       "$$1 + 12(0.01) + 60(0.01)^2 = 1 + 0.12 + 0.006 "
                       "= 1.126.$$"),
             verify=["Eq(1 + Rational(12, 100) + Rational(60, 10000),"
                     " Rational(1126, 1000))"]),
    ]))

# ── Q6 [10] calculus: product rule, stationary points, tangent ───────────
f6 = x ** 3 - 3 * x ** 2
assert expand(diff(f6, x)) == 3 * x ** 2 - 6 * x
assert f6.subs(x, 0) == 0 and f6.subs(x, 2) == -4
assert f6.subs(x, 1) == -2 and diff(f6, x).subs(x, 1) == -3
assert expand(diff(f6, x, 2)) == 6 * x - 6
QS.append(question(
    "IB-AASL-P1-T4-Q6", 6, "A", "calculus", "differentiation_applications",
    contextIntro=("The function $f$ is defined by $f(x) = x^3 - 3x^2$."),
    parts=[
        part("a", "Find $f'(x)$.", 2,
             [M1("differentiate term by term"),
              A1("$f'(x) = 3x^2 - 6x$")],
             answer="$f'(x) = 3x^2 - 6x$",
             solution=("$$f'(x) = 3x^2 - 6x.$$"),
             verify=["Eq(expand(diff(x**3 - 3*x**2, x)), 3*x**2 - 6*x)"]),
        part("b", "Find the coordinates of the two stationary points of the"
             " graph of $f$.", 3,
             [M1("solve $f'(x) = 0$: $3x(x - 2) = 0$"),
              A1("$x = 0$ and $x = 2$"),
              A1("$(0, 0)$ and $(2, -4)$")],
             answer="$(0, 0)$ and $(2, -4)$",
             solution=("$$3x(x - 2) = 0 \\Rightarrow x = 0 \\text{ or } "
                       "x = 2.$$"
                       "$$f(0) = 0, \\qquad f(2) = 8 - 12 = -4.$$"),
             verify=["Eq(0**3 - 3*0**2, 0)", "Eq(2**3 - 3*2**2, -4)"]),
        part("c", "Find the equation of the tangent to the graph of $f$ at"
             " the point where $x = 1$.", 2,
             [M1("gradient $f'(1) = -3$ and point $(1, -2)$"),
              A1("$y = -3x + 1$")],
             answer="$y = -3x + 1$",
             solution=("At $x = 1$: $f(1) = -2$ and $f'(1) = 3 - 6 = -3$, so"
                       "$$y - (-2) = -3(x - 1) \\Rightarrow y = -3x + 1.$$"),
             verify=["Eq(1**3 - 3*1**2, -2)",
                     "Eq(diff(x**3 - 3*x**2, x).subs(x, 1), -3)",
                     "Eq(-3*1 + 1, -2)"]),
        part("d", "Determine the nature of each stationary point.", 3,
             [M1("find $f''(x) = 6x - 6$"),
              A1("$f''(0) = -6 < 0 \\Rightarrow (0, 0)$ is a local maximum"),
              A1("$f''(2) = 6 > 0 \\Rightarrow (2, -4)$ is a local minimum")],
             answer="$(0, 0)$ maximum; $(2, -4)$ minimum",
             solution=("$$f''(x) = 6x - 6.$$"
                       "$$f''(0) = -6 < 0 \\Rightarrow (0, 0)\\text{ is a "
                       "maximum};$$"
                       "$$f''(2) = 6 > 0 \\Rightarrow (2, -4)\\text{ is a "
                       "minimum}.$$"),
             verify=["Eq(expand(diff(x**3 - 3*x**2, x, 2)), 6*x - 6)",
                     "Eq((6*x - 6).subs(x, 0), -6)",
                     "Eq((6*x - 6).subs(x, 2), 6)"]),
    ]))

# ── Q7 [13] geometry_trig (Section B): 3-4-5 cuboid, FIGURE ──────────────
assert sqrt(3 ** 2 + 4 ** 2) == 5
assert sqrt(5 ** 2 + 5 ** 2) == 5 * sqrt(2)
assert atan(Rational(5, 5)) == pi / 4
assert 3 * 4 * 5 == 60
assert 2 * (3 * 4 + 4 * 5 + 3 * 5) == 94
QS.append(question(
    "IB-AASL-P1-T4-Q7", 7, "B", "geometry_trig", "solid_geometry",
    contextIntro=("The diagram shows a cuboid $ABCDEFGH$ with"
                  " $AB = 3$ cm, $BC = 4$ cm and $CG = 5$ cm. The base"
                  " $ABCD$ is horizontal and $G$ is the vertex above $C$."),
    figure=png("ib-aasl-p1-t4-q7.png",
               "Cuboid ABCDEFGH with base edges AB = 3 and BC = 4 and "
               "vertical edge CG = 5; the space diagonal from A to G is "
               "drawn, together with the base diagonal AC."),
    parts=[
        part("a", "Find the length of the base diagonal $AC$.", 2,
             [M1("apply Pythagoras in the base: $AC^2 = 3^2 + 4^2$"),
              A1("$AC = 5$ cm")],
             answer="$AC = 5$ cm",
             solution=("$$AC = \\sqrt{3^2 + 4^2} = \\sqrt{25} = 5 "
                       "\\text{ cm}.$$"),
             verify=["Eq(sqrt(3**2 + 4**2), 5)"]),
        part("b", "Find the length of the space diagonal $AG$, giving your"
             " answer in the form $a\\sqrt{2}$.", 3,
             [M1("$AG^2 = AC^2 + CG^2 = 5^2 + 5^2$"),
              A1("$AG = \\sqrt{50}$"),
              A1("$AG = 5\\sqrt{2}$ cm")],
             answer="$AG = 5\\sqrt{2}$ cm",
             solution=("Triangle $ACG$ is right-angled at $C$:"
                       "$$AG = \\sqrt{AC^2 + CG^2} = \\sqrt{25 + 25} "
                       "= \\sqrt{50} = 5\\sqrt{2} \\text{ cm}.$$"),
             verify=["Eq(sqrt(5**2 + 5**2), 5*sqrt(2))"]),
        part("c", "Show that the angle $G\\hat{A}C$ between the space"
             " diagonal $AG$ and the base is $45^\\circ$.", 3,
             [M1("in right triangle $ACG$, $\\tan(G\\hat{A}C) = "
                 "\\dfrac{CG}{AC}$"),
              A1("$\\tan(G\\hat{A}C) = \\dfrac{5}{5} = 1$"),
              AG("$G\\hat{A}C = 45^\\circ$")],
             answer="$G\\hat{A}C = 45^\\circ$",
             solution=("$$\\tan(G\\hat{A}C) = \\frac{CG}{AC} = \\frac{5}{5} "
                       "= 1 \\Rightarrow G\\hat{A}C = 45^\\circ.$$"),
             verify=["Eq(atan(Rational(5, 5)), pi/4)"]),
        part("d", "Find the volume of the cuboid.", 2,
             [M1("volume $= 3 \\times 4 \\times 5$"),
              A1("$60$ cm$^3$")],
             answer="$60$ cm$^3$",
             solution=("$$V = 3 \\times 4 \\times 5 = 60 \\text{ cm}^3.$$"),
             verify=["Eq(3*4*5, 60)"]),
        part("e", "Find the total surface area of the cuboid.", 3,
             [M1("sum the three distinct face areas $12, 20, 15$"),
              A1("$2(12 + 20 + 15)$"),
              A1("$94$ cm$^2$")],
             answer="$94$ cm$^2$",
             solution=("The three pairs of faces have areas $3 \\times 4 = "
                       "12$, $4 \\times 5 = 20$, $3 \\times 5 = 15$:"
                       "$$S = 2(12 + 20 + 15) = 2(47) = 94 \\text{ cm}^2.$$"),
             verify=["Eq(2*(3*4 + 4*5 + 3*5), 94)"]),
    ]))

# ── Q8 [12] stats_probability (Section B): discrete distribution ─────────
p0, p2, p3 = Rational(1, 10), Rational(3, 10), Rational(2, 10)
k8 = 1 - p0 - p2 - p3
assert k8 == Rational(2, 5)
E8 = 0 * p0 + 1 * k8 + 2 * p2 + 3 * p3
assert E8 == Rational(8, 5)
EX2 = 0 * p0 + 1 * k8 + 4 * p2 + 9 * p3
assert EX2 == Rational(17, 5)
Var8 = EX2 - E8 ** 2
assert Var8 == Rational(21, 25)
assert p2 + p3 == Rational(1, 2)
QS.append(question(
    "IB-AASL-P1-T4-Q8", 8, "B", "stats_probability", "discrete_random_variable",
    contextIntro=("A discrete random variable $X$ has the probability"
                  " distribution shown, where $k$ is a constant:"
                  " $P(X = 0) = \\dfrac{1}{10}$, $P(X = 1) = k$,"
                  " $P(X = 2) = \\dfrac{3}{10}$,"
                  " $P(X = 3) = \\dfrac{2}{10}$."),
    parts=[
        part("a", "Find the value of $k$.", 2,
             [M1("the probabilities sum to 1"),
              A1("$k = \\dfrac{2}{5}$")],
             answer="$k = \\dfrac{2}{5}$",
             solution=("$$\\frac{1}{10} + k + \\frac{3}{10} + \\frac{2}{10} "
                       "= 1 \\Rightarrow k = 1 - \\frac{6}{10} = "
                       "\\frac{2}{5}.$$"),
             verify=["Eq(Rational(1,10) + Rational(2,5) + Rational(3,10)"
                     " + Rational(2,10), 1)"]),
        part("b", "Find $E(X)$.", 3,
             [M1("use $E(X) = \\sum x\\,P(X = x)$"),
              A1("$0 + \\tfrac25 + \\tfrac{6}{10} + \\tfrac{6}{10}$"),
              A1("$E(X) = \\dfrac{8}{5}$")],
             answer="$E(X) = \\dfrac{8}{5}$",
             solution=("$$E(X) = 1\\cdot\\frac25 + 2\\cdot\\frac{3}{10} + "
                       "3\\cdot\\frac{2}{10} = \\frac{4}{10} + \\frac{6}{10}"
                       " + \\frac{6}{10} = \\frac{16}{10} = \\frac{8}{5}.$$"),
             verify=["Eq(1*Rational(2,5) + 2*Rational(3,10) + "
                     "3*Rational(2,10), Rational(8,5))"]),
        part("c", "Find $\\operatorname{Var}(X)$.", 3,
             [M1("$E(X^2) = \\tfrac25 + 4\\cdot\\tfrac{3}{10} + "
                 "9\\cdot\\tfrac{2}{10} = \\tfrac{17}{5}$"),
              M1("$\\operatorname{Var}(X) = E(X^2) - [E(X)]^2$"),
              A1("$\\operatorname{Var}(X) = \\dfrac{21}{25}$")],
             answer="$\\operatorname{Var}(X) = \\dfrac{21}{25}$",
             solution=("$$E(X^2) = 1\\cdot\\frac25 + 4\\cdot\\frac{3}{10} + "
                       "9\\cdot\\frac{2}{10} = \\frac{17}{5}.$$"
                       "$$\\operatorname{Var}(X) = \\frac{17}{5} - "
                       "\\left(\\frac85\\right)^2 = \\frac{85}{25} - "
                       "\\frac{64}{25} = \\frac{21}{25}.$$"),
             verify=["Eq(1*Rational(2,5) + 4*Rational(3,10) + "
                     "9*Rational(2,10), Rational(17,5))",
                     "Eq(Rational(17,5) - Rational(8,5)**2, Rational(21,25))"]),
        part("d", "Find $P(X \\ge 2)$.", 2,
             [M1("add $P(X = 2)$ and $P(X = 3)$"),
              A1("$P(X \\ge 2) = \\dfrac{1}{2}$")],
             answer="$\\dfrac{1}{2}$",
             solution=("$$P(X \\ge 2) = \\frac{3}{10} + \\frac{2}{10} "
                       "= \\frac{5}{10} = \\frac{1}{2}.$$"),
             verify=["Eq(Rational(3,10) + Rational(2,10), Rational(1,2))"]),
        part("e", "Write down the mode of $X$.", 2,
             [M1("identify the value with the greatest probability"),
              A1("mode $= 1$ (probability $\\tfrac25$)")],
             answer="mode $= 1$",
             solution=("The largest probability is $k = \\tfrac25$, at "
                       "$X = 1$, so the mode is $1$."),
             verify=["Rational(2, 5) > Rational(3, 10)"]),
    ]))

# ── Q9 [15] calculus (Section B): total area under a cubic, FIGURE ───────
f9 = x ** 3 - 3 * x ** 2 + 2 * x
assert expand(x * (x - 1) * (x - 2)) == f9
assert expand(diff(f9, x)) == 3 * x ** 2 - 6 * x + 2
assert f9.subs(x, 1) == 0 and diff(f9, x).subs(x, 1) == -1
a01 = integrate(f9, (x, 0, 1))
a12 = integrate(f9, (x, 1, 2))
assert a01 == Rational(1, 4) and a12 == Rational(-1, 4)
assert a01 - a12 == Rational(1, 2)
QS.append(question(
    "IB-AASL-P1-T4-Q9", 9, "B", "calculus", "integration_area",
    contextIntro=("The diagram shows part of the graph of "
                  "$f(x) = x^3 - 3x^2 + 2x$."),
    figure=png("ib-aasl-p1-t4-q9.png",
               "Cubic curve y = x^3 - 3x^2 + 2x crossing the x-axis at 0, 1 "
               "and 2; the region between the curve and the x-axis from x = 0 "
               "to x = 2 is shaded, lying above the axis on (0,1) and below "
               "it on (1,2)."),
    parts=[
        part("a", "Show that $f(x) = x(x - 1)(x - 2)$.", 2,
             [M1("expand the product $x(x - 1)(x - 2)$"),
              AG("$= x^3 - 3x^2 + 2x$")],
             answer="$f(x) = x(x - 1)(x - 2)$",
             solution=("$$x(x - 1)(x - 2) = x(x^2 - 3x + 2) = "
                       "x^3 - 3x^2 + 2x = f(x).$$"),
             verify=["Eq(expand(x*(x - 1)*(x - 2)), x**3 - 3*x**2 + 2*x)"]),
        part("b", "Write down the $x$-intercepts of the graph and find"
             " $f'(x)$.", 3,
             [A1("intercepts $x = 0, 1, 2$"),
              M1("differentiate term by term"),
              A1("$f'(x) = 3x^2 - 6x + 2$")],
             answer="intercepts $0, 1, 2$; $f'(x) = 3x^2 - 6x + 2$",
             solution=("From the factored form the intercepts are "
                       "$x = 0, 1, 2$, and"
                       "$$f'(x) = 3x^2 - 6x + 2.$$"),
             verify=["Eq(expand(diff(x**3 - 3*x**2 + 2*x, x)),"
                     " 3*x**2 - 6*x + 2)"]),
        part("c", "Find the equation of the tangent to the curve at the"
             " point where $x = 1$.", 3,
             [M1("gradient $f'(1) = 3 - 6 + 2 = -1$"),
              A1("point $(1, 0)$"),
              A1("$y = -x + 1$")],
             answer="$y = -x + 1$",
             solution=("At $x = 1$: $f(1) = 0$ and $f'(1) = -1$, so"
                       "$$y - 0 = -1(x - 1) \\Rightarrow y = -x + 1.$$"),
             verify=["Eq((x**3 - 3*x**2 + 2*x).subs(x, 1), 0)",
                     "Eq(diff(x**3 - 3*x**2 + 2*x, x).subs(x, 1), -1)"]),
        part("d", "Find $\\displaystyle\\int_0^1 f(x)\\,dx$.", 3,
             [M1("antiderivative $\\tfrac{x^4}{4} - x^3 + x^2$"),
              M1("evaluate between $0$ and $1$"),
              A1("$\\dfrac{1}{4}$")],
             answer="$\\dfrac{1}{4}$",
             solution=("$$\\int_0^1 (x^3 - 3x^2 + 2x)\\,dx = "
                       "\\left[\\frac{x^4}{4} - x^3 + x^2\\right]_0^1 = "
                       "\\frac14 - 1 + 1 = \\frac14.$$"),
             verify=["Eq(integrate(x**3 - 3*x**2 + 2*x, (x, 0, 1)),"
                     " Rational(1, 4))"]),
        part("e", "Hence find the total area enclosed between the curve and"
             " the $x$-axis for $0 \\le x \\le 2$.", 4,
             [M1("recognise the curve is BELOW the axis on $(1, 2)$"),
              M1("$\\displaystyle\\int_1^2 f(x)\\,dx = -\\tfrac14$"),
              A1("area below $= \\tfrac14$"),
              A1("total area $= \\tfrac14 + \\tfrac14 = \\tfrac12$")],
             answer="total area $= \\dfrac{1}{2}$",
             solution=("On $(1, 2)$ the curve lies below the axis, and"
                       "$$\\int_1^2 f(x)\\,dx = \\left[\\frac{x^4}{4} - x^3 "
                       "+ x^2\\right]_1^2 = 0 - \\frac14 = -\\frac14,$$"
                       " so that region has area $\\tfrac14$. The total area"
                       " is"
                       "$$\\frac14 + \\frac14 = \\frac12.$$"),
             verify=["Eq(integrate(x**3 - 3*x**2 + 2*x, (x, 1, 2)),"
                     " Rational(-1, 4))",
                     "Eq(Rational(1, 4) + Rational(1, 4), Rational(1, 2))"]),
    ]))

META = {"course": "aa", "level": "sl", "paper": 1, "testId": "ib-practice-4",
        "label": "AA SL Practice Paper 1", "timeMinutes": 90,
        "totalMarks": 80, "calculator": False}

if __name__ == "__main__":
    write_paper(META, QS, "data/ib/aa-sl/ib-practice-4/paper1.json")
