"""AA SL Practice Paper 2 (ib-practice-3) — 90 min, 80 marks, GDC required.

Blueprint (topic x marks):
    Section A (40): Q1 functions 6 | Q2 stats_probability 6
                    Q3 geometry_trig 6 | Q4 number_algebra 6
                    Q5 functions 8 | Q6 calculus 8
    Section B (40): Q7 functions 13 | Q8 stats_probability 12
                    Q9 calculus 15
    Paper totals: functions 27 | stats_probability 18 | geometry_trig 6 |
                  number_algebra 6 | calculus 23 = 80.

Fresh archetypes versus practice 1-2: least-squares regression, 3-D
pyramid trigonometry, salary-scheme comparison (arithmetic vs geometric),
rational-function asymptotes, open-box optimisation with an AG identity,
a projectile quadratic, normal distribution N(70, 8^2), and kinematics
with displacement vs TOTAL DISTANCE. Figures: Q3 (pyramid), Q7
(projectile parabola) — generated by
scripts/test-figures/ib-aa-sl-practice-3.py from the SAME parameters.
"""
import os
import sys
from math import floor, log10

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ibbuild import ROOT, A1, AG, M1, R1, part, question, write_paper  # noqa: E402

from sympy import (Rational, sqrt, pi, Eq, erf, erfinv, atan, deg,  # noqa: F401,E402
                   integrate, diff, expand, solve, symbols, N)

x, t = symbols("x t")


def sf3(v):
    """Round to 3 significant figures; return (printed_string, tolerance)."""
    v = float(v)
    assert v != 0
    d = 2 - floor(log10(abs(v)))
    r = round(v, d)
    printed = str(int(r)) if d <= 0 else f"{r:.{d}f}"
    assert abs(v - r) < 0.499 * 10**(-d), f"ambiguous 3sf rounding for {v}"
    return printed, 0.51 * 10**(-d)


def sig(v, n=6):
    """Quote an unrounded value to n significant figures (solution text)."""
    v = float(v)
    d = (n - 1) - floor(log10(abs(v)))
    return f"{round(v, d):.{max(d, 0)}f}"


def png(name, alt_en):
    from PIL import Image
    p = os.path.join(ROOT, "public", "ib-figures", name)
    assert os.path.isfile(p), f"figure missing on disk: {p} — run the figure script first"
    with Image.open(p) as im:
        w, h = im.size
    return {"src": f"/ib-figures/{name}", "width": w, "height": h, "alt_en": alt_en}


QS = []

# ── Q1 [6] functions: quadratic, GDC roots ───────────────────────────────
assert 2 * 3**2 - 5 * 3 - 1 == 2
r1v = (5 - sqrt(33)) / 4
r2v = (5 + sqrt(33)) / 4
r1_p, r1_tol = sf3(N(r1v, 12))
r2_p, r2_tol = sf3(N(r2v, 12))
QS.append(question(
    "IB-AASL-P2-T3-Q1", 1, "A", "functions", "quadratic_functions",
    contextIntro=("The function $f$ is given by $f(x) = 2x^2 - 5x - 1$."),
    parts=[
        part("a", "Find $f(3)$.", 2,
             [M1("substitute $x = 3$"), A1("$f(3) = 2$")],
             answer="$f(3) = 2$",
             solution=("$$f(3) = 2(9) - 15 - 1 = 2$$"),
             verify=["Eq(2*3**2 - 5*3 - 1, 2)"]),
        part("b", "Solve $f(x) = 0$, giving your answers to three "
             "significant figures.", 4,
             [M1("use the GDC (or the quadratic formula)"),
              A1("discriminant $25 + 8 = 33$"),
              A1(f"$x \\approx {r1_p}$"), A1(f"$x \\approx {r2_p}$")],
             answer=f"$x \\approx {r1_p}$ or $x \\approx {r2_p}$",
             solution=("$$x = \\frac{5 \\pm \\sqrt{25 + 8}}{4} "
                       "= \\frac{5 \\pm \\sqrt{33}}{4}$$"
                       f"$$x \\approx {r1_p} \\text{{ or }} {r2_p}$$"),
             verify=[f"Abs((5 - sqrt(33))/4 - ({r1_p})) < {r1_tol}",
                     f"Abs((5 + sqrt(33))/4 - {r2_p}) < {r2_tol}"]),
    ]))

# ── Q2 [6] stats_probability: least-squares regression ───────────────────
xs2 = [1, 2, 3, 4, 5]
ys2 = [3, 5, 6, 8, 8]
n2 = 5
sx, sy = sum(xs2), sum(ys2)
sxy = sum(a * b for a, b in zip(xs2, ys2))
sxx = sum(a * a for a in xs2)
b2 = Rational(n2 * sxy - sx * sy, n2 * sxx - sx**2)
a2 = Rational(sy, n2) - b2 * Rational(sx, n2)
assert b2 == Rational(13, 10) and a2 == Rational(21, 10)
assert b2 * 6 + a2 == Rational(99, 10)
QS.append(question(
    "IB-AASL-P2-T3-Q2", 2, "A", "stats_probability", "regression",
    contextIntro=("The table shows the number of hours $x$ that five "
                  "students revised and their quiz scores $y$: "
                  "$(1, 3)$, $(2, 5)$, $(3, 6)$, $(4, 8)$, $(5, 8)$."),
    parts=[
        part("a", "Use your GDC to find the equation of the regression "
             "line of $y$ on $x$, in the form $y = ax + b$.", 4,
             [M1("enter the data and use linear regression on the GDC"),
              A1("$a = 1.3$"),
              A1("$b = 2.1$"),
              A1("$y = 1.3x + 2.1$")],
             answer="$y = 1.3x + 2.1$",
             solution=("**Plan:** GDC linear regression on the five pairs."
                       "$$a = \\frac{n\\sum xy - \\sum x \\sum y}"
                       "{n\\sum x^2 - (\\sum x)^2} = \\frac{515 - 450}"
                       "{275 - 225} = 1.3$$"
                       "$$b = \\bar{y} - a\\bar{x} = 6 - 1.3(3) = 2.1$$"),
             verify=["Eq(Rational(5*103 - 15*30, 5*55 - 15**2), Rational(13, 10))",
                     "Eq(Rational(30, 5) - Rational(13, 10)*Rational(15, 5), "
                     "Rational(21, 10))"]),
        part("b", "Use your regression line to estimate the quiz score of a "
             "student who revised for 6 hours.", 2,
             [M1("substitute $x = 6$"),
              A1("$y = 1.3(6) + 2.1 = 9.9$")],
             answer="$9.9$",
             solution=("$$y = 1.3(6) + 2.1 = 9.9$$"
                       "(A slight extrapolation beyond the data — acceptable "
                       "this close to the range.)"),
             verify=["Eq(Rational(13, 10)*6 + Rational(21, 10), Rational(99, 10))"]),
    ]))

# ── Q3 [6] geometry_trig: pyramid, FIGURE ────────────────────────────────
half_diag = sqrt(Rational(8, 2)**2 + Rational(6, 2)**2)
assert half_diag == 5
edge3 = sqrt(5**2 + 10**2)
edge3_p, edge3_tol = sf3(N(edge3, 12))
ang3 = atan(Rational(10, 5))
ang3_deg = N(deg(ang3), 12)
ang3_p, ang3_tol = sf3(ang3_deg)
QS.append(question(
    "IB-AASL-P2-T3-Q3", 3, "A", "geometry_trig", "three_d_trig",
    contextIntro=("The solid shown is a pyramid with a rectangular base "
                  "$ABCD$, where $AB = 8$ cm and $BC = 6$ cm. The vertex "
                  "$V$ is directly above the centre of the base, at a "
                  "height of $10$ cm."),
    figure=png("ib-aasl-p2-t3-q3.png",
               "Pyramid with rectangular base ABCD, 8 cm by 6 cm, and apex "
               "V directly above the centre of the base at height 10 cm; "
               "hidden edges dashed."),
    parts=[
        part("a", "Find the length of the edge $VA$, giving your answer to "
             "three significant figures.", 3,
             [M1("half-diagonal of the base: $\\sqrt{4^2 + 3^2} = 5$"),
              M1("right triangle with the height: $VA = \\sqrt{5^2 + 10^2}$"),
              A1(f"$VA \\approx {edge3_p}$ cm")],
             answer=f"$VA \\approx {edge3_p}$ cm (3 sf)",
             solution=("**Plan:** the centre of the base is a half-diagonal "
                       "from $A$."
                       "$$\\tfrac{1}{2}AC = \\sqrt{4^2 + 3^2} = 5$$"
                       "$$VA = \\sqrt{5^2 + 10^2} = \\sqrt{125} "
                       f"= {sig(edge3, 5)}\\ldots \\approx {edge3_p}$$"),
             verify=["Eq(sqrt(4**2 + 3**2), 5)",
                     f"Abs(sqrt(125) - {edge3_p}) < {edge3_tol}"]),
        part("b", "Find the angle that the edge $VA$ makes with the base, "
             "giving your answer to three significant figures.", 3,
             [M1("right triangle: opposite 10, adjacent 5"),
              M1("$\\tan\\theta = \\tfrac{10}{5}$"),
              A1(f"$\\theta \\approx {ang3_p}°$")],
             answer=f"$\\theta \\approx {ang3_p}°$ (3 sf)",
             solution=("The angle sits between $VA$ and its projection (the "
                       "half-diagonal):"
                       "$$\\tan\\theta = \\frac{10}{5} = 2 \\Rightarrow "
                       f"\\theta = {sig(ang3_deg, 5)}\\ldots° \\approx "
                       f"{ang3_p}°$$"),
             verify=[f"Abs(deg(atan(2)) - {ang3_p}) < {ang3_tol}"]),
    ]))

# ── Q4 [6] number_algebra: salary schemes ────────────────────────────────
optA5 = 30000 + 4 * 1200
optB5 = 28000 * Rational(105, 100)**4
assert optA5 == 34800
assert abs(float(optB5) - 34034.18) < 0.01
b5_p, b5_tol = "34034.18", 0.005
QS.append(question(
    "IB-AASL-P2-T3-Q4", 4, "A", "number_algebra", "sequences_applications",
    contextIntro=("Two salary offers both run for several years. Offer A "
                  "starts at \\$30,000 with a raise of \\$1,200 each "
                  "year. Offer B starts at \\$28,000 and increases by "
                  "5\\% each year."),
    parts=[
        part("a", "Find the salary in the 5th year under each offer, giving "
             "the Offer B amount to the nearest cent.", 4,
             [M1("Offer A is arithmetic: $30000 + 4(1200)$"),
              A1("Offer A: \\$34,800"),
              M1("Offer B is geometric: $28000(1.05)^4$"),
              A1(f"Offer B: $\\${b5_p}$")],
             answer="A: \\$34,800; B: \\$34,034.18",
             solution=("Year 5 is four steps beyond year 1."
                       "$$A_5 = 30000 + 4(1200) = 34800$$"
                       f"$$B_5 = 28000(1.05)^4 = {b5_p}$$"),
             verify=["Eq(30000 + 4*1200, 34800)",
                     f"Abs(28000*Rational(105, 100)**4 - {b5_p}) < {b5_tol}"]),
        part("b", "State which offer gives the higher salary in the 5th "
             "year, and by approximately how much.", 2,
             [R1("compare the two amounts: Offer A is higher"),
              A1("by about \\$766 (accept \\$765–\\$770)")],
             answer="Offer A, by about \\$766",
             solution=("$$34800 - 34034.18 \\approx 766$$"
                       "Offer A is higher in year 5 by roughly \\$766."),
             verify=["34800 > 28000*Rational(105, 100)**4",
                     "Abs(34800 - 28000*Rational(105, 100)**4 - 766) < 1"]),
    ]))

# ── Q5 [8] functions: rational function ──────────────────────────────────
assert Rational(2 * 5 + 1, 5 - 3) == Rational(11, 2)
sol5 = solve(Eq((2 * x + 1) / (x - 3), 4), x)
assert sol5 == [Rational(13, 2)]
QS.append(question(
    "IB-AASL-P2-T3-Q5", 5, "A", "functions", "rational_functions",
    contextIntro=("The function $f$ is defined by "
                  "$f(x) = \\dfrac{2x + 1}{x - 3}$ for $x \\ne 3$."),
    parts=[
        part("a", "Write down the equations of the vertical and horizontal "
             "asymptotes of the graph of $f$.", 2,
             [A1("vertical: $x = 3$"),
              A1("horizontal: $y = 2$")],
             answer="$x = 3$ and $y = 2$",
             solution=("The denominator vanishes at $x = 3$ (vertical "
                       "asymptote), and for large $|x|$ the ratio of leading "
                       "coefficients gives $y = 2$."),
             verify=["Eq(Rational(2, 1), 2)"]),
        part("b", "Find $f(5)$.", 2,
             [M1("substitute $x = 5$"),
              A1("$f(5) = \\dfrac{11}{2} = 5.5$")],
             answer="$5.5$",
             solution=("$$f(5) = \\frac{11}{2} = 5.5$$"),
             verify=["Eq(Rational(2*5 + 1, 5 - 3), Rational(11, 2))"]),
        part("c", "Solve $f(x) = 4$.", 3,
             [M1("multiply up: $2x + 1 = 4(x - 3)$"),
              A1("$13 = 2x$"),
              A1("$x = 6.5$")],
             answer="$x = 6.5$",
             solution=("$$2x + 1 = 4x - 12 \\Rightarrow x = \\frac{13}{2} "
                       "= 6.5$$"),
             verify=["Eq(Rational(2*Rational(13, 2) + 1, Rational(13, 2) - 3), 4)"]),
        part("d", "Write down the value that $f(x)$ can never take.", 1,
             [A1("$y = 2$ (the horizontal asymptote value)")],
             answer="$2$",
             solution=("The graph approaches but never reaches its "
                       "horizontal asymptote, so $f(x) \\ne 2$."),
             verify=["Eq(2, 2)"]),
    ]))

# ── Q6 [8] calculus: open-box optimisation ───────────────────────────────
V6 = x * (20 - 2 * x)**2
assert expand(V6) == 4 * x**3 - 80 * x**2 + 400 * x
dV = expand(diff(V6, x))
crit = solve(Eq(dV, 0), x)
assert set(crit) == {Rational(10, 3), 10}
xopt = Rational(10, 3)
vmax = V6.subs(x, xopt)
assert vmax == Rational(16000, 27)
x_p, x_tol = sf3(N(xopt, 12))
v_p, v_tol = sf3(N(vmax, 12))
QS.append(question(
    "IB-AASL-P2-T3-Q6", 6, "A", "calculus", "optimisation",
    contextIntro=("An open box is made from a square sheet of card of side "
                  "$20$ cm by cutting a square of side $x$ cm from each "
                  "corner and folding up the sides. The volume of the box "
                  "is $V = x(20 - 2x)^2$ for $0 < x < 10$."),
    parts=[
        part("a", "Show that $V = 4x^3 - 80x^2 + 400x$.", 2,
             [M1("expand $(20 - 2x)^2 = 400 - 80x + 4x^2$ and multiply by "
                 "$x$"),
              AG("$V = 4x^3 - 80x^2 + 400x$")],
             answer="$V = 4x^3 - 80x^2 + 400x$",
             solution=("$$(20 - 2x)^2 = 400 - 80x + 4x^2$$"
                       "$$V = x(400 - 80x + 4x^2) = 4x^3 - 80x^2 + 400x$$"),
             verify=["Eq(expand(x*(20 - 2*x)**2), 4*x**3 - 80*x**2 + 400*x)"]),
        part("b", "Find $\\dfrac{dV}{dx}$.", 2,
             [M1("differentiate term by term"),
              A1("$\\dfrac{dV}{dx} = 12x^2 - 160x + 400$")],
             answer="$\\dfrac{dV}{dx} = 12x^2 - 160x + 400$",
             solution=("$$\\frac{dV}{dx} = 12x^2 - 160x + 400$$"),
             verify=["Eq(expand(diff(x*(20 - 2*x)**2, x)), "
                     "12*x**2 - 160*x + 400)"]),
        part("c", "Find the value of $x$ that gives the maximum volume, "
             "giving your answer to three significant figures.", 3,
             [M1("set $\\tfrac{dV}{dx} = 0$: $4(3x - 10)(x - 10) = 0$"),
              A1("$x = \\tfrac{10}{3}$ or $x = 10$ (rejected: $V = 0$)"),
              A1(f"$x = \\tfrac{{10}}{{3}} \\approx {x_p}$ cm")],
             answer=f"$x = \\dfrac{{10}}{{3}} \\approx {x_p}$ cm",
             solution=("$$12x^2 - 160x + 400 = 4(3x - 10)(x - 10) = 0$$"
                       "$x = 10$ gives a zero-volume box, so the maximum is "
                       f"at $x = \\tfrac{{10}}{{3}} \\approx {x_p}$."),
             verify=["Eq(expand(4*(3*x - 10)*(x - 10)), 12*x**2 - 160*x + 400)",
                     f"Abs(Rational(10, 3) - {x_p}) < {x_tol}"]),
        part("d", "Find the maximum volume, giving your answer to three "
             "significant figures.", 1,
             [A1(f"$V_{{\\max}} = \\tfrac{{16000}}{{27}} \\approx {v_p}$ "
                 "cm$^3$")],
             answer=f"$\\approx {v_p}$ cm$^3$",
             solution=("$$V\\!\\left(\\tfrac{10}{3}\\right) "
                       "= \\tfrac{16000}{27} = "
                       f"{sig(vmax, 5)}\\ldots \\approx {v_p}$$"),
             verify=["Eq(Rational(10, 3)*(20 - 2*Rational(10, 3))**2, "
                     "Rational(16000, 27))",
                     f"Abs(Rational(16000, 27) - {v_p}) < {v_tol}"]),
    ]))

# ── Q7 [13] functions (Section B): projectile quadratic, FIGURE ──────────
h7 = Rational(-49, 10) * t**2 + Rational(98, 5) * t + Rational(3, 2)
assert h7.subs(t, 0) == Rational(3, 2)
assert h7.subs(t, 2) == Rational(211, 10)
tg = [r for r in solve(Eq(h7, 0), t) if r > 0][0]
tg_p, tg_tol = sf3(N(tg, 12))
hp1 = diff(h7, t).subs(t, 1)
assert hp1 == Rational(49, 5)
QS.append(question(
    "IB-AASL-P2-T3-Q7", 7, "B", "functions", "quadratic_models",
    contextIntro=("A ball is thrown upward from a balcony. Its height above "
                  "the ground, in metres, $t$ seconds after it is thrown is "
                  "modelled by $h(t) = -4.9t^2 + 19.6t + 1.5$, as shown."),
    figure=png("ib-aasl-p2-t3-q7.png",
               "Downward parabola h(t) starting at height 1.5, peaking at "
               "t = 2 (marked with a dashed line), and returning to the "
               "t-axis just after t = 4."),
    parts=[
        part("a", "Write down the height of the balcony.", 1,
             [A1("$h(0) = 1.5$ m")],
             answer="$1.5$ m",
             solution=("The launch height is $h(0) = 1.5$ m."),
             verify=["Eq(Rational(-49, 10)*0 + Rational(98, 5)*0 + "
                     "Rational(3, 2), Rational(3, 2))"]),
        part("b", "Find the maximum height of the ball and the time at "
             "which it occurs.", 4,
             [M1("vertex at $t = -\\tfrac{19.6}{2(-4.9)}$"),
              A1("$t = 2$ s"),
              M1("substitute back into $h$"),
              A1("maximum height $h(2) = 21.1$ m")],
             answer="$21.1$ m at $t = 2$ s",
             solution=("$$t = \\frac{-19.6}{2(-4.9)} = 2$$"
                       "$$h(2) = -19.6 + 39.2 + 1.5 = 21.1 \\text{ m}$$"),
             verify=["Eq(Rational(98, 5)/(2*Rational(49, 10)), 2)",
                     "Eq(Rational(-49, 10)*4 + Rational(98, 5)*2 + "
                     "Rational(3, 2), Rational(211, 10))"]),
        part("c", "Find the time at which the ball hits the ground, giving "
             "your answer to three significant figures.", 4,
             [M1("solve $h(t) = 0$ with the GDC"),
              A1("positive root of $-4.9t^2 + 19.6t + 1.5 = 0$"),
              A1(f"$t = {sig(tg, 5)}\\ldots$"),
              A1(f"$t \\approx {tg_p}$ s")],
             answer=f"$t \\approx {tg_p}$ s (3 sf)",
             solution=("**Plan:** GDC polynomial solver, keep the positive "
                       "root."
                       f"$$t = {sig(tg, 5)}\\ldots \\approx {tg_p} "
                       "\\text{ s}$$"
                       "(The negative root has no physical meaning.)"),
             verify=[f"Abs(Rational(-49, 10)*({sig(tg, 8)})**2 + "
                     f"Rational(98, 5)*{sig(tg, 8)} + Rational(3, 2)) < 0.001",
                     f"Abs({sig(tg, 8)} - {tg_p}) < {tg_tol}"]),
        part("d", "Find the rate of change of the height at $t = 1$, and "
             "interpret the sign of your answer.", 4,
             [M1("differentiate: $h'(t) = -9.8t + 19.6$"),
              A1("$h'(1) = 9.8$ m s$^{-1}$"),
              R1("positive, so the ball is still RISING at $t = 1$"),
              A1("accept 9.8 m/s upward")],
             answer="$h'(1) = 9.8$ m s$^{-1}$; the ball is rising",
             solution=("$$h'(t) = -9.8t + 19.6, \\qquad h'(1) = 9.8$$"
                       "The rate is positive, so the height is increasing — "
                       "the ball is still on its way up at $t = 1$."),
             verify=["Eq(diff(Rational(-49, 10)*t**2 + Rational(98, 5)*t + "
                     "Rational(3, 2), t).subs(t, 1), Rational(49, 5))"]),
    ]))

# ── Q8 [12] stats_probability (Section B): normal distribution ───────────
mu8, sd8 = 70, 8


def Phi(z):
    return (1 + erf(z / sqrt(2))) / 2


p80 = 1 - Phi(Rational(80 - mu8, sd8))
p80_p, p80_tol = sf3(N(p80, 12))
pmid8 = Phi(Rational(75 - mu8, sd8)) - Phi(Rational(60 - mu8, sd8))
pmid8_p, pmid8_tol = sf3(N(pmid8, 12))
z85 = sqrt(2) * erfinv(Rational(7, 10))          # Phi(z) = 0.85
k85 = mu8 + sd8 * z85
k85_p, k85_tol = sf3(N(k85, 12))
QS.append(question(
    "IB-AASL-P2-T3-Q8", 8, "B", "stats_probability", "normal_distribution",
    contextIntro=("The times taken by runners to finish a 10 km race are "
                  "normally distributed with mean 70 minutes and standard "
                  "deviation 8 minutes. Let $X$ be a runner's time, so "
                  "$X \\sim N(70,\\ 8^2)$."),
    parts=[
        part("a", "Write down $P(X > 70)$.", 1,
             [A1("$0.5$ (the mean is the centre of symmetry)")],
             answer="$0.5$",
             solution=("The normal curve is symmetric about the mean, so "
                       "$P(X > 70) = 0.5$."),
             verify=["Eq((1 + erf(0))/2, Rational(1, 2))"]),
        part("b", "Find the probability that a runner takes more than 80 "
             "minutes, giving your answer to three significant figures.", 3,
             [M1("standardise or use the GDC: $z = \\tfrac{80 - 70}{8} "
                 "= 1.25$"),
              A1("normal cdf above 80"),
              A1(f"$P(X > 80) \\approx {p80_p}$")],
             answer=f"${p80_p}$ (3 sf)",
             solution=("$$z = \\frac{80 - 70}{8} = 1.25$$"
                       f"$$P(X > 80) = {sig(p80, 4)}\\ldots \\approx "
                       f"{p80_p}$$"),
             verify=[f"Abs(1 - (1 + erf(Rational(10, 8)/sqrt(2)))/2 - "
                     f"{p80_p}) < {p80_tol}"]),
        part("c", "Find $P(60 < X < 75)$, giving your answer to three "
             "significant figures.", 4,
             [M1("GDC normal cdf between 60 and 75"),
              A1("bounds standardise to $-1.25$ and $0.625$"),
              A1(f"$= {sig(pmid8, 4)}\\ldots$"),
              A1(f"$\\approx {pmid8_p}$")],
             answer=f"${pmid8_p}$ (3 sf)",
             solution=("**Plan:** GDC normal cdf with lower 60, upper 75."
                       f"$$P(60 < X < 75) = {sig(pmid8, 4)}\\ldots "
                       f"\\approx {pmid8_p}$$"),
             verify=[f"Abs((erf(Rational(5, 8)/sqrt(2)) - "
                     f"erf(Rational(-10, 8)/sqrt(2)))/2 - {pmid8_p}) "
                     f"< {pmid8_tol}"]),
        part("d", "The slowest 15\\% of runners take longer than $k$ "
             "minutes. Find $k$, giving your answer to three significant "
             "figures.", 4,
             [M1("$P(X > k) = 0.15$, so $P(X < k) = 0.85$ — inverse normal"),
              A1(f"$z = {sig(z85, 4)}$"),
              M1("$k = 70 + 8z$"),
              A1(f"$k \\approx {k85_p}$ minutes")],
             answer=f"$k \\approx {k85_p}$ min (3 sf)",
             solution=("**Plan:** inverse normal with area 0.85."
                       f"$$z = {sig(z85, 4)}\\ldots \\Rightarrow "
                       f"k = 70 + 8({sig(z85, 4)}\\ldots) = "
                       f"{sig(k85, 5)}\\ldots \\approx {k85_p}$$"),
             verify=[f"Abs((1 + erf(({sig(k85, 8)} - 70)/(8*sqrt(2))))/2 - "
                     f"Rational(17, 20)) < 0.0005",
                     f"Abs(sqrt(2)*erfinv(Rational(7, 10)) - {sig(z85, 4)}) "
                     f"< 0.0005"]),
    ]))

# ── Q9 [15] calculus (Section B): kinematics, displacement vs distance ───
v9 = t**2 - 6 * t + 8
assert v9.subs(t, 0) == 8
assert set(solve(Eq(v9, 0), t)) == {2, 4}
assert diff(v9, t).subs(t, 1) == -4
disp = integrate(v9, (t, 0, 5))
assert disp == Rational(20, 3)
d1 = integrate(v9, (t, 0, 2))
d2 = integrate(v9, (t, 2, 4))
d3 = integrate(v9, (t, 4, 5))
assert (d1, d2, d3) == (Rational(20, 3), Rational(-4, 3), Rational(4, 3))
dist = d1 - d2 + d3
assert dist == Rational(28, 3)
disp_p, disp_tol = sf3(N(disp, 12))
dist_p, dist_tol = sf3(N(dist, 12))
QS.append(question(
    "IB-AASL-P2-T3-Q9", 9, "B", "calculus", "kinematics",
    contextIntro=("A particle moves in a straight line. Its velocity, in "
                  "metres per second, at time $t$ seconds is "
                  "$v(t) = t^2 - 6t + 8$ for $0 \\le t \\le 5$."),
    parts=[
        part("a", "Write down the initial velocity of the particle.", 1,
             [A1("$v(0) = 8$ m s$^{-1}$")],
             answer="$8$ m s$^{-1}$",
             solution=("$$v(0) = 8 \\text{ m s}^{-1}$$"),
             verify=["Eq(0**2 - 6*0 + 8, 8)"]),
        part("b", "Find the times at which the particle is instantaneously "
             "at rest.", 3,
             [M1("set $v(t) = 0$"),
              A1("$(t - 2)(t - 4) = 0$"),
              A1("$t = 2$ s and $t = 4$ s")],
             answer="$t = 2$ and $t = 4$",
             solution=("$$t^2 - 6t + 8 = (t - 2)(t - 4) = 0 "
                       "\\Rightarrow t = 2 \\text{ or } t = 4$$"),
             verify=["Eq(2**2 - 6*2 + 8, 0)", "Eq(4**2 - 6*4 + 8, 0)"]),
        part("c", "Find the acceleration of the particle at $t = 1$.", 3,
             [M1("differentiate: $a(t) = 2t - 6$"),
              A1("$a(1) = -4$"),
              A1("$-4$ m s$^{-2}$ (decelerating)")],
             answer="$-4$ m s$^{-2}$",
             solution=("$$a(t) = v'(t) = 2t - 6, \\qquad a(1) = -4 "
                       "\\text{ m s}^{-2}$$"),
             verify=["Eq(diff(t**2 - 6*t + 8, t).subs(t, 1), -4)"]),
        part("d", "Find the displacement of the particle from its starting "
             "point after 5 seconds, giving your answer to three "
             "significant figures.", 3,
             [M1("displacement $= \\int_0^5 v\\,dt$"),
              A1("$\\left[\\tfrac{t^3}{3} - 3t^2 + 8t\\right]_0^5 = "
                 "\\tfrac{20}{3}$"),
              A1(f"$\\approx {disp_p}$ m")],
             answer=f"$\\dfrac{{20}}{{3}} \\approx {disp_p}$ m",
             solution=("$$\\int_0^5 (t^2 - 6t + 8)\\,dt = \\frac{125}{3} "
                       "- 75 + 40 = \\frac{20}{3} \\approx "
                       f"{disp_p} \\text{{ m}}$$"),
             verify=["Eq(integrate(t**2 - 6*t + 8, (t, 0, 5)), Rational(20, 3))",
                     f"Abs(Rational(20, 3) - {disp_p}) < {disp_tol}"]),
        part("e", "Find the TOTAL DISTANCE travelled by the particle in the "
             "first 5 seconds, giving your answer to three significant "
             "figures.", 5,
             [M1("split at the rest times $t = 2$ and $t = 4$ (velocity "
                 "changes sign)"),
              A1("$\\int_0^2 v = \\tfrac{20}{3}$"),
              A1("$\\int_2^4 v = -\\tfrac{4}{3}$ and $\\int_4^5 v = "
                 "\\tfrac{4}{3}$"),
              M1("add the absolute values"),
              A1(f"distance $= \\tfrac{{28}}{{3}} \\approx {dist_p}$ m")],
             answer=f"$\\dfrac{{28}}{{3}} \\approx {dist_p}$ m",
             solution=("The particle reverses direction on $(2, 4)$, so "
                       "integrate piecewise and add absolute values:"
                       "$$\\tfrac{20}{3} + \\left|-\\tfrac{4}{3}\\right| "
                       "+ \\tfrac{4}{3} = \\tfrac{28}{3} \\approx "
                       f"{dist_p} \\text{{ m}}$$"
                       "(Displacement and distance differ because of the "
                       "backward leg.)"),
             verify=["Eq(integrate(t**2 - 6*t + 8, (t, 0, 2)), Rational(20, 3))",
                     "Eq(integrate(t**2 - 6*t + 8, (t, 2, 4)), Rational(-4, 3))",
                     "Eq(integrate(t**2 - 6*t + 8, (t, 4, 5)), Rational(4, 3))",
                     f"Abs(Rational(28, 3) - {dist_p}) < {dist_tol}"]),
    ]))

META = {"course": "aa", "level": "sl", "paper": 2, "testId": "ib-practice-3",
        "label": "AA SL Practice Paper 2", "timeMinutes": 90,
        "totalMarks": 80, "calculator": True}

if __name__ == "__main__":
    write_paper(META, QS, "data/ib/aa-sl/ib-practice-3/paper2.json")
