"""AA SL Practice Paper 2 (ib-practice-1) — 90 min, 80 marks, GDC required.

Blueprint (topic x marks):
    Section A (40): Q1 number_algebra 5 | Q2 functions 6
                    Q3 geometry_trig 6  | Q4 geometry_trig 7
                    Q5 stats_probability 8 | Q6 number_algebra 8
    Section B (40): Q7 functions 12 | Q8 stats_probability 13 | Q9 calculus 15
    Paper totals: number_algebra 13 (16%) | functions 18 (23%) |
                  geometry_trig 13 (16%)  | stats_probability 21 (26%) |
                  calculus 15 (19%)
    Pair with paper 1: N&A 26 | Func 26 | Geo 31 | Stats 39 | Calc 38 of 160
    — on the AA SL blueprint (~16/17/21/22/24%).

GDC paper: final answers to 3 sf (money to 2 dp), intermediate values quoted
to >= 4 sf. EVERY printed decimal below is computed with sympy at build time
and interpolated — never typed by hand.
Figures: Q4 (circle sector + shaded segment), Q9 (x e^{-0.4x} shaded area)
— generated by scripts/test-figures/ib-aa-sl-practice-1.py from the SAME
parameters.
"""
import os
import sys
from math import floor, log10

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ibbuild import ROOT, A1, AG, M1, R1, part, question, write_paper  # noqa: E402,F401

from sympy import (Rational, sqrt, pi, Eq, sympify, simplify, solve,  # noqa: F401,E402
                   binomial, cos, erf, erfinv, exp, integrate, diff, log,
                   sin, symbols, N)

x, t = symbols("x t")


def sf3(v):
    """Round to 3 significant figures; return (printed_string, tolerance)."""
    v = float(v)
    assert v != 0
    d = 2 - floor(log10(abs(v)))
    r = round(v, d)
    printed = str(int(r)) if d <= 0 else f"{r:.{d}f}"
    # guard against ambiguous roundings (authoring rule: avoid 2.9996-style)
    assert abs(v - r) < 0.499 * 10**(-d), f"ambiguous 3sf rounding for {v}"
    return printed, 0.51 * 10**(-d)


def dp2(v):
    """Round to 2 decimal places (money)."""
    v = float(v)
    r = round(v, 2)
    assert abs(v - r) < 0.00499, f"ambiguous 2dp rounding for {v}"
    return f"{r:.2f}", 0.0051


def sig(v, n=6):
    """Quote an unrounded value to n significant figures (solution text)."""
    from decimal import Decimal
    v = float(v)
    d = (n - 1) - floor(log10(abs(v)))
    return f"{round(v, d):.{max(d, 0)}f}"


def png(name, alt_en):
    from PIL import Image
    p = os.path.join(ROOT, "public", "ib-figures", name)
    assert os.path.isfile(p), f"figure missing on disk: {p} — run the figure script first"
    with Image.open(p) as im:
        w, h = im.size
    return {"src": f"/ib-figures/{name}", "width": w, "height": h, "alt_en": alt_en}


QS = []

# ── Q1 [5] number_algebra: compound interest ─────────────────────────────
# 5000 invested at 4.2% p.a. compounded monthly; 0.042/12 = 7/2000 per month.
rate = Rational(7, 2000)
fv = 5000 * (1 + rate)**72                      # after 6 years = 72 months
fv_p, fv_tol = dp2(N(fv, 12))
assert (1 + rate)**(12 * 16) < 2 < (1 + rate)**(12 * 17)   # doubling year = 17
QS.append(question(
    "IB-AASL-P2-T1-Q1", 1, "A", "number_algebra", "compound_interest",
    contextIntro=("Bolor invests 5000 dollars in a savings account that pays "
                  "an annual interest rate of 4.2%, compounded monthly. "
                  "No further deposits or withdrawals are made."),
    parts=[
        part("a", "Find the value of the investment after 6 years.", 3,
             [M1("use $FV = PV\\left(1 + \\dfrac{r}{100k}\\right)^{kn}$ with "
                 "$r = 4.2$, $k = 12$, $n = 6$"),
              A1("correct substitution: $5000(1.0035)^{72}$"),
              A1(f"$= {fv_p}$ dollars")],
             answer=f"${fv_p}$ dollars",
             solution=("**Plan:** compound interest with monthly compounding "
                       "(booklet formula)."
                       "$$FV = 5000\\left(1 + \\frac{4.2}{100 \\times 12}\\right)"
                       "^{12 \\times 6} = 5000(1.0035)^{72}$$"
                       f"$$= {fv_p} \\text{{ dollars (2 dp)}}$$"
                       "Using the GDC finance app or direct computation gives the "
                       "same value."),
             verify=[f"Abs(5000*(1 + Rational(7, 2000))**72 - {fv_p}) < {fv_tol}"]),
        part("b", "Find the minimum number of whole years needed for the value "
                  "of the investment to become greater than 10000 dollars.", 2,
             [M1("solve $5000(1.0035)^{12n} > 10000$, e.g. GDC table/graph "
                 "or logarithms"),
              A1("$n = 17$ years")],
             answer="17 years",
             solution=("**Plan:** the value doubles when $(1.0035)^{12n} = 2$."
                       "$$12n\\,\\ln(1.0035) = \\ln 2 \\Rightarrow n = "
                       "\\frac{\\ln 2}{12\\ln(1.0035)} \\approx 16.5$$"
                       "After 16 whole years the value is still below 10000 "
                       "dollars; after 17 years it is above. The minimum number "
                       "of whole years is $n = 17$."),
             verify=["(1 + Rational(7, 2000))**(12*16) < 2",
                     "(1 + Rational(7, 2000))**(12*17) > 2"]),
    ]))

# ── Q2 [6] functions: exponential model ──────────────────────────────────
# P(t) = 800 e^{0.12 t}
p5 = 800 * exp(Rational(3, 5))                  # 0.12*5 = 3/5
p5_p, p5_tol = sf3(N(p5, 12))
t2000 = log(Rational(5, 2)) / Rational(3, 25)   # ln(2.5)/0.12
t2000_p, t2000_tol = sf3(N(t2000, 12))
QS.append(question(
    "IB-AASL-P2-T1-Q2", 2, "A", "functions", "exponential_model",
    contextIntro=("The number of fish in a lake is modelled by "
                  "$P(t) = 800\\,e^{0.12t}$, where $t$ is the time in years "
                  "after the lake was first stocked."),
    parts=[
        part("a", "Write down the number of fish when the lake was first "
                  "stocked.", 1,
             [A1("$P(0) = 800$")],
             answer="800 fish",
             solution=("At $t = 0$: $P(0) = 800\\,e^{0} = 800$ fish."),
             verify=["Eq(800*exp(0), 800)"]),
        part("b", "Find the number of fish after 5 years.", 2,
             [M1("$P(5) = 800\\,e^{0.12 \\times 5}$"),
              A1(f"$\\approx {p5_p}$ fish (accept ${sig(p5, 6)}$)")],
             answer=f"${p5_p}$ fish (3 sf)",
             solution=("**Plan:** substitute $t = 5$."
                       f"$$P(5) = 800\\,e^{{0.6}} = {sig(p5, 6)}\\ldots$$"
                       f"To 3 sf the model predicts ${p5_p}$ fish."),
             verify=[f"Abs(800*exp(Rational(3, 5)) - {p5_p}) < {p5_tol}",
                     f"Abs(800*exp(Rational(3, 5)) - {sig(p5, 6)}) < 0.005"]),
        part("c", "Find the value of $t$ when the population first reaches "
                  "2000.", 3,
             [M1("set up $800\\,e^{0.12t} = 2000$, so $e^{0.12t} = 2.5$"),
              M1("solve with the GDC (graph/solver) or logarithms: "
                 "$t = \\dfrac{\\ln 2.5}{0.12}$"),
              A1(f"$t \\approx {t2000_p}$ years (accept ${sig(t2000, 6)}$)")],
             answer=f"$t = {t2000_p}$ years (3 sf)",
             solution=("**Plan:** isolate the exponential, then take logarithms "
                       "(or intersect the two graphs on the GDC)."
                       "$$800\\,e^{0.12t} = 2000 \\Rightarrow e^{0.12t} = 2.5$$"
                       f"$$t = \\frac{{\\ln 2.5}}{{0.12}} = {sig(t2000, 6)}\\ldots"
                       f" \\approx {t2000_p} \\text{{ years}}$$"),
             verify=[f"Abs(log(Rational(5, 2))/Rational(3, 25) - {t2000_p}) "
                     f"< {t2000_tol}",
                     f"Abs(800*exp(Rational(3, 25)*{sig(t2000, 8)}) - 2000) < 0.01"]),
    ]))

# ── Q3 [6] geometry_trig: cosine rule + area (SAS, unambiguous) ──────────
ab, ac = Rational(36, 5), Rational(19, 2)       # AB = 7.2 cm, AC = 9.5 cm
angA = 38 * pi / 180
bc = sqrt(ab**2 + ac**2 - 2 * ab * ac * cos(angA))
bc_p, bc_tol = sf3(N(bc, 12))
bc2 = ab**2 + ac**2 - 2 * ab * ac * cos(angA)
area3 = Rational(1, 2) * ab * ac * sin(angA)
area3_p, area3_tol = sf3(N(area3, 12))
QS.append(question(
    "IB-AASL-P2-T1-Q3", 3, "A", "geometry_trig", "cosine_rule_area",
    contextIntro=("In triangle $ABC$, $AB = 7.2$ cm, $AC = 9.5$ cm and "
                  "$B\\hat{A}C = 38^{\\circ}$."),
    parts=[
        part("a", "Find $BC$.", 3,
             [M1("cosine rule: $BC^2 = 7.2^2 + 9.5^2 - "
                 "2(7.2)(9.5)\\cos 38^{\\circ}$"),
              A1(f"$BC^2 = {sig(bc2, 6)}\\ldots$"),
              A1(f"$BC \\approx {bc_p}$ cm (accept ${sig(bc, 6)}$)")],
             answer=f"$BC = {bc_p}$ cm (3 sf)",
             solution=("**Plan:** two sides and the included angle — cosine rule "
                       "(booklet)."
                       "$$BC^2 = 7.2^2 + 9.5^2 - 2(7.2)(9.5)\\cos 38^{\\circ}"
                       f" = {sig(bc2, 6)}\\ldots$$"
                       f"$$BC = {sig(bc, 6)}\\ldots \\approx {bc_p}"
                       " \\text{ cm}$$"),
             verify=[f"Abs(sqrt(Rational(36, 5)**2 + Rational(19, 2)**2 - "
                     f"2*Rational(36, 5)*Rational(19, 2)*cos(19*pi/90)) - {bc_p}) "
                     f"< {bc_tol}"]),
        part("b", "Find the area of triangle $ABC$.", 3,
             [M1("area $= \\dfrac{1}{2}(7.2)(9.5)\\sin 38^{\\circ}$"),
              A1(f"$= {sig(area3, 6)}\\ldots$"),
              A1(f"area $\\approx {area3_p}$ cm$^2$")],
             answer=f"${area3_p}$ cm$^2$ (3 sf)",
             solution=("**Plan:** the included angle is known, so use "
                       "$\\dfrac{1}{2}bc\\sin A$."
                       "$$\\text{area} = \\frac{1}{2}(7.2)(9.5)\\sin 38^{\\circ}"
                       f" = {sig(area3, 6)}\\ldots \\approx {area3_p}"
                       " \\text{ cm}^2$$"),
             verify=[f"Abs(Rational(1, 2)*Rational(36, 5)*Rational(19, 2)*"
                     f"sin(19*pi/90) - {area3_p}) < {area3_tol}"]),
    ]))

# ── Q4 [7] geometry_trig: sector in radians + segment ────────────────────
r4, th4 = Rational(32, 5), Rational(27, 20)     # r = 6.4 cm, theta = 1.35 rad
arc4 = r4 * th4
assert arc4 == Rational(216, 25)                # 8.64 exactly
sector4 = Rational(1, 2) * r4**2 * th4
assert sector4 == Rational(3456, 125)           # 27.648 exactly
sector4_p, sector4_tol = sf3(N(sector4, 12))
tri4 = Rational(1, 2) * r4**2 * sin(th4)
seg4 = sector4 - tri4
seg4_p, seg4_tol = sf3(N(seg4, 12))
QS.append(question(
    "IB-AASL-P2-T1-Q4", 4, "A", "geometry_trig", "radian_sector_segment",
    contextIntro=("The diagram shows a circle with centre $O$ and radius "
                  "6.4 cm. Points $A$ and $B$ lie on the circle and "
                  "$A\\hat{O}B = 1.35$ radians. The region between the chord "
                  "$[AB]$ and the arc $AB$ is shaded."),
    figure=png("ib-aasl-p2-t1-q4.png",
               "Circle with centre O and radius 6.4 cm; radii OA and OB make "
               "an angle of 1.35 radians; the segment between chord AB and "
               "the minor arc AB is shaded."),
    parts=[
        part("a", "Find the length of the arc $AB$.", 2,
             [M1("arc length $= r\\theta = 6.4 \\times 1.35$"),
              A1("$= 8.64$ cm")],
             answer="$8.64$ cm",
             solution=("**Plan:** radian arc-length formula (booklet)."
                       "$$l = r\\theta = 6.4 \\times 1.35 = 8.64 \\text{ cm}$$"
                       "(exact — no rounding needed)."),
             verify=["Eq(Rational(32, 5)*Rational(27, 20), Rational(216, 25))",
                     "Eq(Rational(216, 25), 8.64)"]),
        part("b", "Find the area of the sector $AOB$.", 2,
             [M1("sector area $= \\dfrac{1}{2}r^2\\theta = "
                 "\\dfrac{1}{2}(6.4^2)(1.35)$"),
              A1(f"$= 27.648 \\approx {sector4_p}$ cm$^2$")],
             answer=f"${sector4_p}$ cm$^2$ (3 sf); exact value $27.648$",
             solution=("**Plan:** radian sector-area formula (booklet)."
                       "$$A = \\frac{1}{2}r^2\\theta = \\frac{1}{2}(40.96)(1.35)"
                       f" = 27.648 \\approx {sector4_p} \\text{{ cm}}^2$$"),
             verify=["Eq(Rational(1, 2)*Rational(32, 5)**2*Rational(27, 20), "
                     "Rational(3456, 125))",
                     f"Abs(Rational(3456, 125) - {sector4_p}) < {sector4_tol}"]),
        part("c", "Find the area of the shaded region.", 3,
             [M1("segment $=$ sector $-$ triangle: "
                 "$\\dfrac{1}{2}r^2\\theta - \\dfrac{1}{2}r^2\\sin\\theta$"),
              A1(f"triangle area $= \\dfrac{{1}}{{2}}(6.4^2)\\sin 1.35 = "
                 f"{sig(tri4, 6)}\\ldots$"),
              A1(f"shaded area $\\approx {seg4_p}$ cm$^2$ "
                 f"(accept ${sig(seg4, 6)}$)")],
             answer=f"${seg4_p}$ cm$^2$ (3 sf)",
             solution=("**Plan:** the segment is the sector minus the isosceles "
                       "triangle $AOB$."
                       "$$\\text{segment} = \\frac{1}{2}r^2(\\theta - \\sin\\theta)"
                       " = \\frac{1}{2}(40.96)(1.35 - \\sin 1.35)$$"
                       f"$$= 27.648 - {sig(tri4, 6)}\\ldots = {sig(seg4, 6)}\\ldots"
                       f" \\approx {seg4_p} \\text{{ cm}}^2$$"
                       "Remember: 1.35 is in **radians** — a GDC left in degree "
                       "mode gives a wrong answer here."),
             verify=[f"Abs(Rational(1, 2)*Rational(32, 5)**2*(Rational(27, 20) - "
                     f"sin(Rational(27, 20))) - {seg4_p}) < {seg4_tol}",
                     f"Abs(Rational(1, 2)*Rational(32, 5)**2*sin(Rational(27, 20))"
                     f" - {sig(tri4, 6)}) < 0.005"]),
    ]))

# ── Q5 [8] stats_probability: normal distribution ────────────────────────
mu, sd = 160, 12
def Phi(z):
    return (1 + erf(z / sqrt(2))) / 2
p148 = Phi(Rational(148 - mu, sd))
p148_p, p148_tol = sf3(N(p148, 12))
pmid = Phi(Rational(175 - mu, sd)) - Phi(Rational(150 - mu, sd))
pmid_p, pmid_tol = sf3(N(pmid, 12))
z80 = sqrt(2) * erfinv(Rational(3, 5))          # z with Phi(z) = 0.8
k80 = mu + sd * z80
k80_p, k80_tol = sf3(N(k80, 12))
QS.append(question(
    "IB-AASL-P2-T1-Q5", 5, "A", "stats_probability", "normal_distribution",
    contextIntro=("The masses of apples from an orchard are normally "
                  "distributed with mean 160 g and standard deviation 12 g. "
                  "An apple is chosen at random. Let $X$ be its mass in grams, "
                  "so $X \\sim N(160,\\ 12^2)$."),
    parts=[
        part("a", "Write down $P(X < 160)$.", 1,
             [A1("$P(X < 160) = 0.5$ (the mean is the centre of symmetry)")],
             answer="$0.5$",
             solution=("The normal curve is symmetric about its mean, so exactly "
                       "half the distribution lies below 160 g: "
                       "$P(X < 160) = 0.5$."),
             verify=["Eq((1 + erf(0))/2, Rational(1, 2))"]),
        part("b", "Find $P(X < 148)$.", 2,
             [M1("standardise or use the GDC: $z = \\dfrac{148 - 160}{12} = -1$"),
              A1(f"$P(X < 148) \\approx {p148_p}$ (accept ${sig(p148, 4)}$)")],
             answer=f"${p148_p}$ (3 sf)",
             solution=("**Plan:** 148 g is exactly one standard deviation below "
                       "the mean."
                       "$$z = \\frac{148 - 160}{12} = -1$$"
                       f"$$P(X < 148) = P(Z < -1) = {sig(p148, 4)}\\ldots"
                       f" \\approx {p148_p}$$"),
             verify=[f"Abs((1 + erf(-1/sqrt(2)))/2 - {p148_p}) < {p148_tol}"]),
        part("c", "Find $P(150 < X < 175)$.", 2,
             [M1("GDC normal cdf between 150 and 175 (or standardise both "
                 "bounds)"),
              A1(f"$P(150 < X < 175) \\approx {pmid_p}$ "
                 f"(accept ${sig(pmid, 4)}$)")],
             answer=f"${pmid_p}$ (3 sf)",
             solution=("**Plan:** GDC normal cdf with lower 150, upper 175, "
                       "$\\mu = 160$, $\\sigma = 12$."
                       f"$$P(150 < X < 175) = {sig(pmid, 4)}\\ldots"
                       f" \\approx {pmid_p}$$"),
             verify=[f"Abs((erf(Rational(15, 12)/sqrt(2)) - "
                     f"erf(Rational(-10, 12)/sqrt(2)))/2 - {pmid_p}) "
                     f"< {pmid_tol}"]),
        part("d", "20% of the apples have mass greater than $k$ grams. "
                  "Find $k$.", 3,
             [M1("$P(X > k) = 0.2$, so $P(X < k) = 0.8$ — inverse normal"),
              A1(f"$z = {sig(z80, 4)}$"),
              A1(f"$k \\approx {k80_p}$ g (accept ${sig(k80, 5)}$)")],
             answer=f"$k = {k80_p}$ g (3 sf)",
             solution=("**Plan:** inverse normal on the GDC with area 0.8."
                       f"$$P(X < k) = 0.8 \\Rightarrow z = {sig(z80, 4)}\\ldots$$"
                       f"$$k = 160 + 12({sig(z80, 4)}\\ldots) = {sig(k80, 5)}\\ldots"
                       f" \\approx {k80_p} \\text{{ g}}$$"),
             verify=[f"Abs((1 + erf(({sig(k80, 8)} - 160)/(12*sqrt(2))))/2 - "
                     f"Rational(4, 5)) < 0.0005",
                     f"Abs(sqrt(2)*erfinv(Rational(3, 5)) - {sig(z80, 4)}) "
                     f"< 0.0005"]),
    ]))

# ── Q6 [8] number_algebra: geometric sequence + threshold ────────────────
g1, gr = 200, Rational(11, 10)
u10 = g1 * gr**9
u10_p, u10_tol = sf3(N(u10, 12))
s10 = g1 * (gr**10 - 1) / (gr - 1)
s10_p, s10_tol = sf3(N(s10, 12))
assert gr**13 < Rational(7, 2) < gr**14         # least n with S_n > 5000 is 14
QS.append(question(
    "IB-AASL-P2-T1-Q6", 6, "A", "number_algebra", "geometric_series",
    contextIntro=("A geometric sequence has first term $u_1 = 200$ and common "
                  "ratio $r = 1.1$."),
    parts=[
        part("a", "Find $u_{10}$.", 2,
             [M1("$u_{10} = 200 \\times 1.1^{9}$"),
              A1(f"$\\approx {u10_p}$ (accept ${sig(u10, 6)}$)")],
             answer=f"$u_{{10}} = {u10_p}$ (3 sf)",
             solution=("**Plan:** $u_n = u_1 r^{n-1}$ (booklet)."
                       f"$$u_{{10}} = 200 \\times 1.1^{{9}} = {sig(u10, 6)}\\ldots"
                       f" \\approx {u10_p}$$"),
             verify=[f"Abs(200*Rational(11, 10)**9 - {u10_p}) < {u10_tol}"]),
        part("b", "Find the sum of the first 10 terms.", 2,
             [M1("$S_{10} = \\dfrac{200(1.1^{10} - 1)}{1.1 - 1}$"),
              A1(f"$\\approx {s10_p}$ (accept ${sig(s10, 6)}$)")],
             answer=f"$S_{{10}} = {s10_p}$ (3 sf)",
             solution=("**Plan:** geometric series formula (booklet)."
                       f"$$S_{{10}} = \\frac{{200(1.1^{{10}} - 1)}}{{0.1}}"
                       f" = {sig(s10, 6)}\\ldots \\approx {s10_p}$$"),
             verify=[f"Abs(200*(Rational(11, 10)**10 - 1)/(Rational(11, 10) - 1)"
                     f" - {s10_p}) < {s10_tol}"]),
        part("c", "Find the least value of $n$ such that $S_n > 5000$.", 4,
             [M1("set up $\\dfrac{200(1.1^{n} - 1)}{0.1} > 5000$"),
              A1("simplify to $1.1^{n} > 3.5$"),
              M1("solve with logarithms or a GDC table: "
                 "$n > \\dfrac{\\ln 3.5}{\\ln 1.1} \\approx 13.1$"),
              A1("least $n = 14$")],
             answer="$n = 14$",
             solution=("**Plan:** solve the inequality for $n$, then round UP to "
                       "a whole term."
                       "$$2000(1.1^{n} - 1) > 5000 \\Rightarrow 1.1^{n} > 3.5$$"
                       "$$n > \\frac{\\ln 3.5}{\\ln 1.1} = 13.14\\ldots$$"
                       "A GDC table confirms $S_{13} \\approx 4905 < 5000$ and "
                       "$S_{14} \\approx 5595 > 5000$. The least value is "
                       "$n = 14$."),
             verify=["Rational(11, 10)**13 < Rational(7, 2)",
                     "Rational(11, 10)**14 > Rational(7, 2)",
                     "Abs(log(Rational(7, 2))/log(Rational(11, 10)) - 13.14) "
                     "< 0.005"]),
    ]))

# ── Q7 [12] Section B functions: projectile quadratic model ──────────────
# h(t) = -4.9 t^2 + 18 t + 1.2
a7, b7, c7 = Rational(-49, 10), 18, Rational(6, 5)
tmax = -b7 / (2 * a7)
hmax = a7 * tmax**2 + b7 * tmax + c7
tmax_p, tmax_tol = sf3(N(tmax, 12))
hmax_p, hmax_tol = sf3(N(hmax, 12))
disc_g = b7**2 - 4 * a7 * c7                    # ground: h = 0
tg = (-b7 - sqrt(disc_g)) / (2 * a7)            # positive root
tg_neg = (-b7 + sqrt(disc_g)) / (2 * a7)
tg_p, tg_tol = sf3(N(tg, 12))
disc_10 = b7**2 - 4 * a7 * (c7 - 10)            # h = 10
t10a = (-b7 + sqrt(disc_10)) / (2 * a7)         # earlier time (a7 < 0)
t10b = (-b7 - sqrt(disc_10)) / (2 * a7)
assert N(t10a) < N(t10b)
dur10 = t10b - t10a
t10a_p, t10a_tol = sf3(N(t10a, 12))
t10b_p, t10b_tol = sf3(N(t10b, 12))
dur10_p, dur10_tol = sf3(N(dur10, 12))
QS.append(question(
    "IB-AASL-P2-T1-Q7", 7, "B", "functions", "quadratic_model",
    contextIntro=("A ball is launched upwards from a platform. Its height "
                  "above the ground is modelled by "
                  "$h(t) = -4.9t^2 + 18t + 1.2$, where $h$ is in metres and "
                  "$t \\ge 0$ is the time in seconds after launch."),
    parts=[
        part("a", "Write down the height of the platform.", 1,
             [A1("$h(0) = 1.2$ m")],
             answer="$1.2$ m",
             solution=("The launch height is the value at $t = 0$: "
                       "$h(0) = 1.2$ m."),
             verify=["Eq(Rational(-49, 10)*0**2 + 18*0 + Rational(6, 5), "
                     "Rational(6, 5))"]),
        part("b", "Find the maximum height of the ball and the time at which "
                  "it occurs.", 3,
             [M1("vertex: $t = \\dfrac{-18}{2(-4.9)}$ (or GDC maximum)"),
              A1(f"$t \\approx {tmax_p}$ s (accept ${sig(tmax, 5)}$)"),
              A1(f"maximum height $\\approx {hmax_p}$ m "
                 f"(accept ${sig(hmax, 5)}$)")],
             answer=f"$t = {tmax_p}$ s, maximum height ${hmax_p}$ m (3 sf)",
             solution=("**Plan:** the vertex of the parabola (GDC maximum, or "
                       "$t = -b/2a$)."
                       f"$$t = \\frac{{-18}}{{2(-4.9)}} = {sig(tmax, 5)}\\ldots"
                       f" \\approx {tmax_p} \\text{{ s}}$$"
                       f"$$h({sig(tmax, 5)}\\ldots) = {sig(hmax, 5)}\\ldots"
                       f" \\approx {hmax_p} \\text{{ m}}$$"),
             verify=[f"Abs(Rational(90, 49) - {tmax_p}) < {tmax_tol}",
                     f"Abs(Rational(4344, 245) - {hmax_p}) < {hmax_tol}",
                     "Eq(-18/(2*Rational(-49, 10)), Rational(90, 49))"]),
        part("c", "Find the time at which the ball hits the ground.", 3,
             [M1("solve $h(t) = 0$ with the GDC (or quadratic formula)"),
              A1(f"$t \\approx {tg_p}$ s (accept ${sig(tg, 5)}$)"),
              R1(f"the negative root $t \\approx {sig(tg_neg, 3)}$ is rejected "
                 "(time cannot be negative)")],
             answer=f"$t = {tg_p}$ s (3 sf)",
             solution=("**Plan:** the ball lands when $h(t) = 0$."
                       "$$-4.9t^2 + 18t + 1.2 = 0$$"
                       f"The GDC gives $t = {sig(tg_neg, 3)}$ or "
                       f"$t = {sig(tg, 5)}\\ldots$. Time is non-negative, so the "
                       f"ball hits the ground at $t \\approx {tg_p}$ s."),
             verify=[f"Abs((-18 - sqrt(Rational(8688, 25)))/(2*Rational(-49, 10))"
                     f" - {tg_p}) < {tg_tol}",
                     "Rational(8688, 25) > 0",
                     f"Abs(Rational(-49, 10)*{sig(tg, 8)}**2 + 18*{sig(tg, 8)} + "
                     f"Rational(6, 5)) < 0.001"]),
        part("d", "Find the length of time for which the ball is at least "
                  "10 m above the ground.", 4,
             [M1("solve $h(t) = 10$: $-4.9t^2 + 18t - 8.8 = 0$"),
              A1(f"$t = {t10a_p}$ and $t = {t10b_p}$ "
                 f"(accept ${sig(t10a, 5)}$, ${sig(t10b, 5)}$)"),
              M1("length of time = difference of the roots"),
              A1(f"$\\approx {dur10_p}$ s (accept ${sig(dur10, 5)}$)")],
             answer=f"${dur10_p}$ s (3 sf)",
             solution=("**Plan:** the ball is at least 10 m up between the two "
                       "solutions of $h(t) = 10$."
                       "$$-4.9t^2 + 18t + 1.2 = 10 \\Rightarrow "
                       "-4.9t^2 + 18t - 8.8 = 0$$"
                       f"GDC: $t = {sig(t10a, 5)}\\ldots$ and "
                       f"$t = {sig(t10b, 5)}\\ldots$"
                       f"$$\\Delta t = {sig(t10b, 5)} - {sig(t10a, 5)}"
                       f" = {sig(dur10, 5)}\\ldots \\approx {dur10_p}"
                       " \\text{ s}$$"),
             verify=[f"Abs((-18 + sqrt(Rational(3788, 25)))/(2*Rational(-49, 10))"
                     f" - {t10a_p}) < {t10a_tol}",
                     f"Abs((-18 - sqrt(Rational(3788, 25)))/(2*Rational(-49, 10))"
                     f" - {t10b_p}) < {t10b_tol}",
                     f"Abs(sqrt(Rational(3788, 25))/Rational(49, 10) - {dur10_p})"
                     f" < {dur10_tol}"]),
        part("e", "Write down the domain of the model.", 1,
             [A1(f"$0 \\le t \\le {tg_p}$ (FT from part (c))")],
             answer=f"$0 \\le t \\le {tg_p}$",
             solution=("The model applies from launch until the ball lands, so "
                       f"$0 \\le t \\le {tg_p}$ (using the landing time from "
                       "part (c))."),
             verify=[f"{tg_p} > 0"]),
    ]))

# ── Q8 [13] Section B stats_probability: binomial distribution ───────────
n8, p8 = 12, Rational(3, 5)
def bpmf(kk):
    return binomial(n8, kk) * p8**kk * (1 - p8)**(n8 - kk)
e8 = n8 * p8
assert e8 == Rational(36, 5)                    # 7.2 exactly
p7 = bpmf(7)
p7_p, p7_tol = sf3(N(p7, 12))
p_ge9 = sum(bpmf(kk) for kk in range(9, 13))
p_ge9_p, p_ge9_tol = sf3(N(p_ge9, 12))
p_ge7 = sum(bpmf(kk) for kk in range(7, 13))
p_ge7_p, p_ge7_tol = sf3(N(p_ge7, 12))
cond8 = p_ge9 / p_ge7
cond8_p, cond8_tol = sf3(N(cond8, 12))
two_of3 = 3 * p_ge9**2 * (1 - p_ge9)
two_of3_p, two_of3_tol = sf3(N(two_of3, 12))
QS.append(question(
    "IB-AASL-P2-T1-Q8", 8, "B", "stats_probability", "binomial_distribution",
    contextIntro=("Sarnai is a basketball player. Each free throw she attempts "
                  "is successful with probability 0.6, independently of all "
                  "other attempts. In one training game she attempts 12 free "
                  "throws. Let $X$ be the number of successful throws, so "
                  "$X \\sim B(12,\\ 0.6)$."),
    parts=[
        part("a", "Find the expected number of successful throws.", 2,
             [M1("$E(X) = np = 12 \\times 0.6$"),
              A1("$E(X) = 7.2$")],
             answer="$E(X) = 7.2$",
             solution=("**Plan:** binomial mean $E(X) = np$ (booklet)."
                       "$$E(X) = 12 \\times 0.6 = 7.2$$"),
             verify=["Eq(12*Rational(3, 5), Rational(36, 5))"]),
        part("b", "Find $P(X = 7)$.", 2,
             [M1("binomial pdf: $\\dbinom{12}{7}(0.6)^7(0.4)^5$ (GDC)"),
              A1(f"$P(X = 7) \\approx {p7_p}$ (accept ${sig(p7, 4)}$)")],
             answer=f"${p7_p}$ (3 sf)",
             solution=("**Plan:** binomial probability with the GDC (binompdf)."
                       "$$P(X = 7) = \\binom{12}{7}(0.6)^7(0.4)^5"
                       f" = {sig(p7, 4)}\\ldots \\approx {p7_p}$$"),
             verify=[f"Abs(binomial(12, 7)*Rational(3, 5)**7*Rational(2, 5)**5 - "
                     f"{p7_p}) < {p7_tol}"]),
        part("c", "Find $P(X \\ge 9)$.", 3,
             [M1("$P(X \\ge 9) = 1 - P(X \\le 8)$ (GDC binomcdf)"),
              A1(f"$P(X \\le 8) \\approx {sig(1 - p_ge9, 4)}$"),
              A1(f"$P(X \\ge 9) \\approx {p_ge9_p}$ (accept ${sig(p_ge9, 4)}$)")],
             answer=f"${p_ge9_p}$ (3 sf)",
             solution=("**Plan:** complement with the cumulative binomial."
                       "$$P(X \\ge 9) = 1 - P(X \\le 8)"
                       f" = 1 - {sig(1 - p_ge9, 4)}\\ldots"
                       f" = {sig(p_ge9, 4)}\\ldots \\approx {p_ge9_p}$$"),
             verify=[f"Abs(Sum(binomial(12, k)*Rational(3, 5)**k*"
                     f"Rational(2, 5)**(12 - k), (k, 9, 12)).doit() - {p_ge9_p})"
                     f" < {p_ge9_tol}"]),
        part("d", "Given that Sarnai makes at least 7 successful throws, find "
                  "the probability that she makes at least 9.", 3,
             [M1("conditional probability: "
                 "$\\dfrac{P(X \\ge 9)}{P(X \\ge 7)}$ (since "
                 "$X \\ge 9 \\Rightarrow X \\ge 7$)"),
              A1(f"$P(X \\ge 7) \\approx {p_ge7_p}$"),
              A1(f"$P(X \\ge 9 \\mid X \\ge 7) \\approx {cond8_p}$ "
                 f"(accept ${sig(cond8, 4)}$)")],
             answer=f"${cond8_p}$ (3 sf)",
             solution=("**Plan:** the event $X \\ge 9$ is inside $X \\ge 7$, so"
                       "$$P(X \\ge 9 \\mid X \\ge 7) = "
                       "\\frac{P(X \\ge 9)}{P(X \\ge 7)}"
                       f" = \\frac{{{sig(p_ge9, 4)}\\ldots}}{{{sig(p_ge7, 4)}"
                       f"\\ldots}} = {sig(cond8, 4)}\\ldots \\approx {cond8_p}$$"),
             verify=[f"Abs(Sum(binomial(12, k)*Rational(3, 5)**k*"
                     f"Rational(2, 5)**(12 - k), (k, 7, 12)).doit() - {p_ge7_p})"
                     f" < {p_ge7_tol}",
                     f"Abs(Sum(binomial(12, k)*Rational(3, 5)**k*"
                     f"Rational(2, 5)**(12 - k), (k, 9, 12)).doit() / "
                     f"Sum(binomial(12, k)*Rational(3, 5)**k*"
                     f"Rational(2, 5)**(12 - k), (k, 7, 12)).doit() - {cond8_p})"
                     f" < {cond8_tol}"]),
        part("e", "Sarnai plays three such games, independently. Find the "
                  "probability that she makes at least 9 successful throws in "
                  "exactly two of the three games.", 3,
             [M1(f"let $Y$ = number of games with at least 9 throws: "
                 f"$Y \\sim B(3,\\ {sig(p_ge9, 4)}\\ldots)$"),
              A1(f"$P(Y = 2) = 3q^2(1 - q)$ with $q \\approx {sig(p_ge9, 4)}$"),
              A1(f"$\\approx {two_of3_p}$ (accept ${sig(two_of3, 4)}$)")],
             answer=f"${two_of3_p}$ (3 sf)",
             solution=("**Plan:** each game is a fresh trial whose success "
                       "probability is the answer to part (c)."
                       f"$$q = P(X \\ge 9) = {sig(p_ge9, 4)}\\ldots$$"
                       "$$P(Y = 2) = \\binom{3}{2}q^2(1 - q)"
                       f" = 3({sig(p_ge9, 4)}\\ldots)^2(1 - {sig(p_ge9, 4)}"
                       f"\\ldots) = {sig(two_of3, 4)}\\ldots \\approx "
                       f"{two_of3_p}$$"
                       "Using the ROUNDED 0.225 here instead of the full GDC "
                       "value changes the third significant figure — keep the "
                       "unrounded value in the calculator."),
             verify=[f"Abs(3*(Sum(binomial(12, k)*Rational(3, 5)**k*"
                     f"Rational(2, 5)**(12 - k), (k, 9, 12)).doit())**2*"
                     f"(1 - Sum(binomial(12, k)*Rational(3, 5)**k*"
                     f"Rational(2, 5)**(12 - k), (k, 9, 12)).doit()) - "
                     f"{two_of3_p}) < {two_of3_tol}"]),
    ]))

# ── Q9 [15] Section B calculus: f(x) = x e^{-0.4x} ───────────────────────
f9 = x * exp(-2 * x / 5)
fp9 = diff(f9, x)
assert simplify(fp9 - (1 - Rational(2, 5) * x) * exp(-2 * x / 5)) == 0
assert solve(fp9, x) == [Rational(5, 2)]
ymax9 = f9.subs(x, Rational(5, 2))
assert ymax9 == Rational(5, 2) * exp(-1)
ymax9_p, ymax9_tol = sf3(N(ymax9, 12))
infl = solve(diff(f9, x, 2), x)
assert infl == [5]
area9 = integrate(f9, (x, 0, 5))
assert area9 == Rational(25, 4) - Rational(75, 4) * exp(-2)
area9_p, area9_tol = sf3(N(area9, 12))
QS.append(question(
    "IB-AASL-P2-T1-Q9", 9, "B", "calculus", "exp_curve_analysis",
    contextIntro=("Let $f(x) = x\\,e^{-0.4x}$ for $x \\ge 0$. The diagram "
                  "shows the graph of $y = f(x)$, and the shaded region is "
                  "enclosed by the curve, the $x$-axis and the line $x = 5$."),
    figure=png("ib-aasl-p2-t1-q9.png",
               "Curve y = x times e to the minus 0.4 x rising from the origin "
               "to a single maximum then decaying; the region under the curve "
               "from x = 0 to the dashed line x = 5 is shaded."),
    parts=[
        part("a", "Write down $f(0)$.", 1,
             [A1("$f(0) = 0$")],
             answer="$f(0) = 0$",
             solution=("$f(0) = 0 \\times e^{0} = 0$."),
             verify=["Eq(0*exp(0), 0)"]),
        part("b", "Show that $f'(x) = (1 - 0.4x)\\,e^{-0.4x}$.", 3,
             [M1("product rule: $f'(x) = (1)\\,e^{-0.4x} + "
                 "x(-0.4)\\,e^{-0.4x}$"),
              A1("$= e^{-0.4x} - 0.4x\\,e^{-0.4x}$"),
              AG("$f'(x) = (1 - 0.4x)\\,e^{-0.4x}$")],
             answer="$f'(x) = (1 - 0.4x)\\,e^{-0.4x}$ (shown)",
             solution=("**Plan:** product rule with $u = x$, $v = e^{-0.4x}$."
                       "$$f'(x) = 1 \\cdot e^{-0.4x} + x \\cdot (-0.4)e^{-0.4x}$$"
                       "$$= e^{-0.4x}(1 - 0.4x)$$"
                       "as required."),
             verify=["Eq(simplify(diff(x*exp(-2*x/5), x) - "
                     "(1 - Rational(2, 5)*x)*exp(-2*x/5)), 0)"]),
        part("c", "Find the coordinates of the maximum point of the graph.", 3,
             [M1("set $f'(x) = 0$: $1 - 0.4x = 0$ (the exponential is never "
                 "zero)"),
              A1("$x = 2.5$"),
              A1(f"$y = 2.5\\,e^{{-1}} \\approx {ymax9_p}$ — maximum at "
                 f"$(2.5,\\ {ymax9_p})$")],
             answer=f"$(2.5,\\ {ymax9_p})$ (y to 3 sf)",
             solution=("**Plan:** use the derivative from part (b)."
                       "$$f'(x) = (1 - 0.4x)e^{-0.4x} = 0 \\Rightarrow x = 2.5$$"
                       f"$$f(2.5) = 2.5\\,e^{{-1}} = {sig(ymax9, 5)}\\ldots"
                       f" \\approx {ymax9_p}$$"
                       f"The maximum point is $(2.5,\\ {ymax9_p})$."),
             verify=["solve((1 - Rational(2, 5)*x)*exp(-2*x/5), x) == "
                     "[Rational(5, 2)]",
                     f"Abs(Rational(5, 2)*exp(-1) - {ymax9_p}) < {ymax9_tol}"]),
        part("d", "Find the $x$-coordinate of the point of inflexion of the "
                  "graph.", 4,
             [M1("differentiate $f'$ again (product rule on "
                 "$(1 - 0.4x)e^{-0.4x}$)"),
              A1("$f''(x) = (0.16x - 0.8)\\,e^{-0.4x}$"),
              M1("set $f''(x) = 0$"),
              A1("$x = 5$")],
             answer="$x = 5$",
             solution=("**Plan:** the inflexion is where $f''$ changes sign."
                       "$$f''(x) = -0.4e^{-0.4x} + (1 - 0.4x)(-0.4)e^{-0.4x}"
                       " = e^{-0.4x}(0.16x - 0.8)$$"
                       "$$f''(x) = 0 \\Rightarrow 0.16x = 0.8 \\Rightarrow x = 5$$"
                       "($f''$ changes from negative to positive there, "
                       "confirming an inflexion)."),
             verify=["solve(diff(x*exp(-2*x/5), x, 2), x) == [5]",
                     "Eq(simplify(diff(x*exp(-2*x/5), x, 2) - "
                     "(Rational(4, 25)*x - Rational(4, 5))*exp(-2*x/5)), 0)"]),
        part("e", "Find the area of the shaded region.", 4,
             [M1("area $= \\displaystyle\\int_0^5 x\\,e^{-0.4x}\\,dx$"),
              A1("GDC numerical integral set up correctly"),
              A1(f"$= {sig(area9, 5)}\\ldots$"),
              A1(f"area $\\approx {area9_p}$ (accept ${sig(area9, 5)}$)")],
             answer=f"${area9_p}$ square units (3 sf)",
             solution=("**Plan:** on this GDC paper, evaluate "
                       "$\\displaystyle\\int_0^5 x\\,e^{-0.4x}\\,dx$ numerically."
                       f"$$\\int_0^5 x\\,e^{{-0.4x}}\\,dx = {sig(area9, 5)}\\ldots"
                       f" \\approx {area9_p}$$"
                       "(The exact value, via integration by parts, is "
                       "$\\dfrac{25}{4} - \\dfrac{75}{4}e^{-2}$ — a good check.)"),
             verify=[f"Abs(integrate(x*exp(-2*x/5), (x, 0, 5)) - {area9_p}) "
                     f"< {area9_tol}",
                     "Eq(integrate(x*exp(-2*x/5), (x, 0, 5)), "
                     "Rational(25, 4) - Rational(75, 4)*exp(-2))"]),
    ]))


META = {"course": "aa", "level": "sl", "paper": 2, "testId": "ib-practice-1",
        "label": "AA SL Practice Paper 2", "timeMinutes": 90, "totalMarks": 80,
        "calculator": True}

if __name__ == "__main__":
    write_paper(META, QS, "data/ib/aa-sl/ib-practice-1/paper2.json")
