"""AA SL Practice Paper 2 (ib-practice-2) — 90 min, 80 marks, GDC required.

Blueprint (topic x marks):
    Section A (40): Q1 functions 6 | Q2 stats_probability 6
                    Q3 geometry_trig 6 | Q4 number_algebra 6
                    Q5 functions 8 | Q6 calculus 8
    Section B (40): Q7 functions 13 | Q8 stats_probability 12
                    Q9 calculus 15
    Paper totals: functions 27 | stats_probability 18 | geometry_trig 6 |
                  number_algebra 6 | calculus 23
    Paired with Paper 1 (na 13/fn 6/gt 19/sp 17/calc 25), the two papers
    together land near the AA SL blueprint.

GDC paper: answers to 3 significant figures unless exact. Every rounded
answer is computed here (sf3/dp2) and checked in verify[] against the exact
sympy value within tolerance. Figures: Q3 (non-right triangle), Q9
(x e^{-0.5x} with shaded area) — generated by
scripts/test-figures/ib-aa-sl-practice-2.py from the SAME parameters.
"""
import os
import sys
from math import floor, log10

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ibbuild import ROOT, A1, AG, M1, R1, part, question, write_paper  # noqa: E402

from sympy import (Rational, sqrt, pi, Eq, exp, log, sin, cos, erf,  # noqa: F401,E402
                   erfinv, integrate, diff, expand, binomial, symbols, N)

x, t = symbols("x t")


def sf3(v):
    """Round to 3 significant figures; return (printed_string, tolerance)."""
    v = float(v)
    assert v != 0
    d = 2 - floor(log10(abs(v)))
    r = round(v, d)
    printed = str(int(r)) if d <= 0 else f"{r:.{d}f}"
    assert abs(v - r) < 0.499 * 10**(-d), f"ambiguous 3sf rounding for {v}"
    return printed, 0.51 * 10**(-d)


def dp2(v):
    """Round to 2 decimal places (money)."""
    v = float(v)
    r = round(v, 2)
    assert abs(v - r) < 0.00499, f"ambiguous 2dp rounding for {v}"
    return f"{r:.2f}", 0.0051


def sig(v, n=6):
    """Quote an unrounded value to n significant figures (solution text)."""
    v = float(v)
    d = (n - 1) - floor(log10(abs(v)))
    return f"{round(v, d):.{max(d, 0)}f}"


def png(name, alt_en):
    from PIL import Image
    p = os.path.join(ROOT, "public", "ib-figures", name)
    assert os.path.isfile(p), f"figure missing on disk: {p} — run the figure script first"
    with Image.open(p) as im:
        w, h = im.size
    return {"src": f"/ib-figures/{name}", "width": w, "height": h, "alt_en": alt_en}


QS = []

# ── Q1 [6] functions: quadratic, GDC roots ───────────────────────────────
r1 = 2 - sqrt(15) / 3
r2 = 2 + sqrt(15) / 3
r1_p, r1_tol = sf3(N(r1, 12))
r2_p, r2_tol = sf3(N(r2, 12))
assert 3 * 2**2 - 12 * 2 + 7 == -5
QS.append(question(
    "IB-AASL-P2-T2-Q1", 1, "A", "functions", "quadratic_functions",
    contextIntro=("The function $f$ is given by $f(x) = 3x^2 - 12x + 7$."),
    parts=[
        part("a", "Find $f(2)$.", 2,
             [M1("substitute $x = 2$"), A1("$f(2) = -5$")],
             answer="$f(2) = -5$",
             solution=("$$f(2) = 3(2)^2 - 12(2) + 7 = 12 - 24 + 7 = -5$$"),
             verify=["Eq(3*2**2 - 12*2 + 7, -5)"]),
        part("b", "Find the two values of $x$ for which $f(x) = 0$, giving "
             "your answers to three significant figures.", 4,
             [M1("solve $3x^2 - 12x + 7 = 0$ (GDC or quadratic formula)"),
              A1("discriminant $144 - 84 = 60$"),
              A1(f"$x \\approx {r1_p}$"), A1(f"$x \\approx {r2_p}$")],
             answer=f"$x \\approx {r1_p}$ or $x \\approx {r2_p}$",
             solution=("**Plan:** solve the quadratic with the GDC (or formula)."
                       "$$x = \\frac{12 \\pm \\sqrt{144 - 84}}{6} "
                       "= \\frac{12 \\pm \\sqrt{60}}{6} = 2 \\pm "
                       "\\frac{\\sqrt{15}}{3}$$"
                       f"$$x \\approx {r1_p} \\text{{ or }} x \\approx {r2_p}$$"),
             verify=[f"Abs(2 - sqrt(15)/3 - {r1_p}) < {r1_tol}",
                     f"Abs(2 + sqrt(15)/3 - {r2_p}) < {r2_tol}"]),
    ]))

# ── Q2 [6] stats_probability: binomial ───────────────────────────────────
p3 = binomial(10, 3) * Rational(3, 10)**3 * Rational(7, 10)**7
p3_p, p3_tol = sf3(N(p3, 12))
pge1 = 1 - Rational(7, 10)**10
pge1_p, pge1_tol = sf3(N(pge1, 12))
QS.append(question(
    "IB-AASL-P2-T2-Q2", 2, "A", "stats_probability", "binomial_distribution",
    contextIntro=("A biased coin lands heads with probability $0.3$. It is "
                  "tossed 10 times. Let $X$ be the number of heads, so "
                  "$X \\sim B(10,\\ 0.3)$."),
    parts=[
        part("a", "Find $P(X = 3)$, giving your answer to three significant "
             "figures.", 3,
             [M1("binomial: $\\binom{10}{3}(0.3)^3(0.7)^7$ (or GDC)"),
              A1("$= 120 \\cdot 0.027 \\cdot 0.0823\\ldots$"),
              A1(f"$P(X = 3) \\approx {p3_p}$")],
             answer=f"${p3_p}$ (3 sf)",
             solution=("**Plan:** binomial probability with $n = 10$, $p = 0.3$."
                       "$$P(X = 3) = \\binom{10}{3}(0.3)^3(0.7)^7 "
                       f"= {sig(p3, 4)}\\ldots \\approx {p3_p}$$"),
             verify=[f"Abs(binomial(10, 3)*Rational(3, 10)**3*Rational(7, 10)**7 "
                     f"- {p3_p}) < {p3_tol}"]),
        part("b", "Find $P(X \\ge 1)$, giving your answer to three "
             "significant figures.", 3,
             [M1("use the complement $P(X \\ge 1) = 1 - P(X = 0)$"),
              A1("$P(X = 0) = (0.7)^{10}$"),
              A1(f"$P(X \\ge 1) \\approx {pge1_p}$")],
             answer=f"${pge1_p}$ (3 sf)",
             solution=("The complement of \"at least one\" is \"none\":"
                       "$$P(X \\ge 1) = 1 - (0.7)^{10} "
                       f"= {sig(pge1, 4)}\\ldots \\approx {pge1_p}$$"),
             verify=[f"Abs(1 - Rational(7, 10)**10 - {pge1_p}) < {pge1_tol}"]),
    ]))

# ── Q3 [6] geometry_trig: non-right triangle (cos rule), FIGURE ──────────
# PQ = 8, QR = 7, angle Q = 112° = 28*pi/45
angQ = 28 * pi / 45
PR = sqrt(8**2 + 7**2 - 2 * 8 * 7 * cos(angQ))
PR_p, PR_tol = sf3(N(PR, 12))
area3 = Rational(1, 2) * 8 * 7 * sin(angQ)
area3_p, area3_tol = sf3(N(area3, 12))
QS.append(question(
    "IB-AASL-P2-T2-Q3", 3, "A", "geometry_trig", "non_right_triangles",
    contextIntro=("In triangle $PQR$, $PQ = 8$ cm, $QR = 7$ cm and the angle "
                  "$P\\hat{Q}R = 112°$, as shown."),
    figure=png("ib-aasl-p2-t2-q3.png",
               "Triangle PQR with PQ = 8 cm along the base, QR = 7 cm, and "
               "the angle at Q equal to 112 degrees."),
    parts=[
        part("a", "Find $PR$, giving your answer to three significant "
             "figures.", 3,
             [M1("cosine rule $PR^2 = PQ^2 + QR^2 - 2\\,PQ\\,QR\\cos Q$"),
              A1("$PR^2 = 64 + 49 - 112\\cos 112° = 155\\ldots$"),
              A1(f"$PR \\approx {PR_p}$ cm")],
             answer=f"$PR \\approx {PR_p}$ cm (3 sf)",
             solution=("**Plan:** two sides and the included angle → cosine rule."
                       "$$PR^2 = 8^2 + 7^2 - 2(8)(7)\\cos 112° "
                       f"= {sig(N(PR**2), 5)}\\ldots$$"
                       f"$$PR \\approx {PR_p} \\text{{ cm}}$$"),
             verify=[f"Abs(sqrt(64 + 49 - 2*8*7*cos(28*pi/45)) - {PR_p}) "
                     f"< {PR_tol}"]),
        part("b", "Find the area of triangle $PQR$, giving your answer to "
             "three significant figures.", 3,
             [M1("use area $= \\tfrac{1}{2}\\,PQ\\,QR\\sin Q$"),
              A1("$\\tfrac{1}{2}(8)(7)\\sin 112°$"),
              A1(f"area $\\approx {area3_p}$ cm$^2$")],
             answer=f"${area3_p}$ cm$^2$ (3 sf)",
             solution=("$$\\text{Area} = \\tfrac{1}{2}(8)(7)\\sin 112° "
                       f"= {sig(area3, 4)}\\ldots \\approx {area3_p}"
                       " \\text{ cm}^2$$"),
             verify=[f"Abs(Rational(1, 2)*8*7*sin(28*pi/45) - {area3_p}) "
                     f"< {area3_tol}"]),
    ]))

# ── Q4 [6] number_algebra: compound interest ─────────────────────────────
fv = 4000 * Rational(21, 20)**6
fv_p, fv_tol = dp2(N(fv, 12))
assert Rational(21, 20)**8 < Rational(3, 2) < Rational(21, 20)**9
QS.append(question(
    "IB-AASL-P2-T2-Q4", 4, "A", "number_algebra", "finance",
    contextIntro=("An amount of \\$4000 is invested at a nominal annual "
                  "interest rate of 5\\%, compounded annually."),
    parts=[
        part("a", "Find the value of the investment after 6 years, giving "
             "your answer to two decimal places.", 3,
             [M1("use $A = 4000(1.05)^6$"),
              A1("$4000(1.05)^6$"),
              A1(f"$\\approx \\${fv_p}$")],
             answer=f"$\\${fv_p}$",
             solution=("**Plan:** compound-interest formula."
                       "$$A = 4000(1.05)^6 = {v}\\ldots \\approx \\${p}$$"
                       .format(v=sig(fv, 6), p=fv_p)),
             verify=[f"Abs(4000*Rational(21, 20)**6 - {fv_p}) < {fv_tol}"]),
        part("b", "Find the least number of complete years for the "
             "investment to first exceed \\$6000.", 3,
             [M1("solve $4000(1.05)^n > 6000$, i.e. $(1.05)^n > 1.5$"),
              A1("$(1.05)^8 \\approx 1.477 < 1.5 < 1.551 \\approx (1.05)^9$"),
              A1("least $n = 9$ years")],
             answer="$9$ years",
             solution=("**Plan:** find when the multiplier exceeds "
                       "$\\tfrac{6000}{4000} = 1.5$."
                       "$$(1.05)^8 \\approx 1.477, \\quad (1.05)^9 \\approx 1.551$$"
                       "The value first exceeds \\$6000 after $9$ complete "
                       "years."),
             verify=["(Rational(21, 20))**8 < Rational(3, 2)",
                     "(Rational(21, 20))**9 > Rational(3, 2)"]),
    ]))

# ── Q5 [8] functions: exponential model ──────────────────────────────────
P10 = 500 * exp(Rational(8, 10))
P10_p, P10_tol = sf3(N(P10, 12))
tt = 25 * log(4) / 2                                # 500 e^{0.08 t} = 2000
tt_p, tt_tol = sf3(N(tt, 12))
QS.append(question(
    "IB-AASL-P2-T2-Q5", 5, "A", "functions", "exponential_models",
    contextIntro=("The population of a colony of bacteria is modelled by "
                  "$P(t) = 500\\,e^{0.08t}$, where $t$ is the time in hours "
                  "after the colony is first observed."),
    parts=[
        part("a", "Write down the initial population.", 1,
             [A1("$P(0) = 500$")],
             answer="$500$",
             solution=("At $t = 0$, $P(0) = 500 e^{0} = 500$."),
             verify=["Eq(500*exp(0), 500)"]),
        part("b", "Find the population after 10 hours, giving your answer to "
             "three significant figures.", 3,
             [M1("substitute $t = 10$: $500 e^{0.8}$"),
              A1("$500 e^{0.8}$"),
              A1(f"$\\approx {P10_p}$")],
             answer=f"${P10_p}$ (3 sf)",
             solution=("$$P(10) = 500 e^{0.08 \\times 10} = 500 e^{0.8} "
                       f"= {sig(P10, 5)}\\ldots \\approx {P10_p}$$"),
             verify=[f"Abs(500*exp(Rational(8, 10)) - {P10_p}) < {P10_tol}"]),
        part("c", "Find the time taken for the population to reach 2000, "
             "giving your answer to three significant figures.", 4,
             [M1("set $500 e^{0.08t} = 2000$"),
              A1("$e^{0.08t} = 4$"),
              M1("take logarithms: $0.08t = \\ln 4$"),
              A1(f"$t \\approx {tt_p}$ hours")],
             answer=f"$t \\approx {tt_p}$ hours (3 sf)",
             solution=("**Plan:** solve for $t$ with logarithms."
                       "$$500 e^{0.08t} = 2000 \\Rightarrow e^{0.08t} = 4$$"
                       "$$0.08t = \\ln 4 \\Rightarrow t = \\frac{\\ln 4}{0.08} "
                       f"= {sig(tt, 5)}\\ldots \\approx {tt_p}$$"),
             verify=[f"Abs(25*log(4)/2 - {tt_p}) < {tt_tol}",
                     "Eq(500*exp(Rational(8, 100)*(25*log(4)/2)), 2000)"]),
    ]))

# ── Q6 [8] calculus: kinematics (exact integral) ─────────────────────────
v6 = 3 * t**2 - 12 * t + 9
assert v6.subs(t, 1) == 0 and v6.subs(t, 3) == 0
assert integrate(v6, (t, 0, 4)) == 4
QS.append(question(
    "IB-AASL-P2-T2-Q6", 6, "A", "calculus", "kinematics",
    contextIntro=("A particle moves in a straight line. Its velocity, in "
                  "metres per second, at time $t$ seconds is "
                  "$v(t) = 3t^2 - 12t + 9$ for $t \\ge 0$."),
    parts=[
        part("a", "Find the times at which the particle is instantaneously "
             "at rest.", 3,
             [M1("set $v(t) = 0$: $3(t - 1)(t - 3) = 0$"),
              A1("$t = 1$"), A1("$t = 3$ (seconds)")],
             answer="$t = 1$ s and $t = 3$ s",
             solution=("**Plan:** the particle is at rest when $v = 0$."
                       "$$3t^2 - 12t + 9 = 3(t - 1)(t - 3) = 0 "
                       "\\Rightarrow t = 1 \\text{ or } t = 3$$"),
             verify=["Eq(3*1**2 - 12*1 + 9, 0)", "Eq(3*3**2 - 12*3 + 9, 0)"]),
        part("b", "Find the displacement of the particle from its starting "
             "position after 4 seconds.", 5,
             [M1("displacement $= \\int_0^4 v(t)\\,dt$"),
              A1("antiderivative $t^3 - 6t^2 + 9t$"),
              A1("evaluate at $t = 4$: $64 - 96 + 36$"),
              M1("subtract the value at $t = 0$ (which is 0)"),
              A1("displacement $= 4$ m")],
             answer="$4$ m",
             solution=("Displacement is the integral of velocity:"
                       "$$\\int_0^4 (3t^2 - 12t + 9)\\,dt "
                       "= \\left[t^3 - 6t^2 + 9t\\right]_0^4$$"
                       "$$= (64 - 96 + 36) - 0 = 4 \\text{ m}$$"),
             verify=["Eq(integrate(3*t**2 - 12*t + 9, (t, 0, 4)), 4)"]),
    ]))

# ── Q7 [13] functions (Section B): trigonometric model ───────────────────
# h(t) = 6 + 4 sin(pi t / 6); h'(t) = (2 pi / 3) cos(pi t / 6)
hprime2 = (2 * pi / 3) * cos(pi * 2 / 6)
hp2_p, hp2_tol = sf3(N(hprime2, 12))
assert 6 + 4 * sin(pi * 3 / 6) == 10          # max at t = 3
assert 6 + 4 * sin(pi * 1 / 6) == 8           # h = 8 first at t = 1
QS.append(question(
    "IB-AASL-P2-T2-Q7", 7, "B", "functions", "trig_models",
    contextIntro=("The depth of water in a harbour is modelled by "
                  "$h(t) = 6 + 4\\sin\\!\\left(\\dfrac{\\pi t}{6}\\right)$, "
                  "where $h$ is the depth in metres and $t$ is the time in "
                  "hours after midday, for $0 \\le t \\le 12$."),
    parts=[
        part("a", "Write down the depth of the water at midday.", 1,
             [A1("$h(0) = 6$ m")],
             answer="$6$ m",
             solution=("At $t = 0$, $\\sin 0 = 0$, so $h(0) = 6$ m."),
             verify=["Eq(6 + 4*sin(0), 6)"]),
        part("b", "Find the maximum depth of the water and the time at which "
             "it first occurs.", 3,
             [M1("the sine reaches its maximum 1 when $\\tfrac{\\pi t}{6} "
                 "= \\tfrac{\\pi}{2}$"),
              A1("maximum depth $6 + 4 = 10$ m"),
              A1("first at $t = 3$ hours")],
             answer="maximum depth $10$ m at $t = 3$ hours",
             solution=("**Plan:** the maximum of $\\sin$ is 1."
                       "$$\\frac{\\pi t}{6} = \\frac{\\pi}{2} "
                       "\\Rightarrow t = 3$$"
                       "$$h(3) = 6 + 4(1) = 10 \\text{ m}$$"),
             verify=["Eq(6 + 4*sin(pi*3/6), 10)"]),
        part("c", "Find the first time after midday when the depth is "
             "exactly 8 m.", 4,
             [M1("set $h(t) = 8$: $\\sin\\!\\left(\\tfrac{\\pi t}{6}\\right) "
                 "= \\tfrac{1}{2}$"),
              A1("$\\tfrac{\\pi t}{6} = \\tfrac{\\pi}{6}$"),
              A1("$t = 1$"),
              A1("first time is $t = 1$ hour after midday")],
             answer="$t = 1$ hour",
             solution=("**Plan:** solve $h(t) = 8$ for the first positive $t$."
                       "$$6 + 4\\sin\\!\\left(\\tfrac{\\pi t}{6}\\right) = 8 "
                       "\\Rightarrow \\sin\\!\\left(\\tfrac{\\pi t}{6}\\right) "
                       "= \\tfrac{1}{2}$$"
                       "$$\\frac{\\pi t}{6} = \\frac{\\pi}{6} "
                       "\\Rightarrow t = 1$$"),
             verify=["Eq(6 + 4*sin(pi*1/6), 8)"]),
        part("d", "Find the rate of change of the depth, in metres per hour, "
             "at $t = 2$, giving your answer to three significant figures.", 5,
             [M1("differentiate: $h'(t) = \\tfrac{2\\pi}{3}"
                 "\\cos\\!\\left(\\tfrac{\\pi t}{6}\\right)$"),
              A1("$h'(t) = \\tfrac{2\\pi}{3}\\cos\\!\\left(\\tfrac{\\pi t}{6}"
                 "\\right)$"),
              A1("at $t = 2$: $\\cos\\tfrac{\\pi}{3} = \\tfrac{1}{2}$"),
              M1("$h'(2) = \\tfrac{2\\pi}{3}\\cdot\\tfrac{1}{2} = \\tfrac{\\pi}{3}$"),
              A1(f"$\\approx {hp2_p}$ m per hour")],
             answer=f"$h'(2) = \\dfrac{{\\pi}}{{3}} \\approx {hp2_p}$ m/h",
             solution=("Differentiate with the chain rule:"
                       "$$h'(t) = 4 \\cdot \\frac{\\pi}{6}"
                       "\\cos\\!\\left(\\frac{\\pi t}{6}\\right) "
                       "= \\frac{2\\pi}{3}\\cos\\!\\left(\\frac{\\pi t}{6}\\right)$$"
                       "At $t = 2$, $\\cos\\tfrac{\\pi}{3} = \\tfrac{1}{2}$, so"
                       "$$h'(2) = \\frac{2\\pi}{3}\\cdot\\frac{1}{2} "
                       f"= \\frac{{\\pi}}{{3}} \\approx {hp2_p}$$"),
             verify=["Eq(simplify(diff(6 + 4*sin(pi*t/6), t) - (2*pi/3)*cos(pi*t/6)), 0)",
                     f"Abs((2*pi/3)*cos(pi/3) - {hp2_p}) < {hp2_tol}"]),
    ]))

# ── Q8 [12] stats_probability (Section B): normal distribution ───────────
mu, sd = 50, 4


def Phi(z):
    return (1 + erf(z / sqrt(2))) / 2


p45 = Phi(Rational(45 - mu, sd))
p45_p, p45_tol = sf3(N(p45, 12))
pmid = Phi(Rational(54 - mu, sd)) - Phi(Rational(46 - mu, sd))
pmid_p, pmid_tol = sf3(N(pmid, 12))
z90 = sqrt(2) * erfinv(Rational(4, 5))              # Phi(z) = 0.9
k90 = mu + sd * z90
k90_p, k90_tol = sf3(N(k90, 12))
QS.append(question(
    "IB-AASL-P2-T2-Q8", 8, "B", "stats_probability", "normal_distribution",
    contextIntro=("The times taken by students to complete a puzzle are "
                  "normally distributed with mean 50 seconds and standard "
                  "deviation 4 seconds. Let $X$ be the time in seconds, so "
                  "$X \\sim N(50,\\ 4^2)$."),
    parts=[
        part("a", "Write down $P(X < 50)$.", 1,
             [A1("$P(X < 50) = 0.5$ (mean is the centre of symmetry)")],
             answer="$0.5$",
             solution=("The normal curve is symmetric about its mean, so "
                       "$P(X < 50) = 0.5$."),
             verify=["Eq((1 + erf(0))/2, Rational(1, 2))"]),
        part("b", "Find $P(X < 45)$, giving your answer to three significant "
             "figures.", 3,
             [M1("standardise or use the GDC: $z = \\tfrac{45 - 50}{4} "
                 "= -1.25$"),
              A1("normal cdf with upper 45"),
              A1(f"$P(X < 45) \\approx {p45_p}$")],
             answer=f"${p45_p}$ (3 sf)",
             solution=("**Plan:** GDC normal cdf, or standardise to $z = -1.25$."
                       f"$$P(X < 45) = {sig(p45, 4)}\\ldots \\approx {p45_p}$$"),
             verify=[f"Abs((1 + erf(Rational(-5, 4)/sqrt(2)))/2 - {p45_p}) "
                     f"< {p45_tol}"]),
        part("c", "Find $P(46 < X < 54)$, giving your answer to three "
             "significant figures.", 4,
             [M1("GDC normal cdf between 46 and 54"),
              A1("standardised bounds $z = \\pm 1$"),
              A1(f"$= {sig(pmid, 4)}\\ldots$"),
              A1(f"$\\approx {pmid_p}$")],
             answer=f"${pmid_p}$ (3 sf)",
             solution=("**Plan:** the interval is $\\mu \\pm 1\\sigma$."
                       f"$$P(46 < X < 54) = {sig(pmid, 4)}\\ldots "
                       f"\\approx {pmid_p}$$"),
             verify=[f"Abs((erf(1/sqrt(2)) - erf(-1/sqrt(2)))/2 - {pmid_p}) "
                     f"< {pmid_tol}"]),
        part("d", "Find the time $k$ such that 90\\% of students finish in "
             "less than $k$ seconds, giving your answer to three significant "
             "figures.", 4,
             [M1("$P(X < k) = 0.9$ — inverse normal"),
              A1(f"$z \\approx {sig(z90, 4)}$"),
              M1("$k = 50 + 4z$"),
              A1(f"$k \\approx {k90_p}$ seconds")],
             answer=f"$k \\approx {k90_p}$ s (3 sf)",
             solution=("**Plan:** inverse normal with area 0.9."
                       f"$$z = {sig(z90, 4)}\\ldots \\Rightarrow "
                       f"k = 50 + 4({sig(z90, 4)}\\ldots) "
                       f"= {sig(k90, 5)}\\ldots \\approx {k90_p}$$"),
             verify=[f"Abs((1 + erf(({sig(k90, 8)} - 50)/(4*sqrt(2))))/2 - "
                     f"Rational(9, 10)) < 0.0005",
                     f"Abs(sqrt(2)*erfinv(Rational(4, 5)) - {sig(z90, 4)}) "
                     f"< 0.0005"]),
    ]))

# ── Q9 [15] calculus (Section B): x e^{-0.5x}, area, tangent, FIGURE ─────
f9 = x * exp(-x / 2)
area9 = integrate(f9, (x, 0, 4))
assert area9 == 4 - 12 * exp(-2)
area9_p, area9_tol = sf3(N(area9, 12))
fmax = 2 * exp(-1)
fmax_p, fmax_tol = sf3(N(fmax, 12))
QS.append(question(
    "IB-AASL-P2-T2-Q9", 9, "B", "calculus", "integration_area",
    contextIntro=("The function $f$ is defined by $f(x) = x\\,e^{-0.5x}$ for "
                  "$x \\ge 0$. The region $R$ is bounded by the graph of $f$, "
                  "the $x$-axis and the line $x = 4$, as shaded."),
    figure=png("ib-aasl-p2-t2-q9.png",
               "Curve y = x e^{-0.5x} rising to a peak near x = 2 then "
               "decaying; the region R between the curve and the x-axis on "
               "0 <= x <= 4 is shaded, with a dashed vertical line at x = 4."),
    parts=[
        part("a", "Find $f'(x)$.", 3,
             [M1("apply the product rule to $x \\cdot e^{-0.5x}$"),
              A1("$f'(x) = e^{-0.5x} + x\\left(-\\tfrac{1}{2}e^{-0.5x}\\right)$"),
              A1("$f'(x) = e^{-0.5x}(1 - 0.5x)$")],
             answer="$f'(x) = e^{-0.5x}(1 - 0.5x)$",
             solution=("**Plan:** product rule with $u = x$, $v = e^{-0.5x}$."
                       "$$f'(x) = (1)e^{-0.5x} + x\\left(-\\tfrac{1}{2}"
                       "e^{-0.5x}\\right) = e^{-0.5x}\\left(1 - \\tfrac{x}{2}"
                       "\\right)$$"),
             verify=["Eq(simplify(diff(x*exp(-x/2), x) - exp(-x/2)*(1 - x/2)), 0)"]),
        part("b", "Find the $x$-coordinate of the local maximum of the graph "
             "of $f$.", 3,
             [M1("set $f'(x) = 0$; since $e^{-0.5x} \\ne 0$, need $1 - 0.5x = 0$"),
              A1("$x = 2$"),
              R1("this is a maximum (the curve rises then falls)")],
             answer="$x = 2$",
             solution=("**Plan:** stationary point where $f'(x) = 0$."
                       "$$e^{-0.5x}(1 - 0.5x) = 0 \\Rightarrow 1 - 0.5x = 0 "
                       "\\Rightarrow x = 2$$"
                       "For $x < 2$, $f' > 0$ and for $x > 2$, $f' < 0$, so "
                       "$x = 2$ gives the local maximum."),
             verify=["Eq((exp(-x/2)*(1 - x/2)).subs(x, 2), 0)"]),
        part("c", "Find the area of the region $R$, giving your answer to "
             "three significant figures.", 5,
             [M1("area $= \\int_0^4 x\\,e^{-0.5x}\\,dx$"),
              A1("integrate by parts: $\\left[-2x\\,e^{-0.5x}\\right]_0^4 "
                 "+ \\int_0^4 2e^{-0.5x}\\,dx$"),
              M1("evaluate the exact value $4 - 12e^{-2}$"),
              A1(f"$= {sig(area9, 4)}\\ldots$"),
              A1(f"area $\\approx {area9_p}$")],
             answer=f"${area9_p}$ (3 sf)",
             solution=("**Plan:** integrate by parts (or use the GDC)."
                       "$$\\int_0^4 x e^{-0.5x}\\,dx "
                       "= \\left[-2x e^{-0.5x}\\right]_0^4 "
                       "+ \\int_0^4 2 e^{-0.5x}\\,dx$$"
                       "$$= -8e^{-2} + \\left[-4e^{-0.5x}\\right]_0^4 "
                       "= 4 - 12e^{-2} "
                       f"= {sig(area9, 4)}\\ldots \\approx {area9_p}$$"),
             verify=["Eq(integrate(x*exp(-x/2), (x, 0, 4)), 4 - 12*exp(-2))",
                     f"Abs(4 - 12*exp(-2) - {area9_p}) < {area9_tol}"]),
        part("d", "Find the equation of the tangent to the graph of $f$ at "
             "the origin.", 4,
             [M1("evaluate $f(0)$ and the gradient $f'(0)$"),
              A1("$f(0) = 0$ and $f'(0) = e^{0}(1 - 0) = 1$"),
              M1("tangent $y - 0 = 1(x - 0)$"),
              A1("$y = x$")],
             answer="$y = x$",
             solution=("At the origin $f(0) = 0$, and the gradient is"
                       "$$f'(0) = e^{0}(1 - 0) = 1.$$"
                       "So the tangent is $y - 0 = 1(x - 0)$, i.e. $y = x$."),
             verify=["Eq((x*exp(-x/2)).subs(x, 0), 0)",
                     "Eq((exp(-x/2)*(1 - x/2)).subs(x, 0), 1)"]),
    ]))

META = {"course": "aa", "level": "sl", "paper": 2, "testId": "ib-practice-2",
        "label": "AA SL Practice Paper 2", "timeMinutes": 90,
        "totalMarks": 80, "calculator": True}

if __name__ == "__main__":
    write_paper(META, QS, "data/ib/aa-sl/ib-practice-2/paper2.json")
