// The client-safe view of the problem bank: which topics exist, their
// display strings, and their forms' identity metadata (id, unit, level) —
// everything the bank HUB page and the ratings card need to render lists
// and compute mastery, at ~55 KB instead of the ~9 MB corpus.
//
// Generated by scripts/build_problembank.py alongside the topic files, so
// it can never drift from them (lib/bank-split.test.ts re-checks the sync
// against lib/bank-data.ts anyway). The corpus itself stays server-side —
// see the header of lib/bank-data.ts.

import manifest from "@/data/bank-manifest.json";
import type { BankProgress } from "@/lib/problem-bank";

export type BankFormMeta = {
  id: string;
  unit: string;
  level: 1 | 2 | 3;
};

export type BankTopicMeta = {
  slug: string;
  title: string;
  titleMn: string;
  blurb: string;
  /** False for the hub-owned banks (sat, ib-*), which live in their exam hubs. */
  courseLadder: boolean;
  unitCount: number;
  problemCount: number;
  forms: BankFormMeta[];
};

const ALL: BankTopicMeta[] = manifest as BankTopicMeta[];

/** Every bank topic, hub-owned ones included. */
export function bankManifest(): BankTopicMeta[] {
  return ALL;
}

/** The /math course-ladder topics — same set as bank-data's getBankTopics(). */
export function courseLadderManifest(): BankTopicMeta[] {
  return ALL.filter((t) => t.courseLadder);
}

/** Mastery from form metadata — the manifest twin of topicMastery(). */
export function manifestMastery(
  topic: BankTopicMeta,
  progress: BankProgress,
): { mastered: number; total: number } {
  return {
    mastered: topic.forms.filter((f) => progress.forms[f.id]?.mastered).length,
    total: topic.forms.length,
  };
}
