-- Legacy attempts.topic / attempts.subtopic -> skill_id.
-- GENERATED by scripts/skills/topic_mapping.py. Do not hand-edit.
--
-- Every ЭЕШ row was checked against the question body, not the label: four of
-- them are mapped to a DIFFERENT skill than their production topic implies, and
-- one ('logarithms / negative exponents') has a production topic that is simply
-- wrong. Backfilling from the label instead of the item would have written that
-- error permanently onto student records.
--
-- Rows with confidence 'awaiting_sat_graph' have no skill and are intentionally
-- inert until SAT skills are authored.

begin;

insert into attempt_topic_skill_map (hub, topic, subtopic, skill_id, is_primary, confidence)
values
  ('esh', 'algebra', 'algebraic expressions', 'algebraic-expressions', true, 'high'),
  ('esh', 'algebra', 'equations with radicals', 'radical-equations', true, 'high'),
  ('esh', 'algebra', 'factoring', 'factor-theorem', true, 'high'),
  ('esh', 'algebra', 'inequality with integer solutions', 'linear-inequality-one-variable', true, 'high'),
  ('esh', 'algebra', 'polynomial remainder', 'remainder-theorem', true, 'high'),
  ('esh', 'algebra', 'ratio', 'percent-and-proportion', true, 'medium'),
  ('esh', 'algebra', 'system of equations', 'systems-nonlinear', true, 'medium'),
  ('esh', 'algebra', 'system of equations', 'logarithmic-equations', false, 'medium'),
  ('esh', 'arithmetic', 'fractions', 'fraction-arithmetic', true, 'high'),
  ('esh', 'functions', 'composite function', 'composite-functions', true, 'high'),
  ('esh', 'functions', 'function evaluation', 'function-notation', true, 'high'),
  ('esh', 'functions', 'парабол, экстремум', 'quadratic-function-vertex', true, 'high'),
  ('esh', 'logarithms', 'negative exponents', 'integer-powers', true, 'high'),
  ('esh', 'sequences', 'geometric sequence', 'geometric-sequence', true, 'high'),
  ('esh', 'set_theory', 'union', 'set-operations', true, 'high'),
  ('esh', 'complex_numbers', 'division', 'complex-conjugate-division', true, 'high'),
  ('esh', 'geometry', 'circle tangent to line', 'circle-tangent', true, 'high'),
  ('esh', 'geometry', 'cylinder', 'cylinder', true, 'high'),
  ('esh', 'geometry', 'geometric transformations, area', 'homothety', true, 'medium'),
  ('esh', 'geometry', 'geometric transformations, area', 'reflection', false, 'medium'),
  ('esh', 'geometry', 'median of a triangle', 'triangle-medians', true, 'high'),
  ('esh', 'geometry', 'trapezoid with inscribed circle', 'inscribed-circumscribed-circles', true, 'high'),
  ('esh', 'geometry', 'гурвалжин пирамид', 'pyramid-volume-surface', true, 'high'),
  ('esh', 'geometry', 'тэгш өнцөгт параллелепипед', 'prism-volume-surface', true, 'high'),
  ('esh', 'linear_algebra', 'dot product', 'dot-product', true, 'high'),
  ('esh', 'linear_algebra', 'matrix dimensions', 'matrix-dimensions', true, 'high'),
  ('esh', 'linear_algebra', 'translation vector', 'translation', true, 'high'),
  ('esh', 'linear_algebra', 'vector arithmetic', 'vector-arithmetic', true, 'high'),
  ('esh', 'linear_algebra', 'vectors in parallelogram', 'vectors-in-polygons', true, 'high'),
  ('esh', 'trigonometry', 'sine rule', 'sine-rule', true, 'high'),
  ('esh', 'trigonometry', 'trigonometric expressions', 'trig-simplification', true, 'high'),
  ('esh', 'calculus', 'antiderivative', 'antiderivative-power', true, 'high'),
  ('esh', 'calculus', 'area between curves', 'area-between-curves', true, 'high'),
  ('esh', 'calculus', 'definite integral', 'definite-integral', true, 'high'),
  ('esh', 'calculus', 'derivatives', 'derivative-trig', true, 'high'),
  ('esh', 'calculus', 'tangent slope', 'tangent-line', true, 'high'),
  ('esh', 'probability', 'divisibility probability', 'addition-rule', true, 'medium'),
  ('esh', 'probability', 'expected value', 'expected-value', true, 'high'),
  ('esh', 'probability', 'variance (hypergeometric)', 'variance-of-random-variable', true, 'high'),
  ('esh', 'probability', 'магадлал, шооны туршилт', 'classical-probability', true, 'medium'),
  ('esh', 'probability', 'магадлал, шооны туршилт', 'sample-space-and-events', false, 'medium'),
  ('esh', 'statistics', 'median', 'mean-median-mode', true, 'high'),
  ('esh', 'statistics', 'standard deviation', 'variance-and-sd', true, 'high'),
  ('sat', 'advanced-math', 'equivalent_expressions', NULL, true, 'awaiting_sat_graph'),
  ('sat', 'advanced-math', 'nonlinear_equations_systems', NULL, true, 'awaiting_sat_graph'),
  ('sat', 'advanced-math', 'nonlinear_functions', NULL, true, 'awaiting_sat_graph'),
  ('sat', 'algebra', 'linear_equations_one_var', NULL, true, 'awaiting_sat_graph'),
  ('sat', 'algebra', 'linear_equations_two_var', NULL, true, 'awaiting_sat_graph'),
  ('sat', 'algebra', 'linear_functions', NULL, true, 'awaiting_sat_graph'),
  ('sat', 'algebra', 'linear_inequalities', NULL, true, 'awaiting_sat_graph'),
  ('sat', 'algebra', 'systems_two_linear', NULL, true, 'awaiting_sat_graph'),
  ('sat', 'geometry-trig', 'area_volume', NULL, true, 'awaiting_sat_graph'),
  ('sat', 'geometry-trig', 'circles', NULL, true, 'awaiting_sat_graph'),
  ('sat', 'geometry-trig', 'lines_angles_triangles', NULL, true, 'awaiting_sat_graph'),
  ('sat', 'geometry-trig', 'right_triangles_trig', NULL, true, 'awaiting_sat_graph'),
  ('sat', 'problem-solving-data', 'one_var_data', NULL, true, 'awaiting_sat_graph'),
  ('sat', 'problem-solving-data', 'percentages', NULL, true, 'awaiting_sat_graph'),
  ('sat', 'problem-solving-data', 'probability_conditional', NULL, true, 'awaiting_sat_graph'),
  ('sat', 'problem-solving-data', 'ratios_rates_units', NULL, true, 'awaiting_sat_graph'),
  ('sat', 'problem-solving-data', 'two_var_data_models', NULL, true, 'awaiting_sat_graph')
on conflict do nothing;

commit;
