#!/usr/bin/env python3
"""Generate the primary-band renumber redirects.

On 2026-08-13 the primary band moved onto the ministry's grade labels:
/math/3 -> /math/2, /math/4 -> /math/3, /math/5 -> /math/4. Every link a
student, parent or teacher had saved into the old grades would otherwise
404 — including deep lesson, practice and test URLs.

This writes data/primary/renumber-redirects.json, which next.config.mjs
reads at build time. One rule per (old grade, topic slug), matching the
topic and everything under it.

The one case that CANNOT be redirected: a slug that exists in both the old
grade and the NEW grade wearing the same number. Only `addition-and-
subtraction` collides (old grade 4's and old grade 5's units share the
slug), so /math/4/addition-and-subtraction stays pointing at the live new
grade-4 unit rather than redirecting to grade 3 — the live URL must win
over a historical one. That collision is recorded in the JSON so the
gate (scripts/verify-primary-renumber.test.ts) can assert it is the ONLY
one and that nothing else was silently dropped.

Run: python3 scripts/primary/build_renumber_redirects.py
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "data", "primary", "renumber-redirects.json")

# old grade -> new grade. The band shifted down exactly one year.
SHIFT = {3: 2, 4: 3, 5: 4}


def spine_slugs(source, name):
    m = re.search(rf"export const {name}: GradeSpineEntry\[\] = \[(.*?)\n\];", source, re.S)
    if not m:
        raise SystemExit(f"{name} not found in lib/genmath-spines.ts")
    return re.findall(r'slug: "([a-z0-9-]+)"', m.group(1))


def main():
    src = open(os.path.join(ROOT, "lib", "genmath-spines.ts"), encoding="utf-8").read()
    # The new spines ARE the old ones, one label down: new grade N holds what
    # old grade N+1 taught. So old grade G's topics == new grade SHIFT[G]'s.
    new_slugs = {g: spine_slugs(src, f"GRADE{g}_SPINE") for g in (2, 3, 4)}

    rules, collisions = [], []
    for old_grade, new_grade in sorted(SHIFT.items()):
        moved = new_slugs[new_grade]  # what that grade taught before the move
        # slugs live at the OLD grade's number today (only if that number is
        # still a real grade — /math/5 no longer is)
        still_live = set(new_slugs.get(old_grade, []))
        for slug in moved:
            if slug in still_live:
                collisions.append({"slug": slug, "oldGrade": old_grade, "newGrade": new_grade,
                                   "why": "the slug also names a LIVE unit of the new grade "
                                          "wearing the old number; the live URL wins"})
                continue
            rules.append({
                "source": f"/math/{old_grade}/{slug}/:rest*",
                "destination": f"/math/{new_grade}/{slug}/:rest*",
                "permanent": True,
            })
        # the bare grade index, when that number no longer resolves
        if old_grade not in new_slugs:
            rules.append({"source": f"/math/{old_grade}",
                          "destination": f"/math/{new_grade}",
                          "permanent": False})

    data = {
        "note": "Primary-band renumber (2026-08-13): the band moved onto the "
                "ministry's grade labels, so every saved link into the old "
                "grades is redirected to where that exact content now lives. "
                "Generated by scripts/primary/build_renumber_redirects.py and "
                "asserted by scripts/verify-primary-renumber.test.ts. The bare "
                "/math/5 rule is a TRANSITION redirect: remove it when the new "
                "grade 5 course is authored.",
        "shift": {str(k): v for k, v in SHIFT.items()},
        "collisions": collisions,
        "redirects": rules,
    }
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(data, fh, ensure_ascii=False, indent=2)
        fh.write("\n")
    print(f"wrote {os.path.relpath(OUT, ROOT)} — {len(rules)} redirects, "
          f"{len(collisions)} unredirectable collision(s)")


if __name__ == "__main__":
    main()
