#!/usr/bin/env python3
"""Problem-bank assembler.

Each topic's problems are generated by a self-contained module in scripts/pb/
(one file per topic, each exposing build() -> topic dict). This script imports
all of them, writes data/problembank/<slug>.json, and reports counts. Every
answer, distractor, and sympy check is COMPUTED in those modules, so the bank
inherits the platform's zero-mistake discipline.

Regenerate:  python3 scripts/build_problembank.py
Verify:      npm run verify:bank
"""
import importlib.util
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PB_DIR = os.path.join(ROOT, "scripts", "pb")
OUT = os.path.join(ROOT, "data", "problembank")
os.makedirs(OUT, exist_ok=True)

# Subjects mirror the course ladder: slug -> generator module in scripts/pb/.
# Order = the import order in lib/problem-bank.ts (hub display order).
# The old exam-topic modules (algebra.py, functions.py, ...) remain as form
# LIBRARIES that these subject modules remap from — they are no longer topics.
SUBJECTS = [
    ("algebra-1", "algebra_1"),
    ("algebra-2", "algebra_2"),
    ("geometry", "geometry_course"),
    ("trigonometry", "trigonometry_course"),
    ("solid-geometry", "solid_geometry"),
]


def load_build(modname):
    path = os.path.join(PB_DIR, f"{modname}.py")
    spec = importlib.util.spec_from_file_location(f"pb_{modname}", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.build


def main():
    grand_forms = grand_vars = 0
    for slug, modname in SUBJECTS:
        topic = load_build(modname)()
        assert topic["slug"] == slug, f"{slug}: build() returned slug {topic['slug']!r}"
        n_forms = len(topic["forms"])
        n_vars = sum(len(f["variants"]) for f in topic["forms"])
        per_unit = {u["id"]: 0 for u in topic["units"]}
        for f in topic["forms"]:
            per_unit[f["unit"]] += len(f["variants"])
        empty = [u for u, n in per_unit.items() if n == 0]
        grand_forms += n_forms
        grand_vars += n_vars
        path = os.path.join(OUT, f"{slug}.json")
        with open(path, "w") as fh:
            json.dump(topic, fh, indent=2, ensure_ascii=False)
            fh.write("\n")
        print(f"wrote {slug}.json: {len(topic['units'])} units, {n_forms} forms, "
              f"{n_vars} variants" + (f"  EMPTY UNITS: {','.join(empty)}" if empty else ""))
    print(f"TOTAL: {len(SUBJECTS)} subjects, {grand_forms} forms, {grand_vars} variants")


if __name__ == "__main__":
    main()
