#!/usr/bin/env python3
"""Problem-bank assembler.

Each topic's problems are generated by a self-contained module in scripts/pb/
(one file per topic, each exposing build() -> topic dict). This script imports
all of them, writes data/problembank/<slug>.json, and reports counts. Every
answer, distractor, and sympy check is COMPUTED in those modules, so the bank
inherits the platform's zero-mistake discipline.

Regenerate:  python3 scripts/build_problembank.py
Verify:      npm run verify:bank
"""
import importlib.util
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PB_DIR = os.path.join(ROOT, "scripts", "pb")
OUT = os.path.join(ROOT, "data", "problembank")
os.makedirs(OUT, exist_ok=True)

# Subjects mirror the course ladder: slug -> generator module in scripts/pb/.
# Order = the import order in lib/problem-bank.ts (hub display order).
# The old exam-topic modules (algebra.py, functions.py, ...) remain as form
# LIBRARIES that these subject modules remap from — they are no longer topics.
SUBJECTS = [
    ("algebra-1", "algebra_1"),
    ("algebra-2", "algebra_2"),
    ("geometry", "geometry_course"),
    ("trigonometry", "trigonometry_course"),
    ("solid-geometry", "solid_geometry"),
    ("prob-stats", "prob_stats"),
    ("precalculus", "precalculus"),
    ("calculus", "calculus"),
    ("vectors-matrices", "vectors_matrices"),
    ("integrated-1", "integrated_1"),
    ("integrated-2", "integrated_2"),
    # Band exit levels: Grade 9 (Mid school) and Grade 12 (High school).
    # Their banks double as the source pools for the band exit exams
    # (scripts/exams/build_band_exams.py).
    ("9", "grade9"),
    ("12", "grade12"),
    # Hub-owned banks (not part of the /math course ladder): the SAT hub's
    # topic practice (four Digital SAT domains) and the IB hub's SL/HL banks
    # (five syllabus topics per tier).
    ("sat", "sat"),
    ("ib-sl", "ib_sl"),
    ("ib-hl", "ib_hl"),
]


def load_extras():
    """scripts/pb/extras.py adds dense forms to the subjects authored before
    the ~36-variants-per-form standard. One integration point, so the older
    generators need no surgery."""
    path = os.path.join(PB_DIR, "extras.py")
    spec = importlib.util.spec_from_file_location("pb_extras", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.extra_forms


def load_build(modname):
    path = os.path.join(PB_DIR, f"{modname}.py")
    spec = importlib.util.spec_from_file_location(f"pb_{modname}", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.build


# Hub-owned banks live in their exam hubs, not in the /math course-ladder
# list. The manifest carries the flag so client code (bank hub page, ratings
# card) can iterate the ladder without importing any topic data.
HUB_BANKS = {"sat", "ib-sl", "ib-hl"}


def main():
    grand_forms = grand_vars = 0
    extra_forms = load_extras()
    manifest = []
    for slug, modname in SUBJECTS:
        topic = load_build(modname)()
        topic["forms"] = topic["forms"] + extra_forms(slug)
        assert topic["slug"] == slug, f"{slug}: build() returned slug {topic['slug']!r}"
        n_forms = len(topic["forms"])
        n_vars = sum(len(f["variants"]) for f in topic["forms"])
        per_unit = {u["id"]: 0 for u in topic["units"]}
        for f in topic["forms"]:
            per_unit[f["unit"]] += len(f["variants"])
        empty = [u for u, n in per_unit.items() if n == 0]
        grand_forms += n_forms
        grand_vars += n_vars
        path = os.path.join(OUT, f"{slug}.json")
        with open(path, "w") as fh:
            json.dump(topic, fh, indent=2, ensure_ascii=False)
            fh.write("\n")
        manifest.append({
            "slug": slug,
            "title": topic["title"],
            "titleMn": topic["titleMn"],
            "blurb": topic["blurb"],
            "courseLadder": slug not in HUB_BANKS,
            "unitCount": len(topic["units"]),
            "problemCount": n_vars,
            "forms": [{"id": f["id"], "unit": f["unit"], "level": f["level"]}
                      for f in topic["forms"]],
        })
        print(f"wrote {slug}.json: {len(topic['units'])} units, {n_forms} forms, "
              f"{n_vars} variants" + (f"  EMPTY UNITS: {','.join(empty)}" if empty else ""))

    # The client-safe manifest: everything the bank HUB page and the ratings
    # card need (titles, counts, form ids/units/levels) without a single
    # problem statement. ~25 KB instead of the ~9 MB corpus — the corpus
    # itself must only ever be imported server-side (lib/bank-data.ts).
    # Lives OUTSIDE data/problembank/ so verify-problembank's glob of topic
    # files does not try to validate it as a topic.
    manifest_path = os.path.join(ROOT, "data", "bank-manifest.json")
    with open(manifest_path, "w") as fh:
        json.dump(manifest, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    print(f"wrote data/bank-manifest.json: {len(manifest)} topics")
    print(f"TOTAL: {len(SUBJECTS)} subjects, {grand_forms} forms, {grand_vars} variants")


if __name__ == "__main__":
    main()
