#!/usr/bin/env python3
"""Problem-bank assembler.

Each topic's problems are generated by a self-contained module in scripts/pb/
(one file per topic, each exposing build() -> topic dict). This script imports
all of them, writes data/problembank/<slug>.json, and reports counts. Every
answer, distractor, and sympy check is COMPUTED in those modules, so the bank
inherits the platform's zero-mistake discipline.

Regenerate:  python3 scripts/build_problembank.py
Verify:      npm run verify:bank
"""
import importlib.util
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PB_DIR = os.path.join(ROOT, "scripts", "pb")
OUT = os.path.join(ROOT, "data", "problembank")
os.makedirs(OUT, exist_ok=True)

# Fixed order = the import order in lib/problem-bank.ts (hub display order).
TOPIC_ORDER = ["algebra", "functions", "logarithms", "trigonometry", "sequences", "geometry"]


def load_build(slug):
    path = os.path.join(PB_DIR, f"{slug}.py")
    spec = importlib.util.spec_from_file_location(f"pb_{slug}", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.build


def main():
    grand_forms = grand_vars = 0
    for slug in TOPIC_ORDER:
        topic = load_build(slug)()
        assert topic["slug"] == slug, f"{slug}: build() returned slug {topic['slug']!r}"
        n_forms = len(topic["forms"])
        n_vars = sum(len(f["variants"]) for f in topic["forms"])
        mn = min(len(f["variants"]) for f in topic["forms"])
        grand_forms += n_forms
        grand_vars += n_vars
        path = os.path.join(OUT, f"{slug}.json")
        with open(path, "w") as fh:
            json.dump(topic, fh, indent=2, ensure_ascii=False)
            fh.write("\n")
        print(f"wrote {slug}.json: {n_forms} forms, {n_vars} variants (min/form {mn})")
    print(f"TOTAL: {len(TOPIC_ORDER)} topics, {grand_forms} forms, {grand_vars} variants")


if __name__ == "__main__":
    main()
